### ISSUE TITLE
detect if installed?

### ISSUE THREAD

**Issue by tregoning** [vvo/selenium-standalone#100]
It would be handy if there was a programmatic API to detect if 'install' has been run

**Comment by vvo** [comment]
multiple calls to install should not redownload any file if that's what you are against.

Otherwise I am happy to add a command for this, yes. List a `selenium-standalone current` and programmatic friend

**Comment by tregoning** [comment]
Thansk @vvo good to know it won't re-download any files. The use case in my head was for a script (gulp/grunt/npm) task like 'run test' wondering if I should call 'install selenium' on every run (given that it won't re-download) or use the non-existing (yet) install-check. I guess it would depend on how fast/slow running 'install' is on a already installed setup.

Probably for now that's good enough. keep up the good work.
