### ISSUE TITLE
"Killed" on Digital Ocean server

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#102]
Hey I have a basic Ubunut Digital Ocean server, when I run `npm install selenium-standalone`, it just sits for a while and then says `Killed`.

    $ npm install selenium-standalone
    Killed

I can not successfully install `selenium-standalone` on this server, any suggestions?

    $ npm -v
    2.7.4
    $ node -v
    v0.12.2

Npm output

	npm info it worked if it ends with ok
	npm verb cli [ '/usr/local/bin/node',
	npm verb cli   '/usr/local/bin/npm',
	npm verb cli   '--verbose',
	npm verb cli   'install',
	npm verb cli   'selenium-standalone' ]
	npm info using npm@2.7.4
	npm info using node@v0.12.2
	npm verb cache add spec selenium-standalone@^4.4.2
	npm verb addNamed selenium-standalone@>=4.4.2 <5.0.0
	npm verb addNameRange registry:https://registry.npmjs.org/selenium-standalone not in flight; fetching
	npm verb request uri https://registry.npmjs.org/selenium-standalone
	npm verb request no auth needed
	npm info attempt registry request try #1 at 17:16:15
	npm verb request id 05330bfa24b8e996
	npm verb etag "9RQYQ7RR1SQ1D5VSAYKVWMWA0"
	npm http request GET https://registry.npmjs.org/selenium-standalone
	npm http 304 https://registry.npmjs.org/selenium-standalone
	npm verb etag https://registry.npmjs.org/selenium-standalone from cache
	npm verb get saving selenium-standalone to /var/www/.npm/registry.npmjs.org/selenium-standalone/.cache.json
	npm verb addNamed selenium-standalone@4.4.2
	npm verb afterAdd /var/www/.npm/selenium-standalone/4.4.2/package/package.json not in flight; writing
	npm verb afterAdd /var/www/.npm/selenium-standalone/4.4.2/package/package.json written
	npm info install selenium-standalone@4.4.2 into /var/www/personal-cron
	npm info installOne selenium-standalone@4.4.2
	npm verb installOne of selenium-standalone to /var/www/personal-cron not in flight; installing
	npm verb lock using /var/www/.npm/_locks/selenium-standalone-aa76bc62762de851.lock for /var/www/personal-cron/node_modules/selenium-standalone
	npm verb unbuild node_modules/selenium-standalone
	npm verb gentlyRm don't care about contents; nuking /var/www/personal-cron/node_modules/selenium-standalone
	npm verb tar unpack /var/www/.npm/selenium-standalone/4.4.2/package.tgz
	npm verb tar unpacking to /var/www/personal-cron/node_modules/selenium-standalone
	npm verb gentlyRm don't care about contents; nuking /var/www/personal-cron/node_modules/selenium-standalone
	Killed

**Comment by sean-hill** [comment]
Looks like it might be related to this [this](https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what), but I'm just making sure here also. Thanks!

**Comment by sean-hill** [comment]
Awesome, after following that answer, it worked!

**Comment by vvo** [comment]
Nice!
