### ISSUE TITLE
Unclear how to use firefox

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#106]
Hey,

I have both Chrome and Firefox installed on my machine, but when I run my scripts, Chrome opens by default. Is there a way to specify to open Firefox instead? Or is just because my OS has Chrome set as it's default? Thanks!

**Comment by vvo** [comment]
You can open firefox by specifying your `desiredCapabilities` when using selenium. It all depends on the selenium module/library you are using https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session

**Comment by sean-hill** [comment]
Great! Something like this:

	var options = {
		desiredCapabilities: { 
			browserName: 'firefox'
		} 
	};
