### ISSUE TITLE
.selenium directory is not installed 

### ISSUE THREAD

**Issue by eevolt** [vvo/selenium-standalone#111]
Hello!

When running a npm install selenium-standalone, I noticed that the latest version doesn't have the .selenium subdirectory. It's a directory that has the selenium-server jarfile and I am wondering why it is no longer in there? I can't seem to find it anywhere else. Thanks!

**Comment by vvo** [comment]
Hi, it's never installed automatically, you have to:

```sh
selenium-standalone install
```
