### ISSUE TITLE
Chromedriver setup broken

### ISSUE THREAD

**Issue by Kolombiken** [vvo/selenium-standalone#112]
I'm user grunt-webdriver and suddenly it can't locate chromedriver anymore. I posted [an issue on grunt-webdriver](https://github.com/webdriverio/grunt-webdriver/issues/63#event-351106611) and was told it was due to [a recent update here](https://github.com/vvo/selenium-standalone/commit/6b2b9ffbf6f72ffc473cffd3542fcd589843cb7d).

Getting the following error:

```RuntimeError: RuntimeError
(UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The driver executable does not exist: /Users/my-user/my-project/node_modules/grunt-webdriver/node_modules/selenium-standalone/.selenium/chromedriver/2.9-x64-chromedriver```

**Comment by vvo** [comment]
This is unfortunately an issue of grunt-webdriver, answered there

**Comment by Kolombiken** [comment]
Thank you @vvo for quick feedback! Hoping for a fix in grunt-webdriver soon.
