### ISSUE TITLE
run Selenium driver directly instead of launching standalone server

### ISSUE THREAD

**Issue by christian-bromann** [vvo/selenium-standalone#115]
Instead of starting a standalone server it would be nice to start the driver instead to run e2e tests faster. The standalone Selenium Server acts as a proxy between the test script and the browser-specific drivers. The server may be used when running locally, but it's not recommend as it introduces an extra hop for each request and will slow things down.

What do you think?

**Comment by vvo** [comment]
I have already seen someone do it (cannot find it in the issues).

It seems feasible to start only the chromedriver (or the IE driver) right? Can you show how to do it using the standard selenium executable?

This would only work for IE and Chrome I guess? Because the firefox driver I think it's included in the selenium-standalone thing.

We could have an option to start with only either chrome or ie driver, let me know how we can do it using the standard selenium executable

**Comment by christian-bromann** [comment]
for Chrome, Internet Explorer, PhantomJS and Opera we only need to run the server driver on a specific port and we should be good to go. For firefox and safari we need to spawn the actual browser executable with the webdriver extension preinstalled. For firefox the actual final xpi gets build before publishing selenium-webdriver to NPM.

My intention is to make this project a dependency of webdriverio but it would require to be able to run the actual driver instead of the selenium server.

I am happy to contribute on this one. My plan would be to enhance the API to start the driver for Chrome, Internet Explorer, PhantomJS and Opera on a specific port. Safari should be doable too (even though it still requires a manual step to enable the extension in the browser). For firefox I would fallback on starting a standalone server until I figured out how to build the extension without having selenium-webdriver as a dependency of this project. I hope the Selenium guys will publish that xpi separately from the actual node module.

**Comment by vvo** [comment]
Ok let's do, propose an API to start only a driver on a specific port and will be happy to iterate on it :)

**Comment by dandv** [comment]
Possibly related discussion [in Gitter](https://gitter.im/webdriverio/webdriverio?at=5485b7fae37ff191423d949b):

> Is there any way to talk directly to the chrome driver without using Selenium Server?
In ruby I do something like:
>
>     `require 'selenium-webdriver'
>     @browser = Selenium::WebDriver.for :chrome
>     //perform tests`
> Without starting the JAVA stuff.

**Comment by dandv** [comment]
The [WebDriver docs](http://docs.seleniumhq.org/docs/03_webdriver.jsp#webdriver-and-the-selenium-server) mention this:

> You may, or may not, need the Selenium Server, depending on how you intend to use Selenium-WebDriver. **If you will be only using the WebDriver API** you do not need the Selenium-Server. **If your browser and tests will all run on the same machine**, and your tests only use the WebDriver API, **then you do not need to run the Selenium-Server; WebDriver will run the browser directly**.

> There are some reasons though to use the Selenium-Server with Selenium-WebDriver.
>
* You are using Selenium-Grid to distribute your tests over multiple machines or virtual machines (VMs).
* You want to connect to a remote machine that has a particular browser version that is not on your current machine.
* You are not using the Java bindings (i.e. Python, C#, or Ruby) and would like to use HtmlUnit Driver

**Comment by wilmoore** [comment]
:+1: - would be great to see something like this added to webdriverio.

**Comment by samhatoum** [comment]
+1 for this, would be fantastic for speed and memory footprint

**Comment by vvo** [comment]
Just to be clear, yes I am interested by this, I just wont do it myself so feel free to do it and submit pr

**Comment by samhatoum** [comment]
I totally get it, I'm the maintainer of [chimp](https://github.com/xolvio/chimp/) and OSS time vs life are always a struggle! Thank you for your work so far and this great package, hopefully someday I'll get some time.

**Comment by vvo** [comment]
Yep also I dunno how to do it so ppl knowing how to do it are more than welcome

**Comment by snoblenet** [comment]
Does anyone know of a fork or a plugin that implement this?

**Comment by mansn** [comment]
@snoblenet Not sure if this helps you (since it's tied to webdriverio), but this is available for webdriverio:
https://github.com/atti187/wdio-chromedriver-service

**Comment by ElishaKay** [comment]
Awesome! Muchos gracias!
