### ISSUE TITLE
Invalid browser strings launch Internet explorer

### ISSUE THREAD

**Issue by dandv** [vvo/selenium-standalone#118]
```js
var webdriverio = require('webdriverio');

webdriverio
    .remote({desiredCapabilities: {browserName: 'opera'}})
    .init()
    .url('http://www.google.com');
```

This launched IE, not Opera. Turns out that any unrecognized `browserName` launches IE.

I'm on Win7 64-bit.

**Comment by vvo** [comment]
@dandv I am sure this is also the behavior of the standard selenium. Maybe raise the issue here or make opera work.

Thanks
