### ISSUE TITLE
Connection to port 4444 failed

### ISSUE THREAD

**Issue by GrzegorzZajac000** [vvo/selenium-standalone#119]
I installed selenium-standalone on ubuntu Droplet on DigitalOcean. First run was succesfull, but each next ends with this error:

root@Ubuntu:~# selenium-standalone start
04:52:34.976 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver
04:52:35.038 INFO - Java: Oracle Corporation 24.79-b02
04:52:35.038 INFO - OS: Linux 3.13.0-57-generic amd64
04:52:35.074 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
04:52:35.219 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
04:52:35.220 INFO - Driver class not found: com.opera.core.systems.OperaDriver
04:52:35.220 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:54
        throw err;
              ^
Error: Unable to connect to selenium
    at hasStarted (/usr/local/lib/node_modules/selenium-standalone/lib/check-started.js:17:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
root@Ubuntu:~#

**Comment by vvo** [comment]
You may have something listening on port 4444 already. Maybe try rebooting

**Comment by GrzegorzZajac000** [comment]
Nope. It doesn't work.

root@Ubuntu:~# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0    308 178.62.87.130:ssh       188.123.222.205.m:63296 ESTABLISHED
tcp        0      0 178.62.87.130:ssh       188.123.222.205.m:63315 ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  5      [ ]         DGRAM                    9061     /dev/log
unix  2      [ ]         DGRAM                    10784
unix  3      [ ]         DGRAM                    7718
unix  3      [ ]         STREAM     CONNECTED     7664
unix  3      [ ]         STREAM     CONNECTED     9046
unix  3      [ ]         STREAM     CONNECTED     8944
unix  3      [ ]         STREAM     CONNECTED     8202     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNECTED     8945
unix  3      [ ]         STREAM     CONNECTED     8986     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNECTED     8966     /var/run/dbus/system_bus_socket
unix  2      [ ]         STREAM     CONNECTED     11600
unix  3      [ ]         DGRAM                    7719
unix  3      [ ]         STREAM     CONNECTED     7674     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNECTED     8937
unix  3      [ ]         STREAM     CONNECTED     9047     /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    9238
unix  2      [ ]         DGRAM                    9613
unix  3      [ ]         STREAM     CONNECTED     8192
unix  2      [ ]         STREAM     CONNECTED     11224
unix  3      [ ]         STREAM     CONNECTED     8965

**Comment by vvo** [comment]
can you try:

```sh
selenium-standalone start -- --debug
```

**Comment by vvo** [comment]
Then can you try to put some debugging in https://github.com/vvo/selenium-standalone/blob/master/lib/check-started.js (like console.log(hub)) thx

**Comment by GrzegorzZajac000** [comment]
root@Ubuntu:~# selenium-standalone start -- --debug
05:45:28.445 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver
05:45:28.516 INFO - Java: Oracle Corporation 24.79-b02
05:45:28.516 INFO - OS: Linux 3.13.0-57-generic amd64
05:45:28.546 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
05:45:28.781 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
05:45:28.782 INFO - Driver class not found: com.opera.core.systems.OperaDriver
05:45:28.782 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:54
        throw err;
              ^
Error: Unable to connect to selenium
    at hasStarted (/usr/local/lib/node_modules/selenium-standalone/lib/check-started.js:17:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
root@Ubuntu:~#

**Comment by GrzegorzZajac000** [comment]
var hub: http://localhost:4444/wd/hub/status

**Comment by vvo** [comment]
Sorry can you do:

```sh
selenium-standalone start -- -debug
```

instead of --debug

**Comment by vvo** [comment]
If nothing works, try the regular selenium server: http://www.seleniumhq.org/ and tell me if it's working

**Comment by GrzegorzZajac000** [comment]
root@Ubuntu:~# selenium-standalone start -- -debug
var hub: http://localhost:4444/wd/hub/status
03:06:39.594 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver
03:06:39.729 INFO - Java: Oracle Corporation 24.79-b02
03:06:39.729 INFO - OS: Linux 3.13.0-57-generic amd64
03:06:39.782 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
03:06:39.782 INFO - Selenium server running in debug mode.
03:06:40.083 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
03:06:40.084 INFO - Driver class not found: com.opera.core.systems.OperaDriver
03:06:40.084 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:54
        throw err;
              ^
Error: Unable to connect to selenium
    at hasStarted (/usr/local/lib/node_modules/selenium-standalone/lib/check-started.js:18:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by GrzegorzZajac000** [comment]
Regular selenium server works in the same way.
First run on clean server is correct, but each next ends with this or similar error.

**Comment by vvo** [comment]
So this looks like a selenium etror, better check for selenium issues

**Comment by asinyagin** [comment]
I had the same issue. That solution helped me http://stackoverflow.com/questions/32707201/selenium-standalone-server-not-starting

**Comment by vvo** [comment]
good thanks @asinyagin for pointing the solution: http://stackoverflow.com/a/32729965/147079
