### ISSUE TITLE
it looks for for Selenium 2.46 instead of 2.47.1

### ISSUE THREAD

**Issue by vladikoff** [vvo/selenium-standalone#120]
I set "version" as 2.47.1 in my code, see https://github.com/vladikoff/ss-247-nightly/blob/master/index.js#L12 

But the module is looking for this file: `.selenium/selenium-server/2.46.0-server.jar` I cannot figure out why, is it cached somewhere?

### STR

```
git clone https://github.com/vladikoff/ss-247-nightly.git
cd ss-247-nightly
npm i
npm test
```
ref https://github.com/vladikoff/ss-247-nightly

### Expected

2.47.1 to run

### Actual

```
 ss-247-nightly@1.0.0 test /Users/vladikoff/tmp/ss-247-nightly
> node ./index.js


/Users/vladikoff/tmp/ss-247-nightly/index.js:16
    if (err) throw err;
                   ^
Error: Missing /Users/vladikoff/tmp/ss-247-nightly/node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar
    at /Users/vladikoff/tmp/ss-247-nightly/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at Object.cb [as oncomplete] (fs.js:169:19)
npm ERR! Test failed.  See above for more details.
```

I have no clue where it is getting the 2.46. info from?

**Comment by vladikoff** [comment]
Ah the version should be in both places:

```
selenium.install({
  // check for more recent versions of selenium here:
  // http://selenium-release.storage.googleapis.com/index.html
  version: '2.47.1',
}, function() {

  selenium.start({
    version: '2.47.1',
  }, function(err, cp) {
```

**Comment by nekoyama** [comment]
How did you fix the Error? Funny thought I'getting the same: 

Error: Missing /../../node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar
    at /../../node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at Object.cb [as oncomplete] (fs.js:169:19)

**Comment by vladikoff** [comment]
@nekoyama did you do `.install` before `.start`? maybe it is looking to start it but cannot find it. check the `.selenium` directory to see what is in there.

**Comment by nekoyama** [comment]
@vladikoff actually I'm checking it: 

```
var gulp = require('gulp');
var selenium = require('selenium-standalone');
var nightwatch = require('gulp-nightwatch');

gulp.task('selenium', function (done) {
  selenium.install({
      // check for more recent versions of selenium here:
      // http://selenium-release.storage.googleapis.com/index.html
      version: '2.45.0',
      baseURL: 'http://selenium-release.storage.googleapis.com',
      drivers: {
        chrome: {
          version: '2.15',
          arch: process.arch,
          baseURL: 'http://chromedriver.storage.googleapis.com'
        },
        ie: {
          version: '2.45.0',
          arch: 'ia32',
          baseURL: 'http://selenium-release.storage.googleapis.com'
        }
      },
    logger: function (message) { }
  }, function (err) {
    if (err) return done(err);

    selenium.start(function (err, child) {
      if (err) return done(err);
      selenium.child = child;
      done();
    });
  });
});

gulp.task('integration', ['selenium'], function () {
  return gulp.src('')
    .pipe(nightwatch({
      configFile: 'nightwatch.json',
      cliArgs:['--group Logbooks']
    }));
});


gulp.task('test', ['integration'], function () {
  selenium.child.kill();
});

```

**Comment by vladikoff** [comment]
@nekoyama compare it with: https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/start.js#L21 

You might need to set the version in `.start` too

**Comment by nekoyama** [comment]
@vladikoff But before it was starting and working properly without setting up the start. And even when deleting the 2.48.2 from the folder it shouldn't conflict... Anyways I think that this should still to be checked on the npm package itself 
https://github.com/vvo/selenium-standalone/issues/158#issuecomment-172549483

**Comment by hijazi** [comment]
Hi, I'm facing a similar problem, I installed version 3.0.1 using:
`selenium-standalone install --version=3.0.1 --baseURL=https://selenium-release.storage.googleapis.com`
And when I start it I get:
`Error: Missing /usr/lib/node_modules/selenium-standalone/.selenium/selenium-server/2.53.1-server.jar`

and trying
`selenium-standalone start --version=3.0.1`
Gave:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0`

Any ideas?

**Comment by hijazi** [comment]
The following comment solved my issue :)
https://github.com/Polymer/web-component-tester/issues/417#issuecomment-259469578
