### ISSUE TITLE
Install offline

### ISSUE THREAD

**Issue by oliviertassinari** [vvo/selenium-standalone#121]
The call to `install()` when the driver is already installed failed in offline mode.
This makes the `grunt-webdriver` inusabled when offline. A method `isInstalled()` would be another way to fix it.

**Comment by Waxolunist** [comment]
+1
Starting without call to install should be possible.

**Comment by vvo** [comment]
Yes install fail when offline because we check the distant ETAG to be the same as the saved one.

Welcoming contribution on isInstalled().

**Comment by oliviertassinari** [comment]
Alright, I will try.

**Comment by vvo** [comment]
we could store an `.installed` file when the whole process finished.

It would only be a mean to indicate that the install process finished, not that the installed version complies to the asked version in the `.install` call.

**Comment by snoblenet** [comment]
Any updates on this?

(The current scenario means I can't be productive on my long semi-rural train ride too and from work...)

**Comment by vvo** [comment]
Nobody took the lead on this task

**Comment by oliviertassinari** [comment]
Last time I had this issue case, I was in the train with no internet connection. This is an issue I do no longer face when working with a dockerized version of selenium.

**Comment by LucasOder66** [comment]
We have 2020 and I think it might still not be possible to install selenium in an offline eviroment. I love all the cool open source tools but dude, they all need to make offline installers for their tools.

**Comment by oliviertassinari** [comment]
Closing as I do no longer need this feature.
