### ISSUE TITLE
Selenium process impossible to kill

### ISSUE THREAD

**Issue by cefn** [vvo/selenium-standalone#122]
I believe that the code I've shared at...
https://gist.github.com/cefn/92de780976090bf89485
...should both launch, test and close a Chrome browser window as part of a Mocha test suite. 

Although the Chrome window launches and tests fine, I can't seem to find any combination of childProcess.kill() or process.kill(childProcess.pid) with "SIGHUP" "SIGTERM" "SIGKILL" or anything else which will cause the browser window to close again.

Any idea what I should be doing differently?.

**Comment by vvo** [comment]
try cp.kill() we have a test that ensures it does works: https://github.com/vvo/selenium-standalone/blob/master/test/programmatic.js

**Comment by vvo** [comment]
Reopen or create a failing test case if needed
