### ISSUE TITLE
OSX 10.11 El capitan unable to open chromedriver binary

### ISSUE THREAD

**Issue by dimirey** [vvo/selenium-standalone#130]
After reinstalling selenium-standalone to the latest version on OSX 10.11 I attempted to initialize the chromedriver. I received an error stating that the binary was unable to be opened. After changing the name of the binary from '2.18-x64-chromedriver' to '2_18-x64-chromedriver' and editing the default-config.js file I am now able to successfully launch chromedriver.

**Comment by vvo** [comment]
Can you do a PR to fix this? Thanks

**Comment by weems** [comment]
```javascript
/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:56
        throw err;
        ^

Error: Missing /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver
    at /usr/local/lib/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

Is this the same issue? When I ran selenium-standalone start, I got this error and/or traceback.

**Comment by 0000000009** [comment]
Http// false cd

**Comment by vvo** [comment]
@0000000009 yes?
