### ISSUE TITLE
Make selenium.start return the process

### ISSUE THREAD

**Issue by silvenon** [vvo/selenium-standalone#131]
Not sure if this is a good idea, but this:

``` js
var seleniumServer = selenium.start();
// ...
seleniumServer.kill();
```

seems a lot cleaner than:

``` js
var seleniumServer;
selenium.start(function(err, child) { seleniumServer = child; })
// ...
seleniumServer.kill();
```

**Comment by vvo** [comment]
agree, this is done this way only because the paths (driver installs) check is done asynchronously.

I think we could change this and keep the backward compat. PR accepted :)

**Comment by quanyaji** [comment]
you can use promisify
```
const { promisify } = require('util');
process = await promisify(server.start)({});
```
