### ISSUE TITLE
No Java runtime present, requesting install. Error: Another Selenium process is already running

### ISSUE THREAD

**Issue by starryeyez024** [vvo/selenium-standalone#140]
@vvo, In my Polymer project, in the file: `polymer/node_modules/web-component-tester/node_modules/wct-local/package.json`, it specifies using selenium-standalone 4.6.1 or greater and I still have this issue. 

*package.json:*

```
  "dependencies": {
    "chalk": "^1.1.1",
    "cleankill": "^1.0.0",
    "freeport": "^1.0.4",
    "launchpad": "^0.4.4",
    "lodash": "^3.0.1",
    "selenium-standalone": "^4.6.1",
    "which": "^1.0.8"
  },
```

*error message:*

```
^MBP:polymer $ gulp test:local
[15:11:20] Using gulpfile ~/Sites/polymer/gulpfile.js
[15:11:20] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
----------
selenium-standalone installation starting
----------
---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: /Users/---/Sites/polymer/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip
to: /Users/---/Sites/polymer/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver
---
File from http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar has already been downloaded
---
File from http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip has already been downloaded
-----
selenium-standalone installation finished
-----
No Java runtime present, requesting install.
[15:11:22] 'wct:local' errored after 1.41 s
[15:11:22] Error: Another Selenium process is already running
```

I also get a popup saying "To view this web content, you need to install the Java Runtime Environment" - which I have done. When I visit the [Java install page](https://java.com/en/download/installed.jsp) it says "You have the recommended Java installed (Version 8 Update 60). "

[originally posted here](https://github.com/Polymer/web-component-tester/issues/206#issuecomment-145280063)

**Comment by sebs** [comment]
did you find a solution?

**Comment by RedBulli** [comment]
I got this working by installing the Java Development Kit

**Comment by sebs** [comment]
I had a similar experience: My ableton live was giving me the same message and I installed a OLD Java development Kit. That worked for ableton live and its "Max for Live" system. Coming from this I found a helper to manage different java versions. 

https://github.com/gcuisinier/jenv

If you are using your computer for more than one job, there might be a conflict anyways. However with the new Java version, I got a new error but a very good clue. ;)

Ill be back with more news ;)

**Comment by vvo** [comment]
@starryeyez024 Do you have java installed? What does `java -version` states? Thanks

**Comment by starryeyez024** [comment]
I think the source of my problems was that I needed to install a JDK. I was getting this:

```
$ java -version
No Java runtime present, requesting install.
$ javac -version
No Java runtime present, requesting install.
```

Then I Installed: [Java SE 8ux](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
and ran the commands again:

```
$ javac -version
javac 1.8.0_65
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by vvo** [comment]
Great, fixed?

**Comment by DullReferenceException** [comment]
It would be really great if this was reopened and the fix was somehow giving an error message that describes that a JDK cannot be found; many developers at my company have been bit by this and wasted time searching for a rogue running selenium process that does not exist.

**Comment by vvo** [comment]
I am open to PR on this subject :)
