### ISSUE TITLE
[Error: Another Selenium process is already running]

### ISSUE THREAD

**Issue by zhangmeng712** [vvo/selenium-standalone#145]
I've installed selenium-standalone through "npm install -g selenium-standalone" , but now I need to start server programmaticly, So I installed locally "npm install selenium-standalone" and wrote start.js like followings:
var selenium = require('selenium-standalone');
selenium.start({
    seleniumArgs:['-port', '5555']
},function(err, child) {
    child.stderr.on('data', function(data){
        console.log(data.toString());
    });
});
but when I executed node start.js
the console showed   [Error: Another Selenium process is already running]
I've checked the ps aux|grep selenium but no process pid returned 
I don't know why?
I tried pkill -f selenium-standalone but it not working

**Comment by vvo** [comment]
Check https://github.com/vvo/selenium-standalone/issues/140
