### ISSUE TITLE
Support for Microsoft Edge

### ISSUE THREAD

**Issue by liabru** [vvo/selenium-standalone#147]
I'm using `browserName: 'MicrosoftEdge'` in one of my [webdriverio](http://webdriver.io/) configurations.

When I run it I get the error:

> ERROR: The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687

I've installed the edge driver, but as the error says you need to also set the `webdriver.edge.driver` system property. I'm not sure how to do this through selenium standalone. I've tried using `spawnOptions` but I couldn't get it working.

According to this [blog post comment](https://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/#div-comment-2013) you need to set a system property via the `java -D` parameter, e.g:

> start /MIN java -Dwebdriver.edge.driver=”C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe” -jar %seleniumjar% -role node -port %port% -browser browserName=”MicrosoftEdge”,maxInstances=5 -hub %hub_url_local%

Is this possible through selenium-standalone?

Thanks.

**Comment by liabru** [comment]
Looks like I managed to get it working using:

    selenium.start({
        seleniumArgs: ['-Dwebdriver.edge.driver=C:\\Program Files (x86)\\Microsoft Web Driver\\MicrosoftWebDriver.exe']
    });

That said, I now get 'Unknown command received'. Looks like the edge webdriver really is too limited to be useful right now.

**Comment by vvo** [comment]
Thx for the debug, will be useful to googlers/other users.

**Comment by ewanharris** [comment]
Just for anyone looking to use this, not sure if anything has changed since the original comment but setting `seleniumArgs` doesn't work for me, `javaArgs` does however. So the below should work

````
javaArgs: ['-Dwebdriver.edge.driver=path_to_webdriver']
````

@vvo  Will Edge support be added to selenium-standalone at any point in the near future?

**Comment by vvo** [comment]
> @vvo Will Edge support be added to selenium-standalone at any point in the near future?

Do you have any idea what are the requirements to make IE edge support smooth? If so please help!

**Comment by ewanharris** [comment]
I wouldn't say I'm well versed enough in the library to answer that question, what would you class as support? The full lifecycle of install and start? I'd be more than happy to work on a PR for this. I see some issues figuring out where to download the driver from however

**Comment by vvo** [comment]
> The full lifecycle of install and start? I

Yes just ensuring using microsoft edge is smooth with selenium-standalone. The lib code is readable and the lib can be hacked by cloning the repo then using npm link
