### ISSUE TITLE
Starting Specific Drivers

### ISSUE THREAD

**Issue by paranoid-android** [vvo/selenium-standalone#149]
Hello,

I am using this project in my Node.js app. I am trying to figure out how to start selenium with just phantomjs. I do not care about Chrome, Firefox, etc. at this time. At this time, I have:

```
function start(onStarted) {
  selenium.start(
    { drivers: {} },
    onStarted
  );
}      
```

Its unclear to me what `drivers` is. Is it supposed to be an array or an object? Either way, I'm not sure how you say "start phantomjs".

Thank you!

**Comment by vvo** [comment]
To say "start phantomjs" this is when you use the started selenium server that you need to send the right capabilities. For example by sending "browserName: 'phantomjs'" when calling the started selenium server with any selenium library.

**Comment by paranoid-android** [comment]
@vvo - Thank you for your response. I'm still slightly confused. I apologize for my ignorance. 

Are you saying that the line above `selenium.start` is starting a library and *not* the selenium server? I had the belief I could use `selenium.start` to replace my original approach of having to manually run the following from the command line:

`java -jar node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-2.47.1.jar` 

So, does the line `selenium.start` start the selenium server or the library?

**Comment by vvo** [comment]
It does start the selenium server but it does not start any browser. The selenium server is then waiting for you to send him commands to start browsers. Thus to run phantomjs you only need to pass the right browser capability when sending a command to the selenium server.

Is that clearer?

**Comment by paranoid-android** [comment]
I understand in theory. However, I do not understand in practice. For example, I have the following:

```
function start(onStarted) {
  selenium.start(
    { drivers: 'phantomjs'   },
    onStarted
  );
}   
```

When the code gets executed, I get an error that says:

[Error: Missing /Users/user/Project/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver]

When I run `lsof -i -P | grep -i "listen"`, I do not see selenium started at all. So, at this point, I'm totally confused.

**Comment by vvo** [comment]
There should be no need to specify anything in the "drivers" section, let the default flow and you should be good.

**Comment by paranoid-android** [comment]
@vvo Thank you for your response. Also, thank you for sticking with this.

When I run
```
selenium.start(onStarted);
```
I receive the following error:
```
Error: Missing /Users/user/Project/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar
```

I do not understand why I'm receiving this error. I have the following in my `package.json` file:

```
"selenium-server-standalone-jar": "^2.47.1",
"selenium-standalone": "^4.7.1"
```
When I look in the ./node_modules/selenium-standalone directory, I do not see a `.selenium` directory. Its like something is not getting installed. I do not understand this. Am I totally misunderstanding something?

**Comment by vvo** [comment]
Before doing .start() you need to do .install(cb)

**Comment by paranoid-android** [comment]
@vvo boy oh boy do I feel dumb :).

Its now working thanks to your patience and help. Now that I see how it all comes together its so obvious and so simple. The installation into the `node_modules/selenium-standalone/.selenium` directory kind of threw me off.

Thank you so much for your help. I can't express my gratitude enough.

**Comment by vvo** [comment]
Its ok I do think the error messages could be more useful here. Sorry you wasted time.

**Comment by vvo** [comment]
have fun testing!
