### ISSUE TITLE
Should fetch executables over HTTPS or require matching checksums

### ISSUE THREAD

**Issue by jyasskin** [vvo/selenium-standalone#152]
It looks like selenium-standalone fetches Selenium and the WebDriver plugins over URLs like http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar, which allows any network attacker to replace the binaries I'm about to execute. You should either fetch over HTTPS, or make your users pass in an expected hash of the download, which you should verify before unpacking it.

**Comment by vvo** [comment]
Indeed, I would by happy to just switch to https.

Do you think you can do the change?
