### ISSUE TITLE
Support user-specified basePath

### ISSUE THREAD

**Issue by knksmith57** [vvo/selenium-standalone#153]
Allowing the developer to specify the installation directory and returning the `fsPaths` mapping allows for greater flexibility and control over where the `jar` files are installed to. This also allows developers easy programmatic access to the jars, which may be required in some applications (eg: nightwatch).

**Comment by knksmith57** [comment]
This update supports programmatically setting the `basePath` where the downloaded files will be put.

Via cli:
```
$ selenium-standalone install --basePath my/custom/path
```

Via programmatic API:
```
'use strict';

var path     = require('path');
var selenium = require('selenium-standalone');

selenium.install({
  logger: console.log.bind(console),
  basePath: path.resolve(process.cwd(), 'my/custom/path')
}, function(err, resp) {
  console.log('---> completed downloading');

  if (err) {
    console.error(err);
  }

  console.log('downloaded selenium jar to: %s', resp.selenium.installPath);
});
```

**Comment by nekoyama** [comment]
I recently installed a package that has selenium-standalone has dependency, so I've got @4.8.0
But I'm getting this error: 
```
[15:17:29] 'selenium' errored after 1.18 min
[15:17:29] Error: Missing C:\projects\Git\preciosita\node_modules\selenium-stand
alone\.selenium\selenium-server\2.48.2-server.jar
    at C:\projects\Git\preciosita\node_modules\selenium-standalone\lib\check-pat
hs-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)

I haven't get this issue before, any clue?
