### ISSUE TITLE
Add "engines" flag to package.json warning about Node 0.10 incompatibility

### ISSUE THREAD

**Issue by azakus** [vvo/selenium-standalone#156]
This commit, https://github.com/vvo/selenium-standalone/commit/3d6525a65a0879577f41014465e33990e56a7459, breaks Node 0.10 compatibility as `fs.access` is new in 0.12.

It would be very helpful to set the `engines` flag in `package.json` to alert to this incompatibility:
https://docs.npmjs.com/files/package.json#engines

**Comment by vvo** [comment]
Good idea, we could also make it work, wonder if that's worth it.

Can you submit a PR?

**Comment by vkramskikh** [comment]
I think it's worth it. 4.7.2 worked fine with 0.10, 4.8.0 doesn't because of usage of fs.access()

**Comment by vvo** [comment]
pr-welcomed

**Comment by ryan-roemer** [comment]
Other option -- there's a https://github.com/sindresorhus/fs-access ponyfill.

**Comment by vvo** [comment]
Good idea
