### ISSUE TITLE
How to use selenium grid programmatically

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#157]
Hey I was just curious how to run `selenium-standalone start -- -role hub` with the Programmatic API. Is this correct?

    selenium.start({
        seleniumArgs: ['-role', 'hub']
    }, ...)

**Comment by turnerhayes** [comment]
That has worked for me; the problem I have is that I'm not sure how to get any information about the started hub (address to connect to/register to). Probably because that's information known only to the Java process and not easily exposed to the Node package. I assume the only way would be to parse the generated log messages (ew).

**Comment by vvo** [comment]
> seleniumArgs: ['-role', 'hub']

Yes this should work.

As for knowing the url/port it should be the default ones of the selenium server unless you specify other values. Let me know

**Comment by turnerhayes** [comment]
I have had the IP vary, without setting a value, I get one value while on one public wifi, and another value on a different public wifi.

**Comment by sean-hill** [comment]
@vvo do I need to call `selenium.start` multiple times, once to create the hub, and then another to create the node? For instance this is how I do it from the command line:

    $ selenium-standalone start -- -role hub
    $ selenium-standalone start -- -role node -hub http://localhost:4444/grid/register

How would I accomplish this with the programatic API?

**Comment by vvo** [comment]
> How would I accomplish this with the programatic API?

call selenium.start twice with different parameters should do it, did you try?

**Comment by sean-hill** [comment]
@vvo I tried creating the hub with 

	selenium.start({
		seleniumArgs: ['-role', 'hub']
	}, function (err, child) {
		...
	});

But your `get-selenium-hub.js` is trying to connect to `http://localhost:4444/wd/hub/status` which according to [this](https://github.com/seleniumhq/selenium/issues/624) post is only for the standalone server, not for the hub. So I get this error when trying to request it:

	Error: connect ECONNREFUSED 127.0.0.1:4444
	code: 'ECONNREFUSED',
	errno: 'ECONNREFUSED',
	syscall: 'connect',
	address: '127.0.0.1',
	port: 4444 } undefined

It looks like the URL should be `http://localhost:4444/sessions`, but may be wrong. What do you think?

**Comment by sean-hill** [comment]
@vvo here's a code sample to replace `get-selenium-hub.js` that worked for me when working with selenium grid. I don't like the naming of my variables, but it works.

    module.exports = getSeleniumHub;

    var URI = require('URIjs');

    function getSeleniumHub(seleniumArgs) {

      var port = 4444;
      var hostname = 'localhost';
      var portArg = seleniumArgs.indexOf('-port');
      var hubArg = seleniumArgs.indexOf('-hub');
      var onlyHub = seleniumArgs.indexOf('hub');

      if (hubArg !== -1) {
        hubURI = new URI(seleniumArgs[hubArg + 1]);
        hostname = hubURI.hostname() || hostname;
        port = hubURI.port() || port;
      }

      if (portArg !== -1) {
        port = seleniumArgs[portArg + 1];
      }

      var urlParams = (onlyHub !== -1) ? '/sessions' : '/wd/hub/status';

      return 'http://' + hostname + ':' + port + urlParams;

    }

**Comment by sean-hill** [comment]
Hey @vvo I upgraded to `v5.0.0` and all is well :)

**Comment by vvo** [comment]
Awesome :)

**Comment by sean-hill** [comment]
Hey @vvo I created this gist to show how I accomplished this in a clean way :smile: 

Check it out [here](https://gist.github.com/sean-hill/73552b74e79367182edf)!

**Comment by vvo** [comment]
Thanks!
