### ISSUE TITLE
When using the programmatic API s version number for selenium it doesn't get updated

### ISSUE THREAD

**Issue by nekoyama** [vvo/selenium-standalone#158]
I recently installed a package that has selenium-standalone has dependency, so I've got @4.8.0
But I got this error: 

```
[15:17:29] 'selenium' errored after 1.18 min
[15:17:29] Error: Missing C:\projects\Git\preciosita\node_modules\selenium-stand
alone\.selenium\selenium-server\2.48.2-server.jar
    at C:\projects\Git\preciosita\node_modules\selenium-standalone\lib\check-pat
hs-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

So selenium got updated as well with the version 2.48.2... 
The little thing that blocked me for hours was that on my gulp-file I had: 

```
gulp.task('selenium', function (done) {
  selenium.install({
      version: '2.45.0',
      baseURL: 'http://selenium-release.storage.googleapis.com',
bla bla
        }
      },
    logger: function (message) { }
  }, function (err) {
```

Little issue here: we can't specify something like '^2.45.0' in the gulp-file. 
A bit confusing cause you think that all should be updated... And when you remember the little tweak that you had for it, you already spend some time understanding what was the issue and why your tests didn't run!  :cry:

**Comment by vvo** [comment]
Hi @nekoyama, I have trouble understading what we should need to change here to solve this? thanks

**Comment by nekoyama** [comment]
Hello @vvo, 

The problem is that you give the option on the programmatic API to use a selenium-server version,  in the case of my gulpfile I'm using 2.45.0 but when updating npm I get a different version, the latest 2.48.2 which is not compatible so then I have to reinstall it manually.
