### ISSUE TITLE
unable to connect to selenium-server started via an SSH session

### ISSUE THREAD

**Issue by tnguyen14** [vvo/selenium-standalone#159]
when I run `selenium-standalone start` over an SSH session, for some reason when I run the tests with webdriverio, it cannot connect to the selenium server.

**Comment by stephenash** [comment]
Are you running the tests from within the same SSH session (or at least on the same remote server)? Or are you starting the tests from another machine and wanting to connect to that remote server?

If the latter, you could try starting the server with the hub role:
```
selenium-standalone start -- -role hub
```

That will output the hostname/port that nodes are expected to connect with.

**Comment by tnguyen14** [comment]
@stephenash maybe I misunderstand the way selenium sever works, but what I want is to start the selenium server from a remote machine as a background process, then have the tests run on the host machine at a later time.

When I tried running it with the hub role as suggested, I get this error:

```
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@58bd507e, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]
```

**Comment by tnguyen14** [comment]
I think I missed the fact that I need to run at least a node and register that with the hub as well.

**Comment by vvo** [comment]
Thanks for getting back here with your workaround
