### ISSUE TITLE
Specify -port programmatically

### ISSUE THREAD

**Issue by decoursin** [vvo/selenium-standalone#163]
This below wouldn't start selenium on port 4446:
```
selenium.start({
     port: 4446,
     version: ....,
     etc
```
Instead, you have to do this:
```
selenium.start({
     seleniumArgs: ['-port', 4446]
     version: ....,
     etc
})
```
I'd prefer the former API, but it doesn't matter that much. Either way, there should be documentation how to specify the port, but there's no examples or anything, save the one example using the commandline.

Also, the options for selenium.start(options), can take version, which isn't listed in your documentation. This lead me to believe port would work too, but it doesn't.

**Comment by vvo** [comment]
Indeed, can you submit a documentation to specify the port? And for the other documentation issue as well.

Thanks, would be awesome to have you as a contributor :)

**Comment by decoursin** [comment]
Thanks! But I don't think that I'm going to get around to this. Good luck!
