### ISSUE TITLE
Passing browser arguments

### ISSUE THREAD

**Issue by vladikoff** [vvo/selenium-standalone#164]
Hey @vvo do you know by any chance if it is possible to pass browser executable arguments to selenium? this is different from `desiredCapabilities`. 

My end goal is to pass the `-jsdebugger` flag, there is no Firefox profile option for it, just the browser arg. 

Ref https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-jsconsole

Thanks!

**Comment by vvo** [comment]
Sorry no I do not know.

This is more of a selenium question you can ask on stackoverflow/google

**Comment by vladikoff** [comment]
Ok thanks!
