### ISSUE TITLE
Set custom user-agent for Firefox

### ISSUE THREAD

**Issue by pietrovismara** [vvo/selenium-standalone#168]
I'm using selenium-standalone with [webdriverio](http://webdriver.io/) and i'm trying to set a custom user-agent.

```
var selenium = require('selenium-standalone');
var webdriverjsAngular = require('webdriverjs-angular');
var FirefoxProfile = require('firefox-profile');
var myProfile = new FirefoxProfile();
myProfile.setPreference("general.useragent.override", "custom-user-agent");


var webDriverOptions = {
    desiredCapabilities: {
        browserName: 'firefox',
        firefox_profile: myProfile
    }
};
var seleniumOptions = {
    drivers: {
        chrome: {
            version: '2.9',
            arch: process.arch,
            baseURL: 'https://chromedriver.storage.googleapis.com'
        },
    },
};

selenium.start(seleniumOptions, function(err, child) {
    webdriverjsAngular.remote(webDriverOptions)
     .....
}
```
First of all, i can't find any hint on how to set the driver for firefox on your docs, you just show for chrome and ie.
Anyway the code is working, except the settings for `firefox-profile` are not used, and Firefox is still using this user-agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 `.

Could you help me?

**Comment by vvo** [comment]
Sorry I do not know how to do that. Maybe @vladikoff? see https://github.com/vvo/selenium-standalone/issues/164

**Comment by vvo** [comment]
I think you need to use myProfile.encoded(asyncFn) as per https://github.com/saadtazi/firefox-profile-js#i-wanna-see-it

Then pass it as you did.

**Comment by vladikoff** [comment]
here you go 

https://github.com/mozilla/fxa-content-server/blob/master/tests/tools/firefox_profile_creator.js#L39

**Comment by pietrovismara** [comment]
Thank you ;)
