### ISSUE TITLE
Firefox >41 shows a "firstrun" homepage instead of the tests

### ISSUE THREAD

**Issue by nolanlawson** [vvo/selenium-standalone#169]
I can't get selenium-standalone to work on any version of Firefox after 41, because it always just shows this home page instead of the tests:

![screenshot 2016-03-06 22 22 10](https://cloud.githubusercontent.com/assets/283842/13560118/e47074ea-e3e9-11e5-9545-fbd4b0ead7d8.png)

I googled/SO'ed around for awhile and didn't find any solutions. I'm using Selenium 2.52.0, wd 0.4.0, and selenium-standalone 5.0.0. It's loading `https://www.mozilla.org/en-US/firefox/44.0.1/firstrun/learnmore/` instead of the tests. Is there a known fix for this problem?

**Comment by nolanlawson** [comment]
Example [SO question with people complaining about this](http://stackoverflow.com/questions/33937067/firefox-webdriver-opens-first-run-page-all-the-time).

**Comment by vvo** [comment]
Hi, this seems more like a generic selenium/firefox driver issue instead of a selenium-standalone issue (which is only here to download and start selenium). What do you think?

**Comment by vvo** [comment]
See this: https://github.com/SeleniumHQ/selenium/issues/1430

**Comment by nolanlawson** [comment]
Yes, it does seem fixed on the Selenium side. Also somehow I'm no longer able to reproduce with selenium-standalone (using latest Selenium, oddly it did reproduce a couple times at the beginning), so I'm just going to close this.

**Comment by knownasilya** [comment]
Offtopic @nolanlawson how did you get firefox running with selenium-standalone?

**Comment by vvo** [comment]
@knownasilya Can you open a new issue? If firefox is installed, it should work by default, maybe not on latest versions, see: #181
