### ISSUE TITLE
How to Run this standalone with phantomjs?

### ISSUE THREAD

**Issue by tegarraharditya** [vvo/selenium-standalone#171]
Is it possible to install this standalone using phantomjs?

**Comment by vvo** [comment]
If you have phantomjs installed locally it's then only about using any webdriver library and asking for phantomjs browser.

Depending on the webdriver library you are using the syntax to specify using phantomjs could be different.

Let me know if you need further help or if you do not understand what am I talking about.

**Comment by xhuang26** [comment]
Trying to run standalone with phantomjs from terminal, Is this a reasonable format:
selenium-standalone start -Dphantomjs.binary.path=./node_modules/phantomjs-prebuilt/bin/phantomjs
