### ISSUE TITLE
Proxy Hook

### ISSUE THREAD

**Issue by JeffHerb** [vvo/selenium-standalone#174]
I have been looking into this project as a possible solution for downloaded selenium and specific drivers for my enterprises web applications. But one of the killer is the inability to use this tool behind an enterprise firewall. What is the possibility of adding proxy support as a configurable set of options that can be passed to the request module. Even the ability to download over http instead of https would be a nice start.

Additional Note:
Environmental variables are not an option where I work as all variables a flushed on a daily bases with fresh images nightly. This is a security thing and we can not change it.

**Comment by vvo** [comment]
Internally we use request and it provides environment variables. 

I don't get why you cannot use env variables but if you want you can submit a PR allowing to pass options to the request module directly.

https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables and yes

**Comment by alcaneo** [comment]
Hello,

Got the same issue, I don't why I could not get it work simply with the environment variables.
I then had to add the proxy support, I'll propose a PR this afternoon.

**Comment by vvo** [comment]
> I'll propose a PR this afternoon.

Awesome!

**Comment by alcaneo** [comment]
I use selenium-standalone through wdio-selenium-standalone-service, to set the proxy parameter you have to add the following code in wdio.conf.js :
```javascript
    services: ['selenium-standalone'],
    seleniumLogs: "./selenium.log",
    seleniumInstallArgs: {
        //Used by selenium-standalone to download dependencies
        proxy: "http://localhost:3128"
    }
```

I tried to make it clean (from the poor knowledge I have on this code base), please advice for any improvement :-)

**Comment by vvo** [comment]
released
