### ISSUE TITLE
Adding the --silent option for selenium-standalone start

### ISSUE THREAD

**Issue by pxslip** [vvo/selenium-standalone#175]
Since Selenium likes to dump a metric ton of log data, and I can't seem to get it to shut up any other way I was looking at adding the `--silent` option to the `start` command for the CLI. My first thought at doing this was to do change selenium-standalone (around line 43) from 

```
options.spawnOptions = {
    stdio: 'inherit'
};
```

to 

```
options.spawnOptions = options.silent ? {stdio: 'ignore'} : {stdio: 'inherit'};
```

I wanted a second opinion before I sent a PR out of the blue, as this would also alter how the `install` command works. So far when trying this it hasn't caused any issues, but I may be missing something. Also, if I totally missed a way to silence Selenium without this option can someone point me in the right direction as nothing I've tried so far works.

**Comment by vvo** [comment]
can't the output be redirected elsewhere? Otherwise maybe start it as a daemon. Isn't there already options on the selenium end to do that?

**Comment by scotthaley** [comment]
Not sure if this is still an issue, but we just solved this by doing 
`selenium-standalone start 2> selenium.log`

**Comment by kidandcat** [comment]
That doesn't work on windows

**Comment by mgrybyk** [comment]
`selenium-standalone start > selenium.log` works on windows as well
