### ISSUE TITLE
Missing "selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver"

### ISSUE THREAD

**Issue by wzhscript** [vvo/selenium-standalone#177]
after installing selenium-standalone by "npm install selenium-standalone --save"
when I run "selenium-standalone start", I got the error msg bellow:
```
selenium-standalone start

/Users/wzhscript/Documents/Development/tmp/crawler/node_modules/selenium-standalone/bin/selenium-standalone:56
        throw err;
        ^

Error: Missing /Users/wzhscript/Documents/Development/tmp/crawler/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver
    at /Users/wzhscript/Documents/Development/tmp/crawler/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

It seems the ".selenium" directory is missing, is there something wrong?

**Comment by wzhscript** [comment]
After I manually downloaded [2.21-x64-chromedriver](https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux32.zip) and [2.50.1-server.jar](https://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar), it's working now.

**Comment by stephenash** [comment]
Did you also run the `selenium-standalone install` step that is listed in the [README](https://github.com/vvo/selenium-standalone/blob/master/README.md#selenium-standalone---)?

**Comment by wzhscript** [comment]
@stephenash I didn't notic that...
thx，this will be much more easy.

**Comment by Jtech42** [comment]
I did run the install, and now /node_modules/selenium-standalone/.selenium/selenium-server/3.6.0-server.jar is throwing the error. So much time wasted to these things that should be included without redundant installation processes.

**Comment by vvo** [comment]
> So much time wasted to these things that should be included without redundant installation processes.

I agree, I initially created selenium-standalone to simplify things. But in the end that's just a wrapper on top of normal selenium things: http://www.seleniumhq.org/

Try to first install everything manually, and if it works then move on with standalone, if it fails, stays with the manual way. Thanks.
