### ISSUE TITLE
pageLoadStrategy: 'eager' enhancement?

### ISSUE THREAD

**Issue by aaronbriel** [vvo/selenium-standalone#178]
I'm curious if there is an enhancement in the works for implementation of the [pageLoadStrategy](http://webdriver.io/guide/getstarted/configuration.html) desired capability.

**Comment by monolithed** [comment]
`pageLoadStrategy` does not work in Chrome, but does in FF. What do you mean?

**Comment by vvo** [comment]
We are not restricting the usage of any selenium capability.
