### ISSUE TITLE
How could I enable the chrome driver?

### ISSUE THREAD

**Issue by NouranMahmoud** [vvo/selenium-standalone#180]
I used this command to install the chrome driver
`# choose chrome driver version`
`sudo selenium-standalone install --drivers.chrome.version=2.15 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com`

Then I started the server
`selenium-standalone start`

And I use the _cucumber-mink_ which uses _webdriverio_ and I pass this configurations to it.

```
var parameters = {
  driver: {
    desiredCapabilities: {
      browserName: 'chrome'
    },
    logLevel: 'silent'
  }
};
```
I tried this command but it didn't work 
```
# choose ie driver architecture
sudo selenium-standalone start --drivers.chrome.arch=2.15 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com
```
But eventually, when I run the test .. the firefox browser opens and the tests run... is there any missed configurations or should I start the selenium-standalone with custom options??

**Comment by vvo** [comment]
Hi, can you try to use the install command without any parameter and then retry? Thanks

**Comment by NouranMahmoud** [comment]
I executed this command `sudo selenium-standalone install `, but it still opens firefox browser not chrome.

**Comment by vvo** [comment]
Can you create a simple repository demonstrating the issue?

**Comment by NouranMahmoud** [comment]
Thanks so much for your time, the problem was that I was running the tests using `cucumber-mink` but when I ran it with `cucumberjs` directly and required the `mink.js` file .. *the selenium server opened the chrome driver* and everything worked fine  ..

I've created a [simple example here](https://github.com/NouranMahmoud/cucumberMink-example) if any one faced the same issue.

**Comment by vvo** [comment]
Awesome! have fun testing :)
