### ISSUE TITLE
Firefox 48+ will require new Marionette driver

### ISSUE THREAD

**Issue by azakus** [vvo/selenium-standalone#181]
https://github.com/SeleniumHQ/selenium/issues/2110#issuecomment-224413609

It appears Firefox 47 is the last release that works out of the box with Selenium, and future releases will require the [Marionette Driver](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver)

**Comment by vvo** [comment]
What do we need to do?

**Comment by azakus** [comment]
I guess the simplest answer would be to add the Marionette driver to the set of ones downloaded on install like chromedriver and IEdriver.

I can give a shot at a Pull Request.

**Comment by vvo** [comment]
> I can give a shot at a Pull Request.

That would be awesome :pray:. Also if you happen to know if this would be backward compatible or not with previous Firefox users. Otherwise we will bump major.

**Comment by TimvdLippe** [comment]
It seems that this issue has not been fixed yet. I am getting the following error now:

```
"value":{"additionalInformation":
"Driver info: org.openqa.selenium.firefox.MarionetteDriver","localizedMessage":"Missing marionetteProtocol field in handshake (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.45 seconds
Build info: version: '2.53.0'
```

**Comment by azakus** [comment]
Yeah, I'm only getting this on Travis, not on my own machine 😕. I wonder if https://github.com/mozilla/geckodriver/issues/72#issuecomment-224891203 is related.

**Comment by vvo** [comment]
This was not released yet as a new version @TimvdLippe, how did you install selenium-standalone?

**Comment by TimvdLippe** [comment]
@vvo Web-component-tester was using the branch for this issue: https://github.com/Polymer/wct-local/commit/50063065c3db97a357e67a658a1a2d0eb2e974a9

**Comment by rhythnic** [comment]
I'm on 5.1.1 and the "selenium-standalone install" is not logging that it is downloading the marionette driver.

```

selenium install:
from: https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
to: /Users/nbaroni/cablelabs/bsa-test/web-client-user/nightwatch/node_modules/selenium-standalone/.selenium/selenium-server/2.53.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip
to: /Users/nbaroni/cablelabs/bsa-test/web-client-user/nightwatch/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver
---
File from https://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip has already been downloaded
---
File from https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar has already been downloaded
```
Is this expected?  Should I pass any parameters to the command?

**Comment by rhythnic** [comment]
The defaultConfig in the docs is constant with the published defaultConfig (no firefox), but those don't match lib/default-config.js (with firefox).  I should be able to get around my problem by passing in the ff driver.
