### ISSUE TITLE
Running server (selenium-standalone start) takes 2.5 min~

### ISSUE THREAD

**Issue by MikiDavid** [vvo/selenium-standalone#182]
When running the command:
`selenium-standalone start`

It takes the server to launch approximately 2.5 minutes.

Is this make any sens?

**Comment by vvo** [comment]
Not it does not make sense :)

**Comment by MikiDavid** [comment]
Cool,
Is there a way to know why its happens?

**Comment by vvo** [comment]
You will have to clone the repository and add console.log at various stages. Unfortunately I never encountered this and don't have an easy solution for you.

This could be a networking issue like DNS resolution on localhost or smg.. I would also try to run the bare selenium server without using selenium-standalone to see if that's a real issue of us or just selenium in your setup.
