### ISSUE TITLE
Version number not respected.

### ISSUE THREAD

**Issue by DaveStein** [vvo/selenium-standalone#184]
My config during install has this:
```
drivers: {
  chrome: {
    version: '2.20',
    arch: process.arch,
    baseURL: 'https://chromedriver.storage.googleapis.com'
  }
},
```

I get the error `Error: Missing /myfolderstructure/myproject/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver`

Expected: To look for `2.20-x64-chromedriver`, which existed in folder structure.
Actual: Looked for `2.21-x64-chromedriver`
Workaround: Updating to `version: '2.21'`

**Comment by nkbt** [comment]
Same config should be used for `start`

**Comment by vvo** [comment]
Yep
