### ISSUE TITLE
Install and use new chromedriver doesn't work

### ISSUE THREAD

**Issue by patthiel** [vvo/selenium-standalone#185]
* Install command for latest chromedriver `selenium-standalone install --drivers.chrome.version=2.22 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com` successfully downloads latest chromedriver.

* However, following this running `selenium-standalone start` results in `/usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver` not found.. (Assuming you have removed the previous version.)..  I had to manually update `lib/default-config.js` chromedriver version to 2.22 to get around this issue.

*Expected Result*
installing a certain driver should update the default driver used by `selenium-standalone start` to that driver.

**Comment by vvo** [comment]
indeed, install AND start need to tune the drivers settings otherwise it uses the default ones. Can you update the default config to latest drivers? This should solve the issue

**Comment by patthiel** [comment]
Ah, makes sense. Here's the PR with the version bump: https://github.com/vvo/selenium-standalone/pull/188
