### ISSUE TITLE
5.1.1 release on npm doesn't include 5.1.1 changes

### ISSUE THREAD

**Issue by rhythnic** [vvo/selenium-standalone#190]
The npm  package @5.1.1 doesn't sync up with what's in master.  It doesn't include the changes for supporting Marionette.

node_modules/selenium-standalone/bin/selenium-standalone
```
var argv = minimist(process.argv.slice(2), {
    string: ['version', 'drivers.chrome.version', 'drivers.ie.version']
  });
```

https://github.com/vvo/selenium-standalone/blob/master/bin/selenium-standalone
```
var argv = minimist(process.argv.slice(2), {
  string: ['version', 'drivers.chrome.version', 'drivers.ie.version', 'drivers.firefox.version']
});
```

**Comment by vvo** [comment]
Ok fixed by releasing 5.2.0
