### ISSUE TITLE
unable to get local issuer certificate with latest selenium-standalone install

### ISSUE THREAD

**Issue by tapanbasak** [vvo/selenium-standalone#194]
Hi,

I am getting below error when running command >**selenium-standalone install**

**Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win64.zip: Error: unable to get local issuer certificate**        
at Request.<anonymous> (C:\Users\tb97406\AppData\Roaming\npm\node_modules\selenium-standalone\lib\install.js:392:8)
at Request.g (events.js:260:16)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7) 
at Request.onRequestError (C:\Users\tb97406\AppData\Roaming\npm\node_modules\selenium-standalone\node_modules\request\request.js:971:8) 
at emitOne (events.js:77:13)
at ClientRequest.emit (events.js:169:7)
at TLSSocket.socketErrorListener (_http_client.js:259:9)
at emitOne (events.js:77:13)
at TLSSocket.emit (events.js:169:7)

Does anyone can provide some idea how to resolve the above issue?

Thanks

**Comment by mdwragg** [comment]
Likewise, affecting our team too on osx.

**Comment by vvo** [comment]
I have no answer to this, can you try forking, using http and see if it fixes it, or just try to download the file.

**Comment by RandTrawick** [comment]
Having same problem

**Comment by vvo** [comment]
I was not able to reproduce this unfortunately:

![2016-07-12-143857_760x892_scrot](https://cloud.githubusercontent.com/assets/123822/16767227/b89529c4-483e-11e6-8773-d8149a090310.png)

Do you have a proxy at the place the errors occurs?

**Comment by mdwragg** [comment]
Hi, thanks for helping out.

I'm behind a corporate proxy - anything I can run from here to help you diagnose? If I connect directly to the internet things start to work...

That said, things worked happily behind the proxy until very recently. We're seeing this across a range of hardware and installations. All of our installations on Travis/Sauce are working fine too, just our stuff inside firewall/proxy...

Thanks again...
Martin.

**Comment by vvo** [comment]
Yes it's more of an internal proxy issue than anything else. I think there are ways to say "ignore those ssl errors because YOLO", if we can find this flag (maybe in https://github.com/request/request or just by searching the error message + nodejs) then you can find ways to avoid this error

**Comment by mdwragg** [comment]
@vvo - Sweet....

`export NODE_TLS_REJECT_UNAUTHORIZED=0`

This worked. I have no idea, though, if this is going to cause my world to end ;-)

**Comment by vvo** [comment]
![fine](https://cdn.meme.am/instances/500x/69402423.jpg)

**Comment by vvo** [comment]
@mdwragg Could you submit a PR updating the documentation about this?

**Comment by RandTrawick** [comment]
unfortunately, I'm on a windows machine.  
tried set NODE_ENV=NODE_TLS_REJECT_UNAUTHORIZED=0  
did not fix the firewall problem,

**Comment by vvo** [comment]
No you need to set an environement variable on windows: http://ss64.com/nt/syntax-variables.html

**Comment by RandTrawick** [comment]
of course I should have! (asleep at the wheel) 
setx NODE_TLS_REJECT_UNAUTHORIZED 0  
worked!  

Thanks for your help.

**Comment by vvo** [comment]
NIIICE

**Comment by mdwragg** [comment]
💯  #teamwork. Thanks all!

@vvo - PR here: #197

**Comment by kimtuck** [comment]
Sortof worked for me; I had to be sudo to get it to work:

sudo sh
# export NODE_TLS_REJECT_UNAUTHORIZED=0
# npm install --save-dev geckodriver

**Comment by dawidpolakowskics** [comment]
Thank you very much 👍 Windows 10 >> inside Company network.

> sudo sh
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> npm install --save-dev geckodriver
