### ISSUE TITLE
selenium-standalone start -port 5555 doesn't run on port 5555 but runs on port 4444

### ISSUE THREAD

**Issue by navinjoy** [vvo/selenium-standalone#198]
selenium-standalone start -port 5555 doesn't run on port 5555 but runs on port 4444.

**Comment by stephenash** [comment]
Since `-port` is an argument for the selenium process itself (not this wrapper), [it needs to be added after the `--` argument](https://github.com/vvo/selenium-standalone#command-line-interface).

```text
$ ./bin/selenium-standalone start -- -port 5555
09:40:00.550 INFO - Launching a standalone Selenium Server
...
09:40:00.709 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:5555/wd/hub
09:40:00.709 INFO - Selenium Server is up and running
Selenium started
```

@navinjoy Can you give that a try and let me know if it works for you?

**Comment by navinjoy** [comment]
@stephenash thank you... that worked 👍 
and how can I use it in selenium-standalone.start([opts], cb) function. Tried the below one but that's not working.

```
            selenium_standalone.start({port:5555},function(err, child) {
                if (err) {
                    grunt.log.error(err);
                    return;
                }
                process.on("exit", function() {
                    child.kill();
                });
            });
```

**Comment by vvo** [comment]
You need to pass it to seleniumArgs: {port}, see https://github.com/vvo/selenium-standalone#seleniumstartopts-cb
