### ISSUE TITLE
Searching for geckodriver?

### ISSUE THREAD

**Issue by DaveStein** [vvo/selenium-standalone#199]
Everything was working great for me until I recently removed my node modules and ran `npm install` again. A coworker had the same problem. Basically I have this gulp task:

```
gulp.task('selenium_install', function(cb) {
  gutil.log('Checking selenium-standalone installation...');
  selenium.install({
    version: '2.48.2',
    baseURL: 'https://selenium-release.storage.googleapis.com',
    drivers: {
      chrome: {
        version: '2.22',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com'
      }
    },
    progressCb: function(total, progress) {
      gutil.log('progressing');
      var bar = new ProgressBar('selenium-standalone & chromedriver installation [:bar] :percent', {
        total: total,
        complete: '=',
        incomplete: ' ',
        width: 20
      });
      bar.tick(progress);
    }
  }, function(err) {
    if (err) {
      gutil.log(gutil.colors.red(err));
      return cb();
    }

    gutil.log('Installed');
    cb();
  });
});
```

For one, the `progressCb` function is no longer called. The second bigger issue is that I will then get this error when going to run tests:

`Error: Missing /mypathtoproject/node_modules/selenium-standalone/.selenium/geckodriver/0.9.0-x64-geckodriver`

If I simply make the folder, and create a blank file with that name, all my things run perfect. Very confusing. I am using `webdriverio` to actually run the tests, but considering the progress bar part is specifically `selenium-standalone`, and it stopped working, I am thinking it is related to this project rather than the other.

**Comment by vvo** [comment]
Hi @DaveStein thanks for reporting this issue, very valuable. The code of selenium-standalone can be hacked itself so would you mind having a look at what is going on in the code and see where it fails more precisely?

I won't have much time to fix this in the coming days sadly.

**Comment by DaveStein** [comment]
Found it.

```
  if (opts.drivers) {
    // Merge in missing driver options for those specified
    opts.drivers = mapValues(opts.drivers, function(config, name) {
      return merge({}, defaultConfig.drivers[name], config);
    });
  } else {
    opts.drivers = defaultConfig.drivers;
  }

```

I specify drivers, it merges the default options on top of them. Those defaults mean even though I did not request FireFox, it is trying to use firefox. Is that the intent? If so the bug would become that the download path is not working correctly.

`checkPathsExistence(getInstallPaths(fsPaths), function(err) {` throws the error rather than only running on things that exist. Keep in mind if i touch the file to fake its existence, all my tests run because I am not requesting tests run in FF.

**Comment by DaveStein** [comment]
PS: Let me know intended behavior and I can make a PR to fix it, assuming you'd be able to answer PR faster than just fixing it yourself :P Hopefully the above is enough to make it easy

**Comment by vvo** [comment]
> If so the bug would become that the download path is not working correctly.

Yes it seems to be the bug we are looking for, if you can submit a PR, I can merge and release really fast :)

**Comment by vvo** [comment]
Thanks already for having a look deeply! I hope we can fix this now :p

**Comment by DaveStein** [comment]
@vvo so if the download fails should I just make sure that `checkPathsExistence` silently fails? Or should I make it log to console and continue on?

**Comment by vvo** [comment]
I would say the download should not fail here first. That's where we should look at

**Comment by DaveStein** [comment]
@vvo Since we are downloading from the internet, i imagine even if we correct the path now, it can fail in the future. Then this bug will pop up again. Guess I'll make a PR to fix the download itself and then make an issue for better handling later?

**Comment by DaveStein** [comment]
Oh I realized something else actually.

I run `install` with driver options. Then I run `start`.

```
  if (opts.drivers) {
    // Merge in missing driver options for those specified
    opts.drivers = mapValues(opts.drivers, function(config, name) {
      return merge({}, defaultConfig.drivers[name], config);
    });
  } else {
    opts.drivers = defaultConfig.drivers;
  }

  // ONLY shows Chrome so seems merge isn't behaving as expected
  console.log('install', opts.drivers);
```

```
  if (opts.drivers) {
    // Merge in missing driver options for those specified
    opts.drivers = mapValues(opts.drivers, function(config, name) {
      return merge({}, defaultConfig.drivers[name], config);
    });
  } else {
    opts.drivers = defaultConfig.drivers;
  }

// No driver options, so just assumes all default drivers
console.log('start', opts.drivers);
```

**Comment by vvo** [comment]
Yes sounds like a plan!!

**Comment by DaveStein** [comment]
@vvo guess you said that before my second response after realizing the duplicate lines in start and install :D

**Comment by vvo** [comment]
Yes I guess we could do a new major version where there is no merging of options

**Comment by DaveStein** [comment]
@vvo https://github.com/vvo/selenium-standalone/commit/e3cfd25255e8cabdf0a8e0ee89b03085112e57d6 is the breaking commit for me.

I get it completely now.

If I never specify drivers, everything works no problem since it will download all the drivers for `install`. Then when I go to `start`, it has everything.

The problem was me specifying `chrome` on install. `start` was only looking for chrome up until recently, where it now looks for FF as well. So that commit didn't really change anything, except expose an existing hidden issue.

I am thinking `start` should attempt to use all the drivers with no options specified, but silently fail if the driver is not found, instead of erroring. (Keep the error for install only). Then if user specifies drivers on `start`, and it's not found, error.

What do you think?

**Comment by DaveStein** [comment]
Note that in my code I had specified chrome for `install` and never specified any drivers in `start`.

**Comment by vvo** [comment]
Ahah yep if you use options for install then you need to specify options for start. We cannot infer settings from any state.

Otherwise it would require us listing what is installed etc.. Which we don't. I guess we should document how start() works, that should do it?

**Comment by DaveStein** [comment]
@vvo Hm it's funny cause out of the box, it will install a default config the user is really unaware of. Then it will use that default on start. So by dumb luck, before FF, things were working with options for install, and none used for start.

Making the docs say "if you use driver config for install, you must use same (or subset) for start" is one solution.

Making `start` log missing drivers, when the config is not specifying any, might be better. I dunno. Docs are def a start cause I was really confused why it was looking for gecko since I had never specified it anywhere!

**Comment by vvo** [comment]
Both of your solution are very good, I am down for any PR solving it.

**Comment by DaveStein** [comment]
@vvo Actually I realized these solutions are bad as I was writing the PR.

`install` and `start` handle the `drivers` options the same way. They both append missing parts, IF you specify a driver. So IF I specify `chrome`, and am missing something, it will put extra attributes on top.

Everything should take the default config, and apply the user config on top. That way if I specify Chrome, I overwrite the default. Then you can only add to the config, rather than subtract, as it does today.

Does that make more sense?

**Comment by vvo** [comment]
> install and start handle the drivers options the same way. They both append missing parts, IF you specify a driver. So IF I specify chrome, and am missing something, it will put extra attributes on top.

I think this was on purpose, if we do the opposite, how do you avoid downloading some drivers? 

Relevant discussions https://github.com/vvo/selenium-standalone/issues/128 (follow the various commits and threads)

I must say at this point I am lost with my own code and decisions, I am not an heavy user of selenium-standalone as you are maybe

**Comment by DaveStein** [comment]
Hm interesting. I guess I'll think about it a bit more :)

**Comment by ArtRule** [comment]
Hi,
so have you solve the problem?

**Comment by DaveStein** [comment]
Ah yeah. @vvo I was down to two options that would make sense. One would just be the readme update. Another would be to create a config file so you can config the drivers for both bases, although the options in the actual JS would overwrite that completely. What do you think there?

**Comment by maverick09** [comment]
Could you post a working example of config file or readme file ?

**Comment by vvo** [comment]
I am OK taking a pull request that would only start() what is available (installed) by default (and log what are the available drivers), then if you specify a driver we will try to only start that driver.

install() should work like it does today and keep merging. @DaveStein if you are still up for a PR then shoot!

**Comment by gin** [comment]
Any of the 2 solutions would be good. We have the same issue.

**Comment by sshaginyan** [comment]
+1

**Comment by vvo** [comment]
I have no solution nor a clear vision of the underlying bug here, anyone can jump in, submit a PR fixing it. Thanks

**Comment by kirkstrobeck** [comment]
In the meantime, if you are experiencing this issue, here’s an install that should get it working. My use-case is to use Chrome as well, but it wants gecko too, so yah.. gecko. 

```js
selenium.install({
    baseURL: 'https://selenium-release.storage.googleapis.com',
    version: '2.53.1',
    drivers: {
      chrome: {
        version: '2.27',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com',
      },
      firefox: {
        version: '0.11.1',
        arch: process.arch,
        baseURL: 'https://github.com/mozilla/geckodriver/releases/download',
      },
    },
  }, resolve);
```

**Comment by jhuesos** [comment]
This issue might be related to the one I am having with web-component-tester from Polymer, that also installs selenium-standalone in the postinstall and it always hangs while downloading geckodriver?

Reading this post, it seems like the download fails in between and the postinstall process hangs forever

**Comment by fabiodamasceno** [comment]
+1

My network access is restricted and don't need (can't ) to download gecko driver.
What's needed to correct this issue? Can I send a PR?

**Comment by vvo** [comment]
> Can I send a PR?

Yes

> What's needed to correct this issue?

No idea, but digging this can be easier than what you think.. Try it!
