### ISSUE TITLE
firefox driver install fails, incorrect path to geckodriver

### ISSUE THREAD

**Issue by paul-haine** [vvo/selenium-standalone#207]
After `selenium-standalone install`

Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz

Correct URL appears to be https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz

**Comment by Goye** [comment]
Yeah to fix that for now, you can change the line #85 on lib/compute-download-urls.js to `platform = 'macos';`

**Comment by monolithed** [comment]
I think it should be fixed in https://github.com/vvo/selenium-standalone/issues/207

**Comment by qrpike** [comment]
+1

**Comment by gstroup** [comment]
I created a PR #208 with the fix suggested by @Goye

**Comment by stephenash** [comment]
Just changing the `platform` value when we construct the download URL may not be the best way. Especially if someone wants to install `v0.9.0`, then we would run into the reverse problem where `geckodriver-v0.9.0-macos.tar.gz` is not found.

Don't have an immediate solution, but https://github.com/mozilla/geckodriver/issues/193 is open to hopefully get more consistent naming of the releases.

**Comment by ckedwards** [comment]
Currently the default install is broken. Can we at least get a fix so vanilla `selenium-standalone install` isn't broken?  Perhaps getFirefoxDriverArchitecture could have the version passed in and make a decision based off of that information?

**Comment by stephenash** [comment]
I just published `selenium-standalone@5.6.1` that will have the correct url for just the v0.10 driver. Will keep this issue open to track the file name inconsistencies.

**Comment by IceCreamYou** [comment]
FWIW, I need to use geckodriver v0.9.0 for compatibility reasons (it's the only version I can get to work with [nightwatch](https://github.com/nightwatchjs/nightwatch)) so I have to put this super fun hack in my package.json:

```json
"scripts": {
    "fix-geckodriver-version": "if [[ $(node -e \"console.log(process.platform);\") == \"darwin\" ]]; then rm -rf node_modules/selenium-standalone/.selenium/geckodriver/0.10.* && curl -Ls https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-mac.tar.gz | tar -xf - && mv geckodriver node_modules/selenium-standalone/.selenium/geckodriver/0.9.0-x64-geckodriver && echo 'Changed geckodriver version to 0.9.0 for compatibility.'; fi"
}
```

Maybe that atrocity will be useful to others...

**Comment by vvo** [comment]
Legacy fun! We cannot handle every case for very recent projects that move release downloads like geckodriver unfortunately.

**Comment by IceCreamYou** [comment]
Geckodriver 0.9.0 is not legacy. It's a supported version of the driver. It's the latest release that works with Selenium 2 according to the [release notes](https://github.com/mozilla/geckodriver/releases) (the 0.10.0 release notes say "Only upgrade to this version if you are using Selenium 3 beta releases"), and Selenium 2 is still the supported version of Selenium (and the one installed by default by selenium-standalone).

@vvo If I submit a PR to fix this, will you accept it?

**Comment by vvo** [comment]
Yep @IceCreamYou :) submit

**Comment by IceCreamYou** [comment]
Done! #217 😀

**Comment by vvo** [comment]
now released, GG @IceCreamYou
