### ISSUE TITLE
Semver is not respected due to breaking changes in chrome driver

### ISSUE THREAD

**Issue by nkbt** [vvo/selenium-standalone#209]
I've been struggling with this for a while and at last decided to open the case.

This is what I keep getting from time to time on my CI without any code changes.
```sh
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome version must be >= 51.0.2704.0
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 3.13.0-91-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.58 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-91-generic', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
       	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
       	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
       	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
       	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
       	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
       	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
       	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
       	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
       	... 14 more
07:07:05.814 WARN - Exception: unknown error: Chrome version must be >= 51.0.2704.0
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 3.13.0-91-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.58 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-91-generic', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
07:07:05.820 DEBUG - Finished: POST /session
07:07:05.821 DEBUG - Finished: POST /session
```

The problem is that `selenium-standalone` is updated with new chrome driver and published patch version, which is supposed to be fully compatible. It is apparently not.

I do believe that any update of chrome driver that involves new Chrome version dependency should be published as `major` release, since it is breaking change.

I have a workaround - just locking the version in https://github.com/nkbt/nightwatch-autorun/blob/master/package.json and never update unless build is passing on CI, but that does not fix the real problem

Thanks for the package by the way, made my `nightwatch-autorun` possible.

**Comment by nkbt** [comment]
So Semver is broken for chromedriver: https://sites.google.com/a/chromium.org/chromedriver/downloads

ChromeDriver 2.23 drops support fro Chrome <51

It happened before with some other versions, so I had to either manually upgrade chrome in our CI docker images, or opt out from selenium-standalone updates.

Would be nice to address this at last

**Comment by patthiel** [comment]
@nkbt Can you setup your CI environment to always install a specified chromedriver version (that has been vetted by you and your team) with this command: `selenium-standalone install --drivers.chrome.version=2.22 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com`? 

Or is the issue more, if a driver has a breaking change there should be a major release of selenium-standalone (philosophically, is that the responsibility of this project @vvo)? I feel like manually specifying the install version might be an approach that would scale better.

**Comment by vvo** [comment]
Hi to both of you, If chromedriver is not following semver (that is, 2.22 vs 2.23) I cannot easily infer that it will be a breaking change somehow. I would say it's not the responsibility of selenium-standalone, at least I will not do it (watch closely the changes of every driver).

**Comment by nkbt** [comment]
@patthiel thanks a lot, locking chromedriver version should do!

@vvo chromedriver does not seem to have semver versioning at all (x.yy is not semver), I don't think you should release patch version when it updates.

**Comment by nkbt** [comment]
@patthiel unfortunately locking drivers' versions does not work. Because of `arch` that was changed too from release to release of chrome drivers.

Note how mac32 is not published anymore, but mac64 appeared

```xml
<xml>
  <Contents>
    <Key>2.22/chromedriver_linux32.zip</Key>
  </Contents>
  <Contents>
    <Key>2.22/chromedriver_linux64.zip</Key>
  </Contents>
  <Contents>
    <Key>2.22/chromedriver_mac32.zip</Key>
  </Contents>
  <Contents>
    <Key>2.22/chromedriver_win32.zip</Key>
  </Contents>
  <Contents>
    <Key>2.23/chromedriver_linux32.zip</Key>
  </Contents>
  <Contents>
    <Key>2.23/chromedriver_linux64.zip</Key>
  </Contents>
  <Contents>
    <Key>2.23/chromedriver_mac64.zip</Key>
  </Contents>
  <Contents>
    <Key>2.23/chromedriver_win32.zip</Key>
  </Contents>
</xml>
```

From https://chromedriver.storage.googleapis.com/

I could probable hardcode arch, which I tried, but there is another issue: https://github.com/vvo/selenium-standalone/issues/212

So far the only real way for me is to lock down `selenium-standalone` version and never auto-update it (until manually tested and CI support is confirmed)

**Comment by vvo** [comment]
> So far the only real way for me is to lock down selenium-standalone version and never auto-update it (until manually tested and CI support is confirmed)

Yes that is the way to go at least for CI testing, for dev environement that's different maybe
