### ISSUE TITLE
npm package selenium-standalone-2.39.0-2.8.0-2 - url of selenium jar changed

### ISSUE THREAD

**Issue by bs123** [vvo/selenium-standalone#214]
https://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
is not available anymore (404)

considering http://central.maven.org/maven2/org/seleniumhq/selenium/selenium-server/2.39.0/selenium-server-2.39.0.jar
https://selenium-release.storage.googleapis.com/2.39/selenium-server-standalone-2.39.0.jar

cheers

**Comment by vvo** [comment]
@bs123 We already use selenium-release.storage, please upgrade selenium-standalone

**Comment by vvo** [comment]
See https://github.com/vvo/selenium-standalone/blob/1be9c73d762d84f5cadb7f8239f44e97bcbff2df/lib/default-config.js

**Comment by bs123** [comment]
hi, thanks, unfortunately we need to test Opera 12.16, it seams we need chromedriver 2.8 and selenium Jar <=2.40.0

our solution was now 
"selenium-server-standalone-jar": "2.40.0",
 "chromedriver": "2.8.1",
