### ISSUE TITLE
ChromeDriver 2.24 is available

### ISSUE THREAD

**Issue by Goye** [vvo/selenium-standalone#220]
Guys, you have plans to integrate the latest Chromedriver version?

**Comment by arun3528** [comment]
@Goye  Try adding it via command line or the api . Check the readme .

**Comment by Goye** [comment]
it doesn't works because the application tries to find 2.24/chromedriver_mac32.zip but the latest version was changed for 2.24/chromedriver_mac64.zip

**Comment by vvo** [comment]
We recently has a PR that was solving exactly this for gecko, see https://github.com/vvo/selenium-standalone/pull/217

Maybe you could upgrade the default chromedriver here: https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js

And also handle the new max64 thing? Thanks

**Comment by Goye** [comment]
@vvo sure, thanks a lot!

**Comment by stephenash** [comment]
Closed via https://github.com/vvo/selenium-standalone/pull/221
