### ISSUE TITLE
expectedRequests is incorrect when less than 3 opts.drivers is provided

### ISSUE THREAD

**Issue by johnelm** [vvo/selenium-standalone#227]
In install.js, expectedRequests is incorrect when less than 3 opts.drivers is provided via the API.

Prevents the progress bar from ever showing, due to the if statement on line 329:

```javascript
  function updateProgressPercentage(chunk) {
    if (expectedRequests === startedRequests) {
      opts.progressCb(total, progress, chunk);
    }
  }
```

**Comment by stephenash** [comment]
Closed via #229
