### ISSUE TITLE
Specify config file

### ISSUE THREAD

**Issue by kirkstrobeck** [vvo/selenium-standalone#230]
What is the flag to specify the path to config for install?

**Comment by stephenash** [comment]
Are you looking for something like `selenium-standalone install --config=...`? That doesn't exist.

You could use [the API](https://github.com/vvo/selenium-standalone#application-programming-interface-api) instead to do something like

```javascript
var selenium = require('selenium-standalone');
var opts = require('../path/to/my-custom-config.js');

selenium.install(opts, cb);
```

**Comment by jucrouzet** [comment]
The flag is now supported : 
```
selenium-standalone install --config=/path/to/config.json
selenium-standalone start --config=./config/seleniumConfig.js
```
