### ISSUE TITLE
selenium server can not start chrome driver

### ISSUE THREAD

**Issue by joodies** [vvo/selenium-standalone#231]
Hi,

with latest selenium-standalone installed, server can start successfully. But when called by webdriverio, chrome driver can not launch.

09:04:07.848 INFO - Launching a standalone Selenium Server
09:04:07.982 INFO - Java: Oracle Corporation 24.80-b11
09:04:07.983 INFO - OS: Windows 8.1 6.3 amd64
09:04:08.021 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
09:04:08.154 INFO - Driver class not found: com.opera.core.systems.OperaDriver
09:04:08.155 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
09:04:08.175 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform WIN8_1
09:04:08.178 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
09:04:08.179 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
09:04:08.483 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
09:04:08.483 INFO - Selenium Server is up and running
Selenium started
09:04:37.434 INFO - Executing: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@76b2b928, javascriptEnabled=true, browserName=chrome, han
dlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]])
09:04:37.456 INFO - Creating a new session for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@76b2b928, javascriptEnabled=true, browserName=chrome, h
andlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]
09:04:58.090 ERROR - org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "J:\webdriverio\node_m
odules\selenium-standalone\.selenium\chromedriver\2.24-x64-chromedriver" (in directory "."): CreateProcess error=5, Access is denied)

**Comment by vvo** [comment]
somehow it cannot find chromedrive, no idea sorry

**Comment by joodies** [comment]
guess sth to do with win 10? the driver is definitely there.:)

**Comment by vvo** [comment]
Access is denied may mean that we need to set some specific rules on the file. Did you find something on the internet/stackoverflow?

**Comment by jucrouzet** [comment]
`Caused by java.io.IOException: Cannot run program "J:\webdriverio\node_m
odules\selenium-standalone.selenium\chromedriver\2.24-x64-chromedriver" (in directory "."): CreateProcess error=5, Access is denied)`

Looking closely, Java is trying to execute the directory `J:\webdriverio\node_m
odules\selenium-standalone.selenium\chromedriver\2.24-x64-chromedriver` 

That's what causing the Error 5.

Would you post your `wdio.conf.js` (the `capabilities` property) or the JS Code calling Webdriver.io ?

**Comment by joodies** [comment]
:( turns out to because of the virus-scan software, deleting the driver. The driver was taken as a virus..

**Comment by subhanimc1** [comment]
org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "

**Comment by serbanghita** [comment]
@subhanimc1 are you sure you're running selenium standalone? it looks like this is related to Apache
