### ISSUE TITLE
how to start selenium-standalone in background?

### ISSUE THREAD

**Issue by junguchina** [vvo/selenium-standalone#232]
Hi guys,
I use selenium-standalone to start selenium server, but there is problem I found.
I need to keep the terminal opening after run the below command
```
selenium-standalone start
```
Is anyway to start selenium-standalone in background？So that it need not keep the terminal opening all the time.
Please provide some solutions,thanks.

**Comment by jucrouzet** [comment]
Isn't a `selenium-standalone start > /dev/null 2>&1 &` ok ?

**Comment by vvo** [comment]
Hi @junguchina this is a generic unix question, see google: https://www.google.fr/search?q=run+program+in+background

**Comment by junguchina** [comment]
@ruddhani yeah, thank you.
And I use docker-selenium instead.
