### ISSUE TITLE
Running headlessly on Mac

### ISSUE THREAD

**Issue by vaskort** [vvo/selenium-standalone#233]
Hello,

is there a way to run headlessly on a Mac as it is on Linux? 

Thank you :)

**Comment by jucrouzet** [comment]
This is a general selenium question, you can find informations on [StackOverflow](http://stackoverflow.com/questions/22712347/how-to-run-selenium-tests-in-headless-mode-on-mac-using-webdriver-with-firefox-1).

**Comment by vvo** [comment]
Thanks!
