### ISSUE TITLE
latest version on npm is 5.6.1

### ISSUE THREAD

**Issue by TheYaMeZ** [vvo/selenium-standalone#235]
Sorry if this is a silly question, but why are no versions after 5.6.1 visible from npm?

**Comment by jucrouzet** [comment]
Latest version available is 5.7.2 : 

```
$ npm view selenium-standalone versions
 
[ '2.35.0-2.6.1',
  '2.35.0-patch',
  '2.35.0',
  '2.37.0-2.6',
  '2.37.0-2.7.0',
  [...]
  '5.6.0',
  '5.6.1',
  '5.6.2',
  '5.6.3',
  '5.6.4',
  '5.7.0',
  '5.7.1',
  '5.7.2' ]
$ npm view selenium-standalone version
5.7.2
```

**Comment by vvo** [comment]
@jucrouzet Thanks for taking care of all those issues, do not hesitate to close also it's ok here I guess.

**Comment by TheYaMeZ** [comment]
I'm not sure what i'm doing wrong here. For me none of the new versions are available.

C:\dev\apitest>npm view selenium-standalone versions

[ '2.35.0-2.6.1',
  '2.35.0-patch',
  '2.35.0',
  '2.37.0-2.6',
  '2.37.0-2.7.0',
  '2.37.0',
  '2.38.0-2.7.0',
  '2.39.0-2.7.0',
  '2.39.0-2.8.0',
  '2.39.0-2.8.0-1',
  '2.39.0-2.8.0-2',
  '2.39.0-2.9.0',
  '2.40.0-2.9.0',
  '2.40.0-2.9.0-1',
  '2.41.0-2.9.0',
  '2.41.0-2.9.0-1',
  '2.42.0-2.9.0',
  '2.42.0-2.9.0-1',
  '2.42.2-2.9.0',
  '2.42.2-2.9.0-1',
  '2.42.2-2.9.0-2',
  '2.43.1-2.9.0',
  '2.43.1-2.9.0-1',
  '2.43.1-3',
  '2.43.1-4',
  '2.43.1-5',
  '2.44.0-1',
  '2.44.0-3',
  '2.44.0-4',
  '2.44.0-5',
  '2.44.0-6',
  '2.44.0-7',
  '2.44.0',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.1.0',
  '3.1.2',
  '3.2.0',
  '3.3.0',
  '4.1.0',
  '4.2.0',
  '4.2.1',
  '4.2.2',
  '4.4.0',
  '4.4.2',
  '4.4.3',
  '4.5.3',
  '4.6.0',
  '4.6.1',
  '4.6.2',
  '4.6.3',
  '4.7.0',
  '4.7.1',
  '4.7.2',
  '4.8.0',
  '4.9.0',
  '4.9.1',
  '5.0.0',
  '5.1.0',
  '5.1.1',
  '5.2.0',
  '5.3.0',
  '5.3.1',
  '5.4.0',
  '5.4.1',
  '5.5.0',
  '5.6.0',
  '5.6.1' ]

**Comment by jucrouzet** [comment]
Can you copy the output of `npm config ls -a` ?

**Comment by vvo** [comment]
@TheYaMeZ You might be using a different npm registry

**Comment by jucrouzet** [comment]
@vvo Yup, that's what I was suspecting in npm config ls output (eg an outdated cache in a local sinopia)

**Comment by TheYaMeZ** [comment]
Thanks for your help guys, my environment has a custom registry that hasn't been updated in a long time apparently.
