### ISSUE TITLE
Firefox/Geckodriver issues

### ISSUE THREAD

**Issue by matteoantoci** [vvo/selenium-standalone#237]
Hi all!
I actually have two problems with firefox and geckodriver. I'm using webdriver.io as test suite, I can provide you my config, though, it's pretty much what's generated by their tool.

The first problem regards the geckdriver download, I'm using these options for the `install` command:
```javascript
{
    version: '3.0.1',
    firefox: {
      version: '0.11.1',
      arch: process.arch,
      baseURL: 'https://github.com/mozilla/geckodriver/releases/download'
    },
    logger: (message) => console.log(message)
  }
```

but this is what I log while the suite runs:

```bash
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
to: /Users/mantoci/Workspace/obe-ui/node_modules/selenium-standalone/.selenium/selenium-server/3.0.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac64.zip
to: /Users/mantoci/Workspace/obe-ui/node_modules/selenium-standalone/.selenium/chromedriver/2.24-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz
to: /Users/mantoci/Workspace/obe-ui/node_modules/selenium-standalone/.selenium/geckodriver/0.10.0-x64-geckodriver
```

Anyone can help on this?

---

The other issue I'm encountering is with firefox, the tests start, firefox opens but then it won't navigate to the desired page nor execute any assertion. Chrome and phantomjs is fine.

I actually don't know if these problems are related to selenium, geckodriver or webdriver.io but I start asking here.

Any help is really appreciated, thanks!

**Comment by jucrouzet** [comment]
Firefox >= 47 [will not work](http://www.theautomatedtester.co.uk/blog/2016/selenium-webdriver-and-firefox-47.html) with selenium, you must now use the Marionette protocol/driver (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette).

Just add the property `marionette: true` to your `wdio.conf.js`
