### ISSUE TITLE
Unit tests for new --config option

### ISSUE THREAD

**Issue by stephenash** [vvo/selenium-standalone#238]
I [had requested](https://github.com/vvo/selenium-standalone/pull/236#pullrequestreview-5308663) new unit tests for your work with the new `--config` option. The PR got merged in before that was done.

@jucrouzet, can you take a look at adding those so that we don't accidentally break your changes in the future? It looks like you might have to extract the config parsing code into a separate module in order to make it testable in isolation.

Thanks!

**Comment by vvo** [comment]
Sorry I was too quick to check that, just reverted the commit for now so that we can start over. Sorry about it
