### ISSUE TITLE
looking for a wrong version of chromedriver 

### ISSUE THREAD

**Issue by camgimenez** [vvo/selenium-standalone#244]
Hi! 

I'm trying to use selenium-standalone version:2.53.1 and chromedriver version:2.25:
```   
  "scripts": {
"selenium": "selenium-standalone install --version=2.53.1 --baseURL=https://selenium-release.storage.googleapis.com --drivers.chrome.version=2.25 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com && selenium-standalone start" 
(..)
}
  "dependencies": {
 "selenium-standalone": "^5.1.1",
(...)
}
```
Installation is doing correctly:
```
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
to: /home/ubuntu/myproject/node_modules/selenium-standalone/.selenium/selenium-server/2.53.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
to: /home/ubuntu/myproject/node_modules/selenium-standalone/.selenium/chromedriver/2.25-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz
to: /home/ubuntu/myproject/node_modules/selenium-standalone/.selenium/geckodriver/0.9.0-x64-geckodriver




-----
selenium-standalone installation finished
```
But while selenium starting, I'm having the following issue, apparently its looking for a version of chromedriver that I'm not installing:
```
/home/ubuntu/myproject/node_modules/selenium-standalone/bin/selenium-standalone:61
        throw err;
        ^

Error: Missing /home/ubuntu/orchard-mile-spec/node_modules/selenium-standalone/.selenium/chromedriver/2.22-x64-chromedriver
    at /home/ubuntu/myproject/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19) 
```
More info about versions that Im using:
``` 
os: Ubuntu 12.04
chrome version: 54.0.2
node version: 4.4.4 
```
Any idea of what could possible be happening here?

**Comment by stephenash** [comment]
When the `selenium-standalone install` step is invoked, all the parameters that you have set are overrides to the default's (found in selenium-standalone/lib/default-config.js). The `selenium-standalone start` step is a totally separate process that doesn't know about those previous parameters, so it thinks it should be using chromedriver@2.22 instead.

Can you try also defining the driver version parameters for the `start` process and see if that fixes the issue?

```shell
selenium-standalone install --version=2.53.1 --drivers.chrome.version=2.25 ... \
   && selenium-standalone start --drivers.chrome.version=2.25
```

**Comment by mknet** [comment]
Hi everybody,

I got a similar issue. I'm on a Mac and try to download the latest driver by defining the version and the architecture, since it looks for mac32 per default:

`selenium-standalone install --drivers.chrome.version=2.25 --drivers.chrome.arch=mac64`

But still it tries to download the mac32 one which does not exist:

`Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.25/chromedriver_mac32.zip: `

I'm not sure if I should put it in here since you're talking about an issue on Ubuntu. But at least it fits to the title. :)

**Comment by NEWeber** [comment]
I'm seeing the same issue as @camgimenez, (I'm running selenium-standalone 5.8.0, though). In my case, it's looking for the `2.19` chrome driver (the old version I used, I'm trying to upgrade). 

I'm using `2.25` as well. I'm already employing the methods that you suggested @stephenash, and still seeing the same errors.

I've checked the default file in selenium-standalone/lib/default-config.js and it's set to look for `2.25`.

Any ideas?

**Comment by naomiaro** [comment]
`selenium.install({
    version: '3.3.1',
    drivers: {
      chrome: {
        version: '2.28'
      }
    }
  }`

Currently I'm trying a config like this, but I always get the defaults of 3.0.1 and 2.27. Are these config options just ignored?

**Comment by shaikatz** [comment]
Getting the same issue, installed latest selenium-standalone and after starting it searching for old chrome driver version. any news about that?

**Comment by naomiaro** [comment]
@shaikatz I managed to make it work, but I had to pass the config to both selenium.install and selenium.start

`var seleniumConfig = {
  version: '3.4.0',
  drivers: {
    chrome: {
      version: '2.29'
    }
  }
};

gulp.task('selenium', function (done) {
  selenium.install(seleniumConfig, function (err) {
    if (err) {
      return done(err);
    }

    selenium.start(seleniumConfig, function (err, child) {
      if (err) {
        return done(err);
      }

      child.stderr.on('data', function(data){
        console.log(data.toString());
      });

      done();
    });
  });
});`
