### ISSUE TITLE
Update default selenium server version to 3

### ISSUE THREAD

**Issue by vitalets** [vvo/selenium-standalone#246]
It seems already released 3.0.1, may be it's time to put it in defaults?
http://docs.seleniumhq.org/download/

**Comment by vvo** [comment]
@vitalets I am fine doing so if we publish a new major version and if you can maybe find/prove that selenium 3.0.1 is stable enough?

**Comment by vitalets** [comment]
@vvo if there is possibility to broke someone's setup of course we should not hurry. 
I just see that on selenium site it marked as stable release, and also webdriverio docs are [suggesting to use 3.0.1](http://webdriver.io/guide/getstarted/install.html)
I think it makes sense to release it as major version of selenium-standalone so most of users will approve this update manually.

**Comment by vvo** [comment]
Ok then let's do this, can you submit a PR where you test a bit that it's actually working (some parameters we pass might have changed behavior, I really don't know).

**Comment by vitalets** [comment]
I actually use 
```
selenium-standalone install --version=3.0.1
```
in my project. Will live with it some time.

**Comment by jonyet** [comment]
@vitalets are you not having problems locally with this? i use the seleniumArgs and seleniumInstallArgs with a custom options object in order to get the selenium version i want and i cannot get firefox tests to work at all. i have to pass my tests to browserstack in order for them to succeed, so im curious what your exp as been

**Comment by vitalets** [comment]
@jonyet I also had this issue - firefox hanging locally.
I solved it with setting selenium-server 3.0.1 and geckodriver 0.11.1.
To get latest geckodriver try re-install latest selenium-stanalone 5.9 (see https://github.com/vvo/selenium-standalone/issues/247)

**Comment by jonyet** [comment]
@vitalets found my problem - i was already using geckodriver 0.11.1 - as it turns out i had updated JRE to 1.8 when i thought i'd done the entire JDK. after that i confirmed that installing selenium-standalone with that version _and_ set the default config to aim for 3.0.1, it worked just fine.

**Comment by monolithed** [comment]
So, let's do it ))

**Comment by vitalets** [comment]
🎉
