### ISSUE TITLE
Publish to npm 5.8.1 with geckodriver v0.11.1

### ISSUE THREAD

**Issue by vitalets** [vvo/selenium-standalone#247]
Geckodriver version was changed a month ago here: https://github.com/vvo/selenium-standalone/commit/2da38157b46efb3338f543ab539ea6457a718799

but still not published to npm.

**Comment by vvo** [comment]
Sure, doing

**Comment by vvo** [comment]
5.9.0

**Comment by vitalets** [comment]
Thanks! 👍
