### ISSUE TITLE
platform is set to 'win64' if process.platform === 'win32' while downloading geckodriver

### ISSUE THREAD

**Issue by LingSpb** [vvo/selenium-standalone#250]
Could anyone explain the piece of code in https://github.com/vvo/selenium-standalone/blob/master/lib/compute-download-urls.js#L159

> } else if(process.platform === 'win32') {
>     platform = 'win64';
>     type = '.zip';
>   }

why do we set platform = 'win64' if process.platform === 'win32'?

**Comment by jucrouzet** [comment]
When this code was introduced (July), Marionette was not released for win 32.
Since [0.11](https://github.com/mozilla/geckodriver/releases), the win32 target seems to be back, we should update this condition for >=0.90 && < 0.11

@vvo : I propose to do the update tonight (and the Unit tests also)
