### ISSUE TITLE
browser.element method error: TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by lancedolan** [vvo/selenium-standalone#264]
I am finding many selector queries that fail while testing in chrome that do not fail in phantomjs. In each of these cases, the cause is using the element() method, and often a solution is to use a different method.

For example:

`browser.element('.redirect-from input').setValue('NEW VALUE HERE');`

This will return 

```
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:190:34)
    at Object.setValue (/Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:467:23)
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at /Users/lancedolan/edlio/cms/node_modules/webdriverio/build/lib/commands/debug.js:54:43
    at /Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:321:29
```

However it will work if I refactor to 

`browser.setValue( '.redirect-from input' , 'NEW VALUE HERE' );`

I have demonstrated this problem in dozens of test cases with dozens of selectors - the problem is not that my selector is bad, and that's especially clear when the same selector succeeds in other functions like setValue( selector , value ) or click( selector ). 

I'm using the latest version on selenium-standalone, which uses the 2.27 version of chrome driver for mac (I'm on mac sierra).

**Comment by vvo** [comment]
Hi @lancedolan, this seems to be a generic webdriver.io/selenium issue rather than an issue with selenium-standalone itself.

You will have better luck asking on stackOverflow or webdriver.io: https://github.com/webdriverio/webdriverio/issues

**Comment by lancedolan** [comment]
Ah! Sorry!
