### ISSUE TITLE
AWS outages kills selenium-standalone

### ISSUE THREAD

**Issue by ckedwards** [vvo/selenium-standalone#265]
AWS is down and now I can't run my integration tests even if I have the drivers already downloaded. This is because of the header checksum `isUpToDate` call. This kind of begs the question: why is selenium-standalone making calls to the outside world to check if it's local contents are up to date? This doesn't seem I deal to me as it lends itself to a certain amount of unnecessary fragility in my opinion. Is there a reason why this call needs to be made?

```
Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-macos.tar.gz: Error: read ECONNRESET
```

**Comment by vvo** [comment]
@ckedwards AWS is up again so you should be fine, this event is too rare to do any action I guess.

> even if I have the drivers already downloaded.

If you have a way to know that the drivers are already downloaded, you should not have to call install but just start (https://github.com/vvo/selenium-standalone#command-line-interface).

Then in the install step, why do we call upToDate: I have no more idea :D

**Comment by patthiel** [comment]
Perhaps we can have an option to install drivers from a local source containing zip files of the drivers specified? Sort of a paranoid option, but for those of us that rely on CI that regularly pull these down drivers, this might be a good option.

**Comment by vvo** [comment]
@patthiel If this issue is a real pain for you then yes dig it further and maybe find why we are calling isUpToDate while drivers are installed already
