### ISSUE TITLE
not updating chromedriver version through config

### ISSUE THREAD

**Issue by sshaar08** [vvo/selenium-standalone#266]
services: ['selenium-standalone'],
seleniumLogs: './',
seleniumArgs: {
platform: 'MAC',
},
seleniumInstallArgs: {
chrome: {
version: '2.28',
arch: process.arch,
baseURL: 'https://chromedriver.storage.googleapis.com'
},

    version: '3.3.0',
},

**Comment by yaniswang** [comment]
https://github.com/vvo/selenium-standalone/pull/269

**Comment by stephenash** [comment]
@sshaar08 Sorry that you are having problems installing the chromedriver that you need.

Can you share more about how you are executing this code? The syntax of the object in your comment does not match anything that `selenium-standalone` understands natively. Are you using a different tool that interacts with `selenium-standalone`?

Are you able to share some output logs of what is happening during the install to help us narrow down where the problem might be?

**Comment by TheMetalCode** [comment]
@stephenash I might be having the same issue as @sshaar08, and am using `wdio-selenium-standalone-service` to interact with `selenium-standalone`. I guess one basic question comes to mind: is it possible to specify desired chromedriver version in one's webdriverio config file in a fashion that `selenium-standalone` will properly consume? If so, how would that be done?

I am able to specify desired selenium webdriver version in my webdriverio configs like this:

```javascript
services: ['selenium-standalone'],
  seleniumArgs: {
    version: '3.3.1'
  },
  seleniumInstallArgs: {
    version: '3.3.1'
  },
```

**Comment by sshaar08** [comment]
i had to do this:

seleniumArgs: {
        platform: 'MAC',
        drivers:{
            chrome: {
                version: '2.28',
            }
        },
    },
    seleniumInstallArgs: {
        chrome: {
            version: '2.28',
            arch: process.arch,
            baseURL: 'https://chromedriver.storage.googleapis.com'
        },
    },

**Comment by TheMetalCode** [comment]
I found that I needed to do this, slightly different than above. It seems that the `drivers` node needs to be included in both places, not just `seleniumArgs`.

```javascript
  seleniumArgs: {
    version: '3.3.1',
    drivers: {
      chrome: {
        version: '2.29'
      },
      firefox: {
        version: '0.15.0'
      }
    }
  },
  seleniumInstallArgs: {
    version: '3.3.1',
    drivers: {
      chrome: {
        version: '2.29'
      },
      firefox: {
        version: '0.15.0'
      }
    }
  },
```

Still, very helpful @sshaar08, thank you!
