### ISSUE TITLE
update default-config.js chromedriver to 2.28 `enhancement`

### ISSUE THREAD

**Issue by sfaxino** [vvo/selenium-standalone#268]
Please upgrade `chromedriver` to version `2.28` on the `default-config.js`, I'm getting too many errors since I upgraded to chrome v57. Thank you !

**Comment by yaniswang** [comment]
Agree, i getting errors too.

**Comment by yaniswang** [comment]
https://github.com/vvo/selenium-standalone/pull/269

**Comment by stephenash** [comment]
`selenium-standalone@6.1.0` now defaults to using `chromedriver@2.28`.

If you run into troubles like this in the future, you can always tell selenium-standalone to use a specific version of a driver:

```shell
selenium-standalone install --drivers.chrome.version=2.28
selenium-standalone start --drivers.chrome.version=2.28
```
