### ISSUE TITLE
seleniumArgs from configuration file is ignored

### ISSUE THREAD

**Issue by tonatiuhromero** [vvo/selenium-standalone#275]
## Expected Behavior
If I add seleniumArgs in a configuration file it should be used if no command line arguments were provided.

i.e.
seleniumArgs: [ '-role', 'hub', '-port', '4446' ],

## Current Behavior

It seems currently only the command line arguments are use and not from the configuration file.
 I think the problem is in this part of selenium-standalone.js :
-----
 
var seleniumArgs = argv._.slice(1);
....  
// Merge default options, options from config file then command line options
  options = merge({}, defaultConfig, configFromFile, options);

  options.seleniumArgs = seleniumArgs;
  options.spawnOptions = {
    stdio: 'inherit'
  };

**Comment by jucrouzet** [comment]
Yep, the `options.seleniumArgs = seleniumArgs` overwrite the configuration value.
Just did a PR, waiting for a peer review, it should be fixed in next version.

**Comment by jucrouzet** [comment]
Fixed in 6.4.1
