### ISSUE TITLE
How to create a headless

### ISSUE THREAD

**Issue by marvoh** [vvo/selenium-standalone#279]
Is there a way to have a  headless start on Ubuntu boot? I've struggled with this for a while, the service doesn't seem to detect xvfb is both are started on boot

**Comment by vvo** [comment]
Hi @marvoh there are many issues opened on how to run this headlessly: https://github.com/vvo/selenium-standalone/search?q=headless&type=Issues&utf8=%E2%9C%93

Also this is not an issue of selenium-standalone per se, more of an issue on how to configure browsers, with selenium, to be headless.

good luck though, use stackoverflow too

**Comment by marvoh** [comment]
I think you prematurely closed this before understanding my problem. I have already checked the issue and googled extensively including asking on stackoverflow where I didn't get help.

I asked this question before I started using your software [here](http://stackoverflow.com/questions/43394067/selenium-as-a-service-on-ubuntu-14-04) and was hoping I would be able to configure yours to work but I have ended up with the same problem whereby selenium-standalone does not detect the xvfb service already running

**Comment by vvo** [comment]
Hi @marvoh,

> I think you prematurely closed this before understanding my problem.

Sorry if that's the case. Thanks for getting back here.

It seems that even without using selenium-standalone (the npm package) but just using the official jar or selenium-standalone (not this current github package so) you were not able to get selenium running in headless mode.

I would first try to get selenium (the official software) running in headless mode and then get back here to see how the npm package (selenium-standalone) could be used to be in headless.

Ultimately the npm package I author is just a simple wrapper on top of the official selenium software. Nothing different is run but selenium-standalone.jar.

There are many ways to get running selenium in headless mode, one of them being with docker: https://github.com/elgalu/docker-selenium

This repository: https://github.com/elgalu/docker-selenium has great explanation on how to run docker with selenium + chrome inside that should help you a lot.

What you ultimately want to do is force the browsers to detect XVFB or launch them in docker so they do not show up.

Good luck.
