### ISSUE TITLE
Java process is open after Address already in use error

### ISSUE THREAD

**Issue by z-vr** [vvo/selenium-standalone#283]
## Expected Behavior
After trying to start a Selenium standalone server on a taken port programmatically with `selenium.start`, the callback should be called with an error and java not running.

## Current Behavior
The process is still open after `Address already in use` error. However, it could be Java error because when spawning a command directly, java does not quit. It might be worth checking stdout for `Address already in use` message.

**Comment by mgrybyk** [comment]
Please try the latest version.

Feel free to re-open if the issue persists.

Thanks!
