### ISSUE TITLE
Use with safari ?

### ISSUE THREAD

**Issue by akrueger** [vvo/selenium-standalone#289]
Just wondering if this works with Safari?

I didn't see any safari driver download on install, so I am unsure if it's possible to use or not.

Thanks

**Comment by vvo** [comment]
I think safari works by default because it embed the driver, searching safari + selenium on google, first result is: https://github.com/SeleniumHQ/selenium/wiki/SafariDriver

**Comment by vvo** [comment]
Thanks!

**Comment by akrueger** [comment]
The instructions at `SeleniumHQ` worked for me. Just make sure to go to version `2.48` and you'll find the SafariDriver that you can install in Safari as an extension.

Thanks
