### ISSUE TITLE
6.6.0 broke headless chrome

### ISSUE THREAD

**Issue by mg80** [vvo/selenium-standalone#293]
## Expected Behavior
Headless chrome should launch

## Current Behavior
Chrome never launches, process never starts on CentOS.  It seems to work fine on OSX.

## Steps to Reproduce
start chrome with the following args --headless --disable-gpu on CentOS.

**Comment by vvo** [comment]
Do you think this is linked to a chrome bug rather than selenium standalone bug? You can also specify your own versions, see the readme https://github.com/vvo/selenium-standalone

Thanks let me know

**Comment by mg80** [comment]
@vvo based on the changes, it must be an issue with the chrome driver.  I'll close this
