### ISSUE TITLE
How to start selenium on port other than 4444 using selenium-standalone api

### ISSUE THREAD

**Issue by kunal-mazumdar** [vvo/selenium-standalone#294]
## Expected Behavior
Argument "-port 4545" is allowed to start the server on port other than 4444 using java command line and selenium-standalone api should have the ability to do that. How to configure?

## Current Behavior
Inputs tried in config json for selenium.start() api
seleniumArgs : ['-port=5555']
seleniumArgs : ['-port 5555']
javaArgs : ['-port=5555']
javaArgs : ['-port 5555']

complete config
```
{
    spawnOptions: {
        detached: true,
        stdio: 'ignore'
    },
    drivers : drivers,
    seleniumArgs : ['-port=5555']
}
```

Exception
```
Another Selenium process may already be running or your java version may be out of date.
Be sure to check the official Selenium release notes for minimum required java version: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG


    at ChildProcess.errorIfNeverStarted (D:\Officials\Workspaces\workspace-node\smartbotapp\node_modules\selenium-standalone\lib\start.js:158)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:191)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215)
```

## Environment
selenium-standalone": "^6.5.0
selenium-webdriver": "^3.4.0
NodeJS v6.10.1
Java Version "1.8.0_102
OS Windows

**Comment by stephenash** [comment]
Try using `seleniumArgs: ['-port', '5555']` and let me know if that works for you.

**Comment by kunal-mazumdar** [comment]
Oh Yes! It works !! Thanks.
Please close the issue.

**Comment by PrashantBhatasana** [comment]
You can use this command

`java -jar selenium-server-standalone-2.44.0.jar -role hub -port 4545`

**Comment by omprasad123** [comment]
thanks

**Comment by drekhate** [comment]
thnks
