### ISSUE TITLE
geckodriver-v0.18.0-win64.zip not found

### ISSUE THREAD

**Issue by bingxueDU** [vvo/selenium-standalone#303]
selenium-standalone installation [=================   ] 87% 8.8sC:\Users\b\AppDa
ta\Roaming\npm\node_modules\selenium-standalone\bin\selenium-standalone:111
        throw err;
        ^

Error: Could not download https://github.com/mozilla/geckodriver/releases/downlo
ad/v0.18.0/geckodriver-v0.18.0-win64.zip: Error: read ECONNRESET

**Comment by stephenash** [comment]
@bingxueDU Are you routinely hitting this error? `ECONNRESET` errors happen when the remote server (GitHub in this case) closes the TCP connection abruptly.

I am able to download that same URL on my local machine, so wondering if this is a transient network issue for you or not.

**Comment by mgrybyk** [comment]
Please try the latest version.

Thanks!
