### ISSUE TITLE
install should timeout after x seconds

### ISSUE THREAD

**Issue by donaldpipowitch** [vvo/selenium-standalone#304]
## Expected Behavior

I'm currently on a train and try to debug a selenium test. I run `install`, but because of some connection problem the `install` will run forever. It would be nice to have a default timeout (maybe after 10 seconds?), so a real error is thrown. It took me a while to figure out that the `install` runs forever and not some other part of my test.

## Current Behavior

Currently `install` runs forever on a (flaky?) connection.

## Steps to Reproduce

Hard to reproduce. But I can try ;)

- Visit Germany. 🍺 
- Go on a train trip from Munich to Leipzig. 🚋 
- Train should be an ICE. 🚅 
- Log into `WIFIonICE` to get free internet. 📶 
- (Oh, I'm also on corporate VPN for some extra fun. 💃 )
- Run `install`. 🎉 

😄

**Comment by stephenash** [comment]
Those steps to repro are going to take me awhile to finish! Going to add the `pr welcome` label in the meantime.

**Comment by donaldpipowitch** [comment]
😄
