### ISSUE TITLE
Proxy options not working

### ISSUE THREAD

**Issue by Shtirlits** [vvo/selenium-standalone#31]
Greetings!

I'm trying to run selenium-standalone with proxy options as arguments. I tried this:
`start-selenium -Dhttp.proxyHost=107.17.100.254 -Dhttp.proxyPort=8080`
and programmatic way:
```coffeescript
selenium = require 'selenium-standalone'
spawnOptions = stdio: 'pipe'
seleniumArgs = [
  '-debug'
  'PATH="path_to_phantomjs/bin:$PATH"'
  '-Dhttp.proxyHost=107.17.100.254'
  '-Dhttp.proxyPort=8080'
]
server = selenium(spawnOptions, seleniumArgs)
server.stdout.on 'data', (output) ->
  console.log(output)
```

Proxy was taken from http://proxylist.hidemyass.com/#proxy-search-form

How I tested my ip address:
```coffeescript
webdriverio = require 'webdriverio'

options =
  desiredCapabilities:
    browserName: 'phantomjs'

webdriverio
  .remote(options)
  .init()
  .url('http://myhttp.info/')
  .getText 'h1', (err, res) ->
    console.log res
  .end()
```

In both cases I received my real ip address (if I use proxy with authentication - it still doesn't work). At the same time, if I use that proxy in https://github.com/mikeal/request or phantomjs/phridge setup - my real IP is hidden, as expected.
Can you please tell how can I use proxy with selenium-standalone?

Thanks in advance.

UPD: Also, I've noticed, that specifying the path to phantomjs via '-Dphantomjs.binary.path' does not work either, so may be the problem is not in proxy options.

**Comment by sean-hill** [comment]
Did anyone ever solve this? I'm having the same issue where my local IP is not being proxied even then I passed the proxy arguments via `seleniumArgs`. Could the Chrome Driver just be ignoring the arguments and using the machine's IP?

**Comment by vvo** [comment]
Maybe go to the selenium issues to see if there's some matching bug
