### ISSUE TITLE
selenium-standalone: command not found

### ISSUE THREAD

**Issue by vvbhandare** [vvo/selenium-standalone#323]
I am getting below error on entering this command `selenium-standalone install`

> selenium-standalone: command not found

**Comment by vvo** [comment]
Did you do npm install -g selenium-standalone?

**Comment by vvbhandare** [comment]
Yes after doing it, I get below snippet

```
/home/vikas/.npm-global/bin/start-selenium -> /home/vikas/.npm-global/lib/node_modules/selenium-standalone/bin/start-selenium
/home/vikas/.npm-global/bin/selenium-standalone -> /home/vikas/.npm-global/lib/node_modules/selenium-standalone/bin/selenium-standalone
/home/vikas/.npm-global/lib
`-- selenium-standalone@6.11.0 
```

**Comment by vvo** [comment]
when this is done, just open a new tab and do 

```
selenium-standalone install
selenium-standalone start
```

If that does not work, try with another global package like `npm install ava -g` and `ava`. If this fails then your setup about binaries in npm packages is broken and you might want to ask the question on stackoverflow
