### ISSUE TITLE
Chromedriver fails with "CreatePlatformSocket() returned an error" on Linux platform  

### ISSUE THREAD

**Issue by PreeG** [vvo/selenium-standalone#326]
## Expected Behavior
on the test trigger, chromedriver should successfully start. 

## Current Behavior
Chromedriver fails with "CreatePlatformSocket() returned an error" on Linux platform. Refer to error below:
22:11:57.968 DEBUG - http-outgoing-0 << "{"sessionId":"9405fad70a09f38786e511b3e2132060","status":13,"value":{"message":"unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-696.6.3.el6.x86_64 x86_64)"}}"

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  Test script from WDIO to using chrome broswer
2.  Start selenium standalone server
3.  Trigger test

## Logs
Selenium Standalone log:
> node ./node_modules/selenium-standalone/bin/selenium-standalone start --config=marginator-test/seleniumdriver-config.js -- -debug

22:09:56.790 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
22:09:56.791 INFO - Launching a standalone Selenium Server
2017-11-13 22:09:56.806:INFO::main: Logging initialized @208ms to org.seleniumhq.jetty9.util.log.StdErrLog
22:09:56.853 INFO - Driver class not found: com.opera.core.systems.OperaDriver
22:09:56.877 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
22:09:56.878 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
22:09:56.878 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
22:09:56.900 INFO - Using the passthrough mode handler
2017-11-13 22:09:56.921:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-11-13 22:09:56.946:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@335eadca{/,null,STARTING} has uncovered http methods for path: /
2017-11-13 22:09:56.951:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@335eadca{/,null,AVAILABLE}
2017-11-13 22:09:56.964:INFO:osjs.AbstractConnector:main: Started ServerConnector@4bbfb90a{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-11-13 22:09:56.965:INFO:osjs.Server:main: Started @366ms
22:09:56.965 INFO - Selenium Server is up and running
2017-11-13 22:09:57.213:INFO:osjshC.ROOT:qtp1910163204-11: org.openqa.selenium.remote.server.WebDriverServlet-d8355a8: Initialising WebDriverServlet
22:09:57.238 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@3e84d9d7
22:09:57.241 INFO - /status: Executing GET on /status (handler: Status)
Selenium started
22:10:57.683 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
22:10:57.683 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@532ac31a
22:10:57.684 INFO - /session: Executing POST on /session (handler: BeginSession)
22:10:57.697 DEBUG - Memory-based payload for: {desiredCapabilities={rotatable=true, locationContextEnabled=true, loggingPrefs={driver=ALL, browser=ALL}, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}}
22:10:57.703 INFO - Capabilities are: Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={driver=ALL, browser=ALL, }, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io, }, }
22:10:57.704 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={driver=ALL, browser=ALL, }, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
22:10:57.705 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={driver=ALL, browser=ALL, }, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
22:10:57.722 DEBUG - Waiting for [http://localhost:24330/status]
22:10:57.722 DEBUG - Polling http://localhost:24330/status
Starting ChromeDriver 2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5) on port 24330
Only local connections are allowed.
22:10:57.739 DEBUG - Polling http://localhost:24330/status
22:10:57.741 DEBUG - sun.net.www.MessageHeader@5c8e71805 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_73}{Host: localhost:24330}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
22:10:57.742 DEBUG - sun.net.www.MessageHeader@524994614 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 141}{Content-Type: application/json; charset=utf-8}{Connection: close}
22:10:57.923 DEBUG - CookieSpec selected: default
22:10:57.929 DEBUG - Auth cache not set in the context
22:10:57.930 DEBUG - Connection request: [route: {}->http://localhost:24330][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
22:10:57.938 DEBUG - Connection leased: [id: 0][route: {}->http://localhost:24330][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
22:10:57.939 DEBUG - Opening connection {}->http://localhost:24330
22:10:57.940 DEBUG - Connecting to localhost/127.0.0.1:24330
22:10:57.940 DEBUG - Connection established 127.0.0.1:49052<->127.0.0.1:24330
22:10:57.940 DEBUG - http-outgoing-0: set socket timeout to 10800000
22:10:57.941 DEBUG - Executing request POST /session HTTP/1.1
22:10:57.941 DEBUG - Target auth state: UNCHALLENGED
22:10:57.941 DEBUG - Proxy auth state: UNCHALLENGED
22:10:57.942 DEBUG - http-outgoing-0 >> POST /session HTTP/1.1
22:10:57.942 DEBUG - http-outgoing-0 >> Content-Type: application/json; charset=utf-8
22:10:57.943 DEBUG - http-outgoing-0 >> Content-Length: 292
22:10:57.943 DEBUG - http-outgoing-0 >> Host: localhost:24330
22:10:57.943 DEBUG - http-outgoing-0 >> Connection: Keep-Alive
22:10:57.943 DEBUG - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_73)
22:10:57.943 DEBUG - http-outgoing-0 >> Accept-Encoding: gzip,deflate
22:10:57.943 DEBUG - http-outgoing-0 >> "POST /session HTTP/1.1[\r][\n]"
22:10:57.943 DEBUG - http-outgoing-0 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
22:10:57.943 DEBUG - http-outgoing-0 >> "Content-Length: 292[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "Host: localhost:24330[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_73)[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "[\r][\n]"
22:10:57.944 DEBUG - http-outgoing-0 >> "{"desiredCapabilities":{"rotatable":true,"locationContextEnabled":true,"loggingPrefs":{"driver":"ALL","browser":"ALL"},"browserName":"chrome","javascriptEnabled":true,"handlesAlerts":true,"maxInstances":5,"requestOrigins":{"name":"webdriverio","version":"4.6.2","url":"http://webdriver.io"}}}"
[0.393][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
[0.444][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
[0.496][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
[0.547][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
...
..
60.183][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
[60.235][SEVERE]: CreatePlatformSocket() returned an error, errno=97: Address family not supported by protocol
22:11:57.968 DEBUG - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
22:11:57.968 DEBUG - http-outgoing-0 << "Content-Length:273[\r][\n]"
22:11:57.968 DEBUG - http-outgoing-0 << "Content-Type:application/json; charset=utf-8[\r][\n]"
22:11:57.968 DEBUG - http-outgoing-0 << "Connection:close[\r][\n]"
22:11:57.968 DEBUG - http-outgoing-0 << "[\r][\n]"
22:11:57.968 DEBUG - http-outgoing-0 << "{"sessionId":"9405fad70a09f38786e511b3e2132060","status":13,"value":{"message":"unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-696.6.3.el6.x86_64 x86_64)"}}"
22:11:57.970 DEBUG - http-outgoing-0 << HTTP/1.1 200 OK
22:11:57.970 DEBUG - http-outgoing-0 << Content-Length:273
22:11:57.970 DEBUG - http-outgoing-0 << Content-Type:application/json; charset=utf-8
22:11:57.971 DEBUG - http-outgoing-0 << Connection:close
22:11:57.974 DEBUG - http-outgoing-0: Close connection
22:11:57.974 DEBUG - Connection discarded
22:11:57.974 DEBUG - Connection released: [id: 0][route: {}->http://localhost:24330][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]

## Your Environment
* Version of `selenium-standalone` that you are using: selenium-standalone-6.9.0
* Is there another tool calling `selenium-standalone` on your behalf: Yes, WDIO- webdriverio-4.8.0
* System/platform: Linux 2.6.32-696.6.3.el6.x86_64 x86_64
* Other details that might be important: drivers.chrome.versions= 2.29

**Comment by mg80** [comment]
I have seen this error when trying to run chrome on a headless environment without specifying it to run headless. I'm guessing it's a more general issue of trying to start a session on a device where the chrome driver isn't compatible with the requested session.

**Comment by kheerthi** [comment]
Hi, was the above error resolved?

**Comment by P0403** [comment]
No, it is not yet resolved ...

**Comment by lumean** [comment]
Might be related to this:
https://bugs.chromium.org/p/chromium/issues/detail?id=700347
We had similar problems when running chromedriver inside an ubuntu docker on a centos 7 host. Although we didn't confirm the root-cause 100%, I'm quite sure it was related to kernel as mentioned in the chromium issue. I'm not sure about IPv6, as we did actually disable IPv6 via chromedriver options, but still saw the issue.
As soon as we swapped the docker host OS to ubuntu 16.04 (kernel 4.X , instead of centos 7 - kernel 3.10) the issue was gone.

**Comment by visch** [comment]
Not the same error but to help fellow googlers I received this

[SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)


This ended up being because I was running google chrome as root, which requires a "no-sandbox" parameter. In reality you shouldn't be running as root so shame on me.  My chrome driver couldn't communicate with chrome but there wasn't a super clear indicator of this.

**Comment by mgrybyk** [comment]
Try running the latest version of Chrome in headless mode with args `'--headless', '--no-sandbox'`

**Comment by object-destructuring** [comment]
https://stackdev.space/questions/the-operation-of-chromedriver-is-hindered-on-centos-65-and-it-is-unable-to



The answer’s discovered
