### ISSUE TITLE
Starting the server programmatically vs 'start-selenium'

### ISSUE THREAD

**Issue by eawer** [vvo/selenium-standalone#33]
Today I found out, that server, that was started programmaticaly != server, that was started using 'start-selenium' command. Here is the topic, which describes the problem - https://groups.google.com/forum/#!topic/webdriverio/b7ohm7tkG7Q

Key takeaways:
- if I start the server programmatically - testing fails
- if I start the server using 'start-selenium' - testing succeeds.

Can you please tell if I'm doing it wrong, or is it some bug?

**Comment by vvo** [comment]
@Shtirlits This should now be solved

**Comment by gghez** [comment]
I get a similare issue when calling this code:
```js
var selenium = require('selenium-standalone');
selenium.start({spawnOptions: {stdio: 'inherit'}}, function(err, child) {
     // code section never called...
});
```

Callback never called...

**Comment by vvo** [comment]
@gghez Can you open a separate issue? Did you `selenium-standalone install` or install via programmatic API before trying to start? Let me know in a separate issue

**Comment by gghez** [comment]
Done #91
