### ISSUE TITLE
Cannnot launch extension for Chrome on a remote machine using RemoteWebDriver

### ISSUE THREAD

**Issue by anzded** [vvo/selenium-standalone#336]
## Expected Behavior
Hello. Need some help. I need to launch Chrome Browser on a remote machine with some extension using Selenium Grid.
## Current Behavior
I use IntelliJ Idea for running my tests+jUnit+Java. If I add an extension for Chrome on my local machine just using ChromeDriver, it works perfect. But when I am tryig to launch it remotly using RemoteWebDriver then only empty Chrome browser is opening. 
## Steps to Reproduce
There is my simple code below that should work accordingly to my understatnding, but it does not
public class remote {
   public static RemoteWebDriver driver;
    @BeforeClass
    public static void setUp() throws MalformedURLException, InterruptedException {
        ChromeOptions options = new ChromeOptions();
        options.addExtensions(new File("D:\\Grid\\extension_1_3_0.crx"));
        options.setBinary("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");
        //options.addArguments("load-extension='C:\\Users\\Andrey Zimin\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Extensions\\dniinonmliiclhbbkamokcmabdhfjioh\\0.12.1_0'","allow-outdated-plugins");
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability(ChromeOptions.CAPABILITY, options);
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);

        
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.manage().window().maximize();
        driver.get("https://google.com");
        Thread.sleep(3000);

    }
    @Test
    public void c_exit(){
       driver.quit();
    }
}
## Logs
00:14:52.561 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@280d3b1a
00:14:52.562 INFO - /session: Executing POST on /session (handler: BeginSession)
00:14:52.649 INFO - Capabilities are: Capabilities {browserName: chrome, chromeOptions: {args: [load-extension='C:\Users\An..., allow-outdated-plugins], binary: C:\Program Files (x86)\Goog..., extensions: [Q3IyNAIAAAAmAQAAAAEAADCCASI...]}, goog:chromeOptions: {}, version: }
00:14:52.651 INFO - Capabilities {browserName: chrome, chromeOptions: {args: [load-extension='C:\Users\An..., allow-outdated-plugins], binary: C:\Program Files (x86)\Goog..., extensions: [Q3IyNAIAAAAmAQAAAAEAADCCASI...]}, goog:chromeOptions: {}, version: } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 3735
Only local connections are allowed.
00:14:55.381 INFO - Detected dialect: OSS
00:14:55.590 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5dba2606
00:14:55.593 INFO - Handler thread for session 5047ededde50bcd4f1efbef8f798b1cd (chrome): Executing POST on /session/5047ededde50bcd4f1efbef8f798b1cd/timeouts (handler: ServicedSession)
00:14:55.601 INFO - To upstream: {"type":"implicit","ms":30000}
00:14:55.608 INFO - To downstream: {"sessionId":"5047ededde50bcd4f1efbef8f798b1cd","status":0,"value":null}
00:14:55.632 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5dba2606
00:14:55.646 INFO - Handler thread for session 5047ededde50bcd4f1efbef8f798b1cd (chrome): Executing POST on /session/5047ededde50bcd4f1efbef8f798b1cd/window/current/maximize (handler: ServicedSession)
00:14:55.661 INFO - To upstream: {"windowHandle":"current"}
00:14:56.827 INFO - To downstream: {"sessionId":"5047ededde50bcd4f1efbef8f798b1cd","status":0,"value":null}
00:14:56.857 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5dba2606
00:14:56.859 INFO - Handler thread for session 5047ededde50bcd4f1efbef8f798b1cd (chrome): Executing POST on /session/5047ededde50bcd4f1efbef8f798b1cd/url (handler: ServicedSession)
00:14:56.870 INFO - To upstream: {"url":"https://www.google.com"}
00:14:59.437 INFO - To downstream: {"sessionId":"5047ededde50bcd4f1efbef8f798b1cd","status":0,"value":null}
00:15:02.458 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5dba2606
00:15:02.458 INFO - Handler thread for session 5047ededde50bcd4f1efbef8f798b1cd (chrome): Executing DELETE on /session/5047ededde50bcd4f1efbef8f798b1cd (handler: ServicedSession)
00:15:02.769 INFO - To downstream: {"sessionId":"5047ededde50bcd4f1efbef8f798b1cd","status":0,"value":null}
00:15:02.776 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@5dba2606
00:15:03.194 INFO - To downstream: {"sessionId":"","status":0,"value":null}

If there are lots of logs, please link to [a public gist](https://gist.github.com/).

## Your Environment
Windows 10, 
selenium-server-standalone-3.8.1.jar,
Chrome driver last version 2.34
Chrome version 63.0

**Comment by mgrybyk** [comment]
Please try with the latest version and provide with reproducible example if the issue persists.

Thanks
