### ISSUE TITLE
ChromeOptions not being passed to selenium grid node

### ISSUE THREAD

**Issue by jlseeto101** [vvo/selenium-standalone#350]
## Expected Behavior
Expected the node to start the browser maximize and set useAutomationExtension to false. When running the test locally (using selenium-standalone start), these options works as expected. 

## Current Behavior
Currently the node is ignoring all the chrome options being passed into the chrome driver. 

## Your Environment
* Version of `selenium-standalone` that you are using: 6.13.0
* System/platform: Win10
* Other details that might be important:

Using Webdriverio to pass these options to the chrome driver:
capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        chromeOptions: {
            "useAutomationExtension":false,
            "args":['--start-maximized']
        }
    }],

commands used for starting up selenium-standalone:
* selenium-standalone start -- -role hub
* selenium-standalone start -- -role node -hub http://<ip>/grid/register etc..

**Comment by mg80** [comment]
If this is true it would explain an issue I am seeing after upgrading to 6.13.0 from 6.12.0

**Comment by mg80** [comment]
Any update?

**Comment by mg80** [comment]
Looks like chomeOptions was changed to goog:chromeOptions
