### ISSUE TITLE
Killing child returned by start() leaves chromedriver process running

### ISSUE THREAD

**Issue by prantlf** [vvo/selenium-standalone#351]
## Expected Behavior

The process returned by the `start` method should be enough to stop all additional child processes started by calling its `kill` method. Example of an expected usage:

```js
const selenium = require('selenium-standalone')
selenium.start({...}, function (error, child) {
  if (!error) {
    // work with webdriverio and when finished, stop selenium:
    child.kill()
    // both selenium server and chromedriver process should exit
  }
})
```

## Current Behavior

Killing the process returned by the `start` method stops the selenium server (java) but the chromedriver process remains running. This occurs only, if the selenium process was actually used before trying to stop it. In my example, using [WebdriverIO](http://webdriver.io/) for just initialising and uninitialising the driver was enough:

```js
const webdriverio = require('webdriverio')
const client = webdriverio.remote({...})
client.init()
  .end()
```
If the driver usage by the above code was removed, both processes were stopped after calling the `kill` method of the returned child, as expected. Additionally, if a delay was introduced *after* calling the `end` method of the WebdriverIO client, the chromedriver process was topped too! It can be used as a workaround. Waiting for 1 ms was not enough, but waiting for 100 ms, or longer, helped:

```js
const webdriverio = require('webdriverio')
const client = webdriverio.remote({...})
client.init()
  .end()
  .pause(100)
```

## Steps to Reproduce

Create a testing directory, install latest versions of the following npm modules there, download [selenium.test.js](https://gist.github.com/prantlf/a3c2a267ed48f4f779888189c269d349#file-selenium-test-js) there, execute it and check for running selenium processes:

```sh
npm i selenium-standalone
npm i webdriverio
node selenium.test.js
ps ax | grep selenium
```
Only the `grep selenium` process should be printed, but the `chromedriver` process from the "node_modules/selenium-standalone/.selenium" directory is printed too.

I wrote comments in the attached script about what do modify there to help the chromedriver process stop.

## Logs

Executing the attached script with extra logging prints more information - see [selenium.test.txt](https://gist.github.com/prantlf/a3c2a267ed48f4f779888189c269d349#file-selenium-test-txt) - but no information about the process-stopping phase.

## Testing Environment

Versions of Node.js and npm modules:

```txt
node:                8.10.0
npm:                 5.6.0
selenium-standalone: 6.13.0
webdriverio:         4.12.0
```

Operating system with latest updates applied:

```sh
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Bionic Beaver (development branch)
Release:	18.04
Codename:	bionic
$ uname -a
Linux de08365 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fractile81** [comment]
I have the same problem on Windows.

Versions:
```
node: 10.6.0
npm: 6.0.0
selenium-standalone: 6.15.1
chromedriver: 2.40
```

**Comment by mgrybyk** [comment]
Please try the latest version.

Feel free to re-open if the issue persists.

Thanks!
