### ISSUE TITLE
Use latest version of chromedriver

### ISSUE THREAD

**Issue by vlashchevskyi** [vvo/selenium-standalone#353]
## Expected Behavior
It should be used `chromedriver 2.37` for working with `Chrome 65`.
I updated my `lib/default-config.js`:
```
3 3   version: '3.8.1',
4 4   drivers: {
5 5     chrome: {
6   -     version: '2.36',
  6 +     version: '2.37',
7 7       arch: process.arch,
8 8       baseURL: 'https://chromedriver.storage.googleapis.com'
9 9     },
```
and it works good.

## Current Behavior
After clone my tests from git & `npm i` it uses old version of chromedriver, so my tests not work.

## Your Environment
* Version of `selenium-standalone` that you are using: 6.13.0
* `wdio-selenium-standalone-service`: 0.0.10
* System/platform: Windows 10

**Comment by serbanghita** [comment]
The change is already in the master. https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js#L6
This can be closed 🍻 Thank you!
