### ISSUE TITLE
Set trustAllSSLCertificates programmatically

### ISSUE THREAD

**Issue by basickarl** [vvo/selenium-standalone#356]
How does one use the programmable API to set the trustAllSSLCertificates property? I'm using a self-signed certificate.

I found the following buy don't know how it works:
https://github.com/vvo/selenium-standalone#error-unable-to-get-local-issuer-certificate
Is this an environmental variable?

**Comment by mgrybyk** [comment]
Feel free to reopen if it's still an issue. Thanks!
