### ISSUE TITLE
Compute-fs-paths should use opts.version and not opts.seleniumVersion

### ISSUE THREAD

**Issue by humphreyn** [vvo/selenium-standalone#358]
## Expected Behavior
When using the compute-fs-paths.js to get the selenium server install path. Given the steps to reproduce below I expect the console output to be:

"./selenium/selenium-server/3.11.0-server.jar"

I would suggest that we change line 35 in compute-fs-paths.js to use opts.version rather than opts.seleniumVersion

## Current Behavior

undefined-server.jar

## Steps to Reproduce
const seleniumStandalone = require('selenium-standalone');
const seleniumPaths = require('../node_modules/selenium-standalone/lib/compute-fs-paths');
const driverPaths = seleniumPaths({
  version: '3.11.0',
  baseURL: 'https://selenium-release.storage.googleapis.com',
  basePath: "./selenium/",
  drivers: {
    chrome: {
      version: '2.31',
      arch: process.arch,
      baseURL: 'https://chromedriver.storage.googleapis.com'
    }
  });

console.log(driverPaths.selenium.installPath);

Expect:
 "./selenium/selenium-server/3.11.0-server.jar"
but get
 "undefined-server.jar"

## Your Environment
* Version of `selenium-standalone` that you are using: 6.14.0
* Is there another tool calling `selenium-standalone` on your behalf: No
* System/platform: Windows 10
* Other details that might be important: NodeJS v:8.9.4

**Comment by mgrybyk** [comment]
fixed now

**Comment by humphreyn** [comment]
big :+1:
