### ISSUE TITLE
Add option to disable download of certain unneeded drivers

### ISSUE THREAD

**Issue by robcalcroft** [vvo/selenium-standalone#361]
## Expected Behavior
I should be able to specify in the configuration file that I don't want an certain driver to be downloaded perhaps denoted by passing e.g. `{ edge: false }`.

## Current Behavior
Currently the code merges the default configuration into my configuration and then the drivers I have left out still get downloaded and because I am behind a firewall, it fails the install process. 

## Steps to Reproduce
Try installing with a custom configuration pointed to an internal hosting service  and not specifying e.g. IE driver on Windows, it will still download from the public internet site in the default config

## Your Environment
* Version of `selenium-standalone` that you are using: 6.14.1
* Is there another tool calling `selenium-standalone` on your behalf: nope
* System/platform: Windows & Mac

**Comment by kbartnik1** [comment]
I have encountered the same issue. Anything that would disable merging with default config would be appreciated.

**Comment by kylewhitaker** [comment]
@robcalcroft @kbartnik1 I've submitted PR #448 as a proposed solution to this request.

**Comment by vvo** [comment]
closed by #448
