### ISSUE TITLE
Update HISTORY.md please?

### ISSUE THREAD

**Issue by corysimmons** [vvo/selenium-standalone#368]
Please keep this up-to-date, or remove it for notes attached to tagged releases. My use case is tracking down some driver mismatches. :}

Thank you for your work on this.

**Comment by serbanghita** [comment]
Ok, I will start updating that on each release.
@corysimmons how often do you run into browser/driver mismatch? I am planning on adding e2e tests to detect this before a release

**Comment by corysimmons** [comment]
Every time I've been forced to use Selenium by some company, there are always problems with it.

Thus things like Cypress and Testcafe have been gaining traction.

**Comment by serbanghita** [comment]
@corysimmons thanks for sharing that!
