### ISSUE TITLE
Allow custom config for Microsoft Edge, instead of relying on version

### ISSUE THREAD

**Issue by npeterkamps** [vvo/selenium-standalone#372]
## Expected Behavior

* Allow to manually configure the entire config for Edge, including version, url and extension.
* `selenium-standalone` should use the version within the downloaded file name.

## Current Behavior

Currently, Edge only supports a version within the config. Since #364 isn't merged yet, I'm unable to automate the download process. Instead of putting pressure on pull requests, it might be good to support manual configuration (not limited to Edge, but my current experience is only related to Edge).

https://github.com/vvo/selenium-standalone/blob/494223ef2fd80b6e1521f61974e12b0cc13d98fb/lib/compute-download-urls.js#L80-L82

https://github.com/vvo/selenium-standalone/blob/494223ef2fd80b6e1521f61974e12b0cc13d98fb/lib/compute-download-urls.js#L249-L256

This makes things currently limited.

## Your Environment
* Version of `selenium-standalone` that you are using: 6.15.0
* Is there another tool calling `selenium-standalone` on your behalf: No.
* System/platform: Windows 10.0.17134.48

**Comment by serbanghita** [comment]
Agree 👍 , I will couple this change with https://github.com/vvo/selenium-standalone/pull/365
