### ISSUE TITLE
Add JS linter

### ISSUE THREAD

**Issue by serbanghita** [vvo/selenium-standalone#377]
Add eslint with Airbnb default rules.
This is good for future refactorings and new tests.
It will also be added as an additional step to build and release.

**Comment by marlonemmerich** [comment]
hmm..
Maybe I can help with this if you want

**Comment by mgrybyk** [comment]
Go aheas, please add go CI as well

**Comment by marlonemmerich** [comment]
Hello!
I've created a new [PR](https://github.com/vvo/selenium-standalone/pull/484) (484). 
But sure if we run "npm run lint" we will get some erros and warnings. With this command link will the folders "lib" and "bin".
It's some think like this you have in your mind?
if not, just tell me! Cya!

**Comment by mgrybyk** [comment]
Let's proceed convo in the PR
