### ISSUE TITLE
Cannot download IEDriverServer_x64_3.12.0.zip

### ISSUE THREAD

**Issue by fang130tao** [vvo/selenium-standalone#383]
## Expected Behavior
When I installed the plug-in in API, I made a mistake in this command ("selenium-standalone start").
it throw a error :
**Error: Could not request headers from https://seleniumrelease.storage.googleapis.com/3.12/IEDriverServer_x64_3.12.0.zip: Error: connect ETIMEDOUT 216.58.197.112:443**

## Current Behavior
I searched for the reason in the search engine and opened the official address of the installation package. But it is different from the address in CLI. Maybe the address of the installation package is not correct. Please check this error.
**https://selenium-release.storage.googleapis.com/index.html?path=3.12/IEDriverServer_x64_3.12.0.zip**

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  npm install selenium-standalone@latest -g
2.  selenium-standalone install
3.  
4.  

## Logs
edge install:
from: https://download.microsoft.com/download/F/8/A/F8AF50AB-3C3A-4BC4-8773-DC27B32988DD/MicrosoftWebDriver.exe
to: C:\Users\jiangyang\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\edgedriver\17134-MicrosoftEdgeDriver.exe
---
File from https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-win64.zip has already been downloaded
C:\Users\jiangyang\AppData\Roaming\npm\node_modules\selenium-standalone\bin\selenium-standalone:111
        throw err;
        ^

Error: Could not request headers from https://selenium-release.storage.googleapis.com/3.12/IEDriverServer_x64_3.12.0.zip: Error: connect ETIMEDOUT 216.58.197.112:443
    at Request.<anonymous> (C:\Users\jiangyang\AppData\Roaming\npm\node_modules\selenium-standalone\lib\install.js:552:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\jiangyang\AppData\Roaming\npm\node_modules\selenium-standalone\node_modules\_request@2.87.0@request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

## Your Environment
* Version of `selenium-standalone` that you are using: the lasted
* Is there another tool calling `selenium-standalone` on your behalf: no
* System/platform:  win10
* Other details that might be important:

**Comment by serbanghita** [comment]
@fang130tao was this a problem on your end? I guess it was connection problems, since I can download the zip file.

**Comment by fang130tao** [comment]
@serbanghita yes,solved, when I run 'selenium-standalone install', every time there are different files that can not be downloaded. It may be caused by network instability. I did not use this command again and back to scan the Macaca document .I found this commond  'selenium-standalone install --drivers.firefox.baseURL=http://npm.t...'  and  run it .It works,  the download was successful. - . -
