### ISSUE TITLE
Set custom user-agent for Microsoft Edge

### ISSUE THREAD

**Issue by sopnopriyo** [vvo/selenium-standalone#390]
I have looked into the previous issues about  setting up user-agent for Chrome and Firefox from [Issue 168](https://github.com/vvo/selenium-standalone/issues/168)

But I could not find any documentation for setting the user-agent for Microsoft Edge.

Is there any workaround available for that ?

**Comment by mgrybyk** [comment]
Hello,
the question is not related to the selenium-standalone
