### ISSUE TITLE
Update default-config geckodriver to 0.23.0 to support Firefox 63

### ISSUE THREAD

**Issue by usergenic** [vvo/selenium-standalone#409]
## Expected Behavior
Firefox 63 should be controllable by geckodriver.

## Current Behavior
The version of geckodriver in the package is out-of-date and does not support Firefox 63

## Steps to Reproduce
Update default-config geckodriver version to 0.23.0

**Comment by usergenic** [comment]
@vvo if you merge PR #408 people can use selenium-standalone as-is with Firefox 63.  Otherwise, it fails because the default geckodriver version (0.20.1) doesn't work with it.

**Comment by jwalton** [comment]
By way of a workaround:

```
selenium-standalone install --drivers.firefox.version=0.23.0
npx selenium-standalone start --drivers.firefox.version=0.23.0
```

**Comment by salomvary** [comment]
Workaround for users of [wdio-standalone-service](https://github.com/webdriverio-boneyard/wdio-selenium-standalone-service):

Add these to `wdio.conf.js`:

```
  seleniumArgs: {drivers: Object.assign({}, require('selenium-standalone/lib/default-config').drivers, {firefox: {version: '0.23.0'}})},
  seleniumInstallArgs: {drivers: Object.assign({}, require('selenium-standalone/lib/default-config').drivers, {firefox: {version: '0.23.0'}})},
```
