### ISSUE TITLE
failed to change window state to maximized

### ISSUE THREAD

**Issue by Stngle** [vvo/selenium-standalone#410]
## Unexpected Behavior
![image](https://user-images.githubusercontent.com/18617837/47850600-cd4cb700-de10-11e8-8bfb-3e3a0c07534e.png)

## Current Behavior
selenium-standalone version 6.15.3
chromedriver version 2.43 (I have changed the `default-config.js` file)
chrome browser version 70.x
MacOS

**Comment by Stngle** [comment]
i haven't this problem when i use chrome v69.x

**Comment by wck821829906** [comment]
I also have the same problem

**Comment by stychu** [comment]
@wck821829906 go to the ` node_modules/selenium-standalone/lib/default-config.js` and change the chrome version to at least `2.44` then maximize will work

**Comment by wck821829906** [comment]
@stychu It seems not work
![image](https://user-images.githubusercontent.com/17002975/56862532-86fe9c00-69de-11e9-9809-a895bda173fc.png)

![image](https://user-images.githubusercontent.com/17002975/56862536-95e54e80-69de-11e9-8195-92a6881bb0b1.png)

**Comment by stychu** [comment]
@wck821829906 try changin `chrome:version: 73....` to `2.44` at least

**Comment by mgrybyk** [comment]
Please raise an issue to chromium if it still actual.

Thanks
