### ISSUE TITLE
I can run test in jenkins using vvo/selenium-standalone docker service but not with jenkins: Unable to receive message from renderer

### ISSUE THREAD

**Issue by MohammadHemel** [vvo/selenium-standalone#412]
I can run my tests locally using vvo/selenium-standalone docker but cant seems to run it in Jenkins

## Logs
Successfully built ce488d150ecf
Successfully tagged testenguitests_master-aawv4ixu32cv56xwwzp2gbm5ryhbtcff7f465mxb2ygcpjng4fdq_webdriverio:latest
selenium-standalone is up-to-date
Recreating webdriverio ... 
[1A[2K
Recreating webdriverio ... [32mdone[0m
[1BAttaching to webdriverio
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m > testeng-webdriverio@1.0.0 pretest /testeng-webdriverio
[36mwebdriverio                 |[0m > npm run cleanup && eslint --ignore-path .gitignore ./app
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m > testeng-webdriverio@1.0.0 cleanup /testeng-webdriverio
[36mwebdriverio                 |[0m > rm -rf ./reports && rm -rf ./allure-report && rm -rf ./errorShots/*
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m > testeng-webdriverio@1.0.0 test /testeng-webdriverio
[36mwebdriverio                 |[0m > wdio wdio.conf.js "--host" "selenium-standalone" "--port" "4444"
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m starting test
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;33mDATA		[0m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","chromeOptions":{"args":["headless","window-size=1920,1080"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.0","name":"webdriverio"}}}
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;33mDATA		[0m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","chromeOptions":{"args":["headless","window-size=1920,1080"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.0","name":"webdriverio"}}}
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;33mDATA		[0m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","chromeOptions":{"args":["headless","window-size=1920,1080"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.0","name":"webdriverio"}}}
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
[36mwebdriverio                 |[0m [1;30m[17:34:35] [0m [0;33mDATA		[0m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","chromeOptions":{"args":["headless","window-size=1920,1080"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.0","name":"webdriverio"}}}
[36mwebdriverio                 |[0m [31mERROR: session not created
[36mwebdriverio                 |[0m from disconnected: Unable to receive message from renderer[0m
[36mwebdriverio                 |[0m [93mchrome[0m
[36mwebdriverio                 |[0m [90m    at new RuntimeError (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
[36mwebdriverio                 |[0m     at Request._callback (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
[36mwebdriverio                 |[0m     at Request.self.callback (/testeng-webdriverio/node_modules/request/request.js:185:22)
[36mwebdriverio                 |[0m     at emitTwo (events.js:126:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:214:7)
[36mwebdriverio                 |[0m     at Request.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1161:10)
[36mwebdriverio                 |[0m     at emitOne (events.js:116:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:211:7)
[36mwebdriverio                 |[0m     at IncomingMessage.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1083:12)
[36mwebdriverio                 |[0m     at Object.onceWrapper (events.js:313:30)[0m
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m [31mERROR: session not created
[36mwebdriverio                 |[0m from disconnected: Unable to receive message from renderer[0m
[36mwebdriverio                 |[0m [93mchrome[0m
[36mwebdriverio                 |[0m [90m    at new RuntimeError (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
[36mwebdriverio                 |[0m     at Request._callback (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
[36mwebdriverio                 |[0m     at Request.self.callback (/testeng-webdriverio/node_modules/request/request.js:185:22)
[36mwebdriverio                 |[0m     at emitTwo (events.js:126:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:214:7)
[36mwebdriverio                 |[0m     at Request.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1161:10)
[36mwebdriverio                 |[0m     at emitOne (events.js:116:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:211:7)
[36mwebdriverio                 |[0m     at IncomingMessage.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1083:12)
[36mwebdriverio                 |[0m     at Object.onceWrapper (events.js:313:30)[0m
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m [31mERROR: session not created
[36mwebdriverio                 |[0m from disconnected: Unable to receive message from renderer[0m
[36mwebdriverio                 |[0m [93mchrome[0m
[36mwebdriverio                 |[0m [90m    at new RuntimeError (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
[36mwebdriverio                 |[0m     at Request._callback (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
[36mwebdriverio                 |[0m     at Request.self.callback (/testeng-webdriverio/node_modules/request/request.js:185:22)
[36mwebdriverio                 |[0m     at emitTwo (events.js:126:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:214:7)
[36mwebdriverio                 |[0m     at Request.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1161:10)
[36mwebdriverio                 |[0m     at emitOne (events.js:116:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:211:7)
[36mwebdriverio                 |[0m     at IncomingMessage.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1083:12)
[36mwebdriverio                 |[0m     at Object.onceWrapper (events.js:313:30)[0m
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m [31mERROR: session not created
[36mwebdriverio                 |[0m from disconnected: Unable to receive message from renderer[0m
[36mwebdriverio                 |[0m [93mchrome[0m
[36mwebdriverio                 |[0m [90m    at new RuntimeError (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
[36mwebdriverio                 |[0m     at Request._callback (/testeng-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
[36mwebdriverio                 |[0m     at Request.self.callback (/testeng-webdriverio/node_modules/request/request.js:185:22)
[36mwebdriverio                 |[0m     at emitTwo (events.js:126:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:214:7)
[36mwebdriverio                 |[0m     at Request.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1161:10)
[36mwebdriverio                 |[0m     at emitOne (events.js:116:13)
[36mwebdriverio                 |[0m     at Request.emit (events.js:211:7)
[36mwebdriverio                 |[0m     at IncomingMessage.<anonymous> (/testeng-webdriverio/node_modules/request/request.js:1083:12)
[36mwebdriverio                 |[0m     at Object.onceWrapper (events.js:313:30)[0m
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m 
[36mwebdriverio                 |[0m ==================================================================
[36mwebdriverio                 |[0m Number of specs: 4
[36mwebdriverio                 |[0m Wrote xunit report "WDIO.xunit.chrome.0-0.xml" to [./reports/junit-results/].
[36mwebdriverio                 |[0m Wrote xunit report "WDIO.xunit.chrome.0-3.xml" to [./reports/junit-results/].
[36mwebdriverio                 |[0m Wrote xunit report "WDIO.xunit.chrome.0-1.xml" to [./reports/junit-results/].
[36mwebdriverio                 |[0m Wrote xunit report "WDIO.xunit.chrome.0-2.xml" to [./reports/junit-results/].
[36mwebdriverio                 |[0m Wrote json report to [./reports/json-results/].
[36mwebdriverio                 |[0m Wrote json report to [./reports/json-results/].
[36mwebdriverio                 |[0m Wrote json report to [./reports/json-results/].
[36mwebdriverio                 |[0m Wrote json report to [./reports/json-results/].
[36mwebdriverio                 |[0m Wrote json report to [./reports/mocha-results/].
[36mwebdriverio                 |[0m Test execution completed
[36mwebdriverio                 |[0m [37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Test failed.  See above for more details.
[36mwebdriverio                 |[0m [0m[36mwebdriverio exited with code 1
[0m[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

If there are lots of logs, please link to [a public gist](https://gist.github.com/).

## Your Environment

Trying to run docker compose in jenkins but fails. It runs locally
services:
  wdio-selenium-standalone:
    image: vvoyer/selenium-standalone
    hostname: selenium-standalone
    container_name: selenium-standalone
    volumes:
      - ${PWD}/dev/shm:/dev/shm

  webdriverio:
    build: .
    hostname: webdriverio
    container_name: webdriverio
    links:
      - wdio-selenium-standalone
    depends_on:
      - wdio-selenium-standalone
    tty: true
    volumes:
      - ${PWD}/app:/testeng-webdriverio/app
      - ${PWD}/wdio.conf.js:/testeng-webdriverio/wdio.conf.js
      - ${PWD}/wdio.conf.helper.js:/testeng-webdriverio/wdio.conf.helper.js
      - ${PWD}/user-script-stnd.sh:/testeng-webdriverio/user-script-stnd.sh
      - ${PWD}/errorShots:/testeng-webdriverio/errorShots
    command: bash -c "sh user-script-stnd.sh"
    environment:
      DOCKER_BROWSER_NAME: ${BROWSER}

sh user-script-stnd.sh
npm test -- --host selenium-standalone --port 4444

**Comment by mgrybyk** [comment]
To run selenium-standalone in docker you need to have Java and NodeJS.
It would be better to run browsers in headless mode.
