### ISSUE TITLE
Selenium Server to 3.141.5

### ISSUE THREAD

**Issue by lrocheWB** [vvo/selenium-standalone#417]
Possible to update Selenium server to 3.141.5 ?

Problem: Selenium fails to launch when running on a single cpu
https://github.com/SeleniumHQ/selenium/issues/6605

If I edit "lib/default-config.js" file with this new version and I execute "selenium-standalone install && [...] start", it works !

Thx

**Comment by grandegiraffo** [comment]
Server crashes on startup. Changing the 3.141.0 to 3.141.5 also fixes this for me.

**Comment by mgrybyk** [comment]
fixed now
