### ISSUE TITLE
Microsoft Edge is now a FoD aka Feature on Demand

### ISSUE THREAD

**Issue by jlchereau** [vvo/selenium-standalone#419]
`selenium-standalone install` installs version 17134 of MicrosoftEdgeDriver in `./node_modules/selenium-standalone/.selenium/edgedriver/17134-MicrosoftEdgeDriver.exe`.

This version is obsolete and this no more the way to install the Edge driver. See:
- https://blogs.windows.com/msedgedev/2018/06/14/webdriver-w3c-recommendation-feature-on-demand/
- https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

You should either use:
- `DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0`, or
- Settings -> Manage Optional Features:

![image](https://user-images.githubusercontent.com/2556751/50562765-d8d43580-0d0e-11e9-9ba1-f0e825bad3d8.png)

Then selenium should be configured using `-Dwebdriver.edge.driver=C:\\Windows\\System32\\MicrosoftWebDriver.exe`

**Comment by rodrigovolkmer** [comment]
for those like me that couldn't use any of the methods above on the description, please refer to this link:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/21489934/

**Comment by mgrybyk** [comment]
Please use edge chromium instead
