### ISSUE TITLE
Callback when selenium has started

### ISSUE THREAD

**Issue by daleharvey** [vvo/selenium-standalone#42]
One thing that is irritating using selenium programmatically is waiting for it to be ready to take connections, you can see how we deal with that in pouchdb @ https://github.com/pouchdb/pouchdb/blob/master/bin/test-browser.js#L122

It would be nice to have `selenium(function() { ... selenium is ready ... });`

**Comment by vvo** [comment]
To test for selenium start, it should be done inside the programmatic API and then exposed as a callback yes.

The best way to check for the server to be started is not to parse stderr/stdout but to call /status on the launched server: https://code.google.com/p/selenium/wiki/JsonWireProtocol#/status

**Comment by daleharvey** [comment]
Yup that code linked ^ hits http://localhost:4444/wd/hub/status, probably dont interpret the results correctly though

**Comment by vvo** [comment]
Seems fine they check for 200 that's enough

**Comment by daleharvey** [comment]
Awesome, fixed by https://github.com/vvo/selenium-standalone/commit/364379e2d2ffba20fdc7b1374a157fad58365f8f, thanks :)
