### ISSUE TITLE
Trying to specify firefox driver breaks operations

### ISSUE THREAD

**Issue by hotdog2201** [vvo/selenium-standalone#432]
## Expected Behavior
Should be able to specify a version of firefox driver, such as 0.24.0, and then have selenium recognise this and run the tests in the browser. This should also apply for chrome

## Current Behavior
Neither chrome nor firefox start when trying to use a config file or options for specifying driver version, 
chrome fails with : "Can't connect to WebDriver.
unknown error: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)"
firefox fails with : "Error: Can't connect to WebDriver.
unknown error: invalid argument: can't kill an exited process"

## Steps to Reproduce
i am running a yarn command as follows:
    "automation:server": "selenium-standalone install --config=e2eTests/.seleniumConfig.js  && selenium-standalone start --config=e2eTests/.seleniumConfig.js",
and am then running tests with codeceptjs, which uses webdriver,  "automation:run": "codeceptjs run --steps".

## Logs
Error: Can't connect to WebDriver.
unknown error: invalid argument: can't kill an exited process
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
Driver info: driver.version: unknown
remote stacktrace: 

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

unknown error: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 3.10.0-862.14.4.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 206 milliseconds
Driver info: driver.version: unknown

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

## Your Environment
* Version of `selenium-standalone` that you are using: 6.16.0
* Is there another tool calling `selenium-standalone` on your behalf: codeceptjs
* System/platform: Centos 7 Linux
* Other details that might be important: firefox version 60.3.0esr, chrome version, 71.0.3578.98, attempting to use firefox driver 0.24.0 and chromedriver 2.44

my config file is as follows:

module.exports = {
    drivers: {
      chrome: {
        version: '2.44',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com'
      },
      firefox: {
        version: '0.24.0',
        arch: process.arch,
        baseURL: 'https://github.com/mozilla/geckodriver/releases/download'
      },
    } 
}

**Comment by mgrybyk** [comment]
If it's still an issue please provide with a reproducible example

Thanks!
