### ISSUE TITLE
ChromeDriver version

### ISSUE THREAD

**Issue by stychu** [vvo/selenium-standalone#434]
Current driver for chrome `2.43` is kinda bugged and you're unable to maximize the window.
When I changed the version from `2.43` to `2.44` it worked as expected.

Please update the configurations for drivers

**Comment by stychu** [comment]
why it's still being outdated?? Every time I have to change the config file in node modules in order to chromedriver to properly work...

**Comment by nikhilo** [comment]
@stychu Can you tell how to change the config to use `2.44` ?
I'm seeing some problem with latest chrome, and I wanted to try with latest chromedriver

**Comment by nikhilo** [comment]
Looks like updating `./node_modules/selenium-standalone/lib/default-config.js` did the job. But didn't help with my error. Nvm.

**Comment by balukov** [comment]
> Current driver for chrome `2.43` is kinda bugged and you're unable to maximize the window.
> When I changed the version from `2.43` to `2.44` it worked as expected.

same problem

**Comment by webOS101** [comment]
With Chrome 75 and 76, this outdated chromedriver doesn't work for mouse actions.  This is causing a lot of failing tests.
