### ISSUE TITLE
ERROR: Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by Taewa** [vvo/selenium-standalone#438]
## Expected Behavior
I expect to see Chrome is being opened and start test by running `./node_modules/.bin/wdio wdio.e2e.conf.js`

## Current Behavior
When I run `./node_modules/.bin/wdio wdio.e2e.conf.js`, I see an error message.
```
A service failed in the 'onPrepare' hook
Error: Missing /Users/moka/workspace/my-app/node_modules/selenium-standalone/.selenium/chromedriver/2.43-x64-chromedriver
    at /Users/moka/workspace/my-app/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)

Continue...
[wdio-webcomponents] Overriding native wdio element/elements commands!
ERROR: Unable to create new service: ChromeDriverService
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'SOME_HOST', ip: 'SOME_IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '12.0.1'
Driver info: driver.version: unknown
chrome
    at new RuntimeError (/Users/moka/workspace/my-app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/Users/moka/workspace/my-app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/Users/moka/workspace/my-app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/moka/workspace/my-app/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/moka/workspace/my-app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

I am confused with ChromeDriver.
From what I understand is that when the test start, Selenium tries to find chromedriver at `node_modules/selenium-standalone/.selenium/chromedriver/2.43-x64-chromedriver` which doesn't exist.

So I tried 
`selenium-standalone install`
And terminal shows the below

```
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.5.jar
to: /Users/moka/.nvm/versions/node/v8.16.0/lib/node_modules/selenium-standalone/.selenium/selenium-server/3.141.5-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.43/chromedriver_mac64.zip
to: /Users/moka/.nvm/versions/node/v8.16.0/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.43-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz
to: /Users/moka/.nvm/versions/node/v8.16.0/lib/node_modules/selenium-standalone/.selenium/geckodriver/0.23.0-x64-geckodriver
---
File from https://chromedriver.storage.googleapis.com/2.43/chromedriver_mac64.zip has already been downloaded
---
File from https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.5.jar has already been downloaded
---
File from https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz has already been downloaded
```

Ok I can see that chromedriver is downloaded but it's downloaded on `/Users/moka/.nvm/versions/node/v8.16.0/` directory. Not on my `/Users/moka/workspace/my-app/node_modules` directory.

I tried again `./node_modules/.bin/wdio wdio.e2e.conf.js` to check if anything has been changed.

I still see the same error `ERROR: Unable to create new service: ChromeDriverService`

By Googling, I figured out that Chrome and Chromedriver should match the version.
My Chrome's version is 75.0.3770.80
So I went [here](https://sites.google.com/a/chromium.org/chromedriver/home) and downloaded chromedriver for 75.
Unzip the file and copy and paste into 
`/Users/moka/workspace/my-app/node_modules/selenium-standalone/.selenium/chromedriver/`

and change the file name as `2.43-x64-chromedriver`

I tried again `./node_modules/.bin/wdio wdio.e2e.conf.js`

A bit better. At least Chrome was opened and get failed with error that never seen.

`Promise was rejected with the following reason: number or type of arguments don't agree with elementIdDisplayed protocol command`

Ok...how about I try with Chromedriver 74? (with Chrome 75)

And it works everything.

From this moment I felt I am totally lost.

I also tried with `webdriver-manager` to manage versioning but no luck.

I guess this might be version issue or some driver is missing but find no clue.

So my question is:
1. Is this normal that there is no driver at `/Users/moka/workspace/my-app/node_modules/selenium-standalone/.selenium/chromedriver/` when I installed selenium-standalone by `npm install selenium-standalone --save-dev`?

1. When I run `selenium-standalone install`, is this normal that the chromedriver is downloaded on `/Users/moka/.nvm/versions/node/v8.16.0/lib/node_modules/selenium-standalone/.selenium`?

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  `npm install selenium-standalone --save-dev`
2.  `selenium-standalone install`
3.  `selenium-standalone start`
4.  Go to the project directory
5.  Run `./node_modules/.bin/wdio wdio.e2e.conf.js`
6. See an error `ERROR: Unable to create new service: ChromeDriverService`

## Your Environment
* MacOS Mojave 10.14.5
* Chrome 75.0.3770.80 (Official Build) (64-bit)
* selenium-standalone: 6.16.0
* webdriverio: 4.14.4
* wdio-selenium-standalone-service: 0.0.12
* wdio-webcomponents: 1.1.0
* node: 8.16.0
* npm: 6.4.1
* nvm: 0.34.0

**Comment by tzujui** [comment]
Hi @Taewa 
I am experiencing a similar issue and seeing timeout errors `Error: Could not download https://chromedriver.storage.googleapis.com/2.40/chromedriver_mac64.zip: Error: connect ETIMEDOUT 199.36.153.5:443` and `Error: Could not download https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar: Error: connect ETIMEDOUT 199.36.153.5:443` I am not sure why but I think https://selenium-release.storage.googleapis.com is inaccessible at the moment which causes missing files. 

To answer your question
1. No, not normal. I have `2.40-x64-chromedriver     2.40-x64-chromedriver.zip` under `node_modules/selenium-standalone/.selenium/chromedriver/`
2. Yes, here's the content when I do a `ls` at `node_modules/selenium-standalone/.selenium`
`chromedriver    geckodriver     selenium-server`

Hope this helps!

**Comment by Taewa** [comment]
Hi @tzujui 
Ok it's good to know that I was just unlucky.

**Comment by Taewa** [comment]
@tzujui 
I have created a new project and executed `npm i npm install selenium-standalone --save-dev`
But I don't find `.selenium` folder in `node_modules/selenium-standalone`.

I think it's something generated from local.
But I don't know how to generate.

Any idea?

**Comment by tzujui** [comment]
@Taewa 
Nice! Are you able to download the jar files now? 
Also, I've ran into issues on file permission - make sure executables are `chmod 755`.
