### ISSUE TITLE
Configurable download URLs

### ISSUE THREAD

**Issue by rdepena** [vvo/selenium-standalone#44]
Hey guys, one of our projects is being used within a pretty strict firewall and the downloads are failing, I would like to add configurable CDN rules like phantomJS to alleviate the issue: 

PhantomJS code for example:
https://github.com/Medium/phantomjs/blob/master/install.js#L26

I could take care of it but wanted to make sure before I spend some time on it.

**Comment by vvo** [comment]
@rdepena I do not understand, what other url would you use to download selenium or chrome driver for example?

selenium-standalone already supports setting a proxy for download (just set the proxy on your system or set env variables).

**Comment by vvo** [comment]
@rdepena done https://github.com/vvo/selenium-standalone/blob/master/HISTORY.md#320-2015-01-23

**Comment by rdepena** [comment]
woa, awesome. thank you.
