### ISSUE TITLE
Unable to install selenium v4.0.0-alpha-1

### ISSUE THREAD

**Issue by kad0108** [vvo/selenium-standalone#445]
#### Usage:
```javascript
selenium.install({
  baseURL: 'https://npm.taobao.org/mirrors/selenium',
  version: '4.0.0-alpha-1',
}, )
```

#### Current Behavior:
```
selenium-install-error Error: Could not download https://npm.taobao.org/mirrors/selenium/4.0-alpha-1/selenium-server-standalone-4.0.0-alpha-1.jar
```

#### Expected Behavior:
Actually, the `4.0.0-alpha-1.jar` is below the dir `4.0/`, the right url is `https://npm.taobao.org/mirrors/selenium/4.0/selenium-server-standalone-4.0.0-alpha-1.jar`

And I found the [origin code](https://github.com/vvo/selenium-standalone/blob/ee0e5edf08237331249da12835191d85b3b2b966/lib/compute-download-urls.js#L43)  which generate the selenium install path here, not sure whether it helps.

How can I set the specific version path？

**Comment by hieuxlu** [comment]
If no one has been work on this, I can take this up, just a minor change to support `alpha` syntax, so `4.0.0-alpha-6 => `4.0-alpha`. A nice to have would be to be able to specify a custom URL.
```
  // 2.44.0 => 2.44
  // 2.44.0 would be `patch`, 2.44 `minor`, 2 `major` as per semver

  var downloadUrls = {
    selenium: util.format(
      urls.selenium,
      opts.seleniumBaseURL,
      opts.seleniumVersion.replace(/(\d+\.\d+)\.\d+/, "$1"),
```

**Comment by mgrybyk** [comment]
@hieuxlu are you still able to help with this one?

**Comment by hieuxlu** [comment]
> @hieuxlu are you still able to help with this one?

Yes, are you a maintainer? I see no replies from the team so didn't take any action.

**Comment by mgrybyk** [comment]
What do you think if we implement this one https://github.com/vvo/selenium-standalone/issues/437 instead? It would allow inatalling v4 by exact url

**Comment by hieuxlu** [comment]
> Yes. What do you think if we implement this one https://github.com/vvo/selenium-standalone/issues/437 instead? It would allow inatalling v4 by exact url

Ah I saw that one too, but it's been 2 years old and need more effort. I agree that would be the best approach. It makes sense to start working on that and close this one.

**Comment by mgrybyk** [comment]
On it.

In order to download selenium v4, please specify `fullURL`, ex
```
selenium.install({
  baseURL: 'https://selenium-release.storage.googleapis.com/4.0-alpha-7/selenium-server-4.0.0-alpha-7.jar,
  version: '4.0.0-alpha-7',
  drivers: {}
})
```

See CLI/API docs for more details
