### ISSUE TITLE
How to update ChromeDriver?

### ISSUE THREAD

**Issue by Taewa** [vvo/selenium-standalone#446]
## Expected Behavior
Open Chrome with configured address.

## Current Behavior
When I run my test it runs `WebdriverIo4` and `selenium-standalone` and Chrome is open.
But the address bar shows `data:,` instead of `https://my-website.com`.

I have [found that I should update](https://github.com/webdriverio/webdriverio/issues/2250) my `chromedriver`.

I have [followed this steps to update](https://www.swtestacademy.com/install-chrome-driver-on-mac/) `chromedriver`.
But the browser is still displaying `data:,`.

I am not sure if I updated `chromedriver` properly for `selenium-standalone`.

I know there is a command that select driver version. ( and [here is version matching](https://stackoverflow.com/questions/41133391/which-chromedriver-version-is-compatible-with-which-chrome-browser-version) )
`selenium-standalone start --drivers.chrome.version=77.0.3865.40`

But it's saying I don't have that driver.

One side question is why `selenium-standalone`'s chrome driver is `2.43` whereas [chromedriver website](http://chromedriver.chromium.org/) shows `77.0`?
Feels like the gap is quite big between 2.43 and 77.0. So I am confused.

// EDIT 1
Found the version rules ( [here](https://stackoverflow.com/questions/41133391/which-chromedriver-version-is-compatible-with-which-chrome-browser-version#answer-49618567) )

// EDIT 2
* I forced to use `ChromeDriver 77.0.3865.40`.
* And updated the following file 
`/Users/ME/.nvm/versions/node/v8.16.0/lib/node_modules/selenium-standalone/lib/default-config.js`
as 
```
chrome: {
      version: '77.0.3865.40',  // Originally '2.43'
      arch: process.arch,
      baseURL: 'https://chromedriver.storage.googleapis.com'
    },
```
* Restarted `selenium-standalone`
* But no luck. Still seeing `data:,`

Any comment would be very helpful.
Thanks

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  run `wdio wdio.e2e.conf.js` // my wdio config file
2.  browser is open
3.  but the address bar of browser shows `data:,` instead of `https://my-website.com`.
4.  test fails

## Your Environment
* MacOS: Mojave 10.14.6
* Chrome:  77.0.3865.90
* Selenium-standalone: 6.16.0
* Webdriverio: 4.13.2

**Comment by kylewhitaker** [comment]
@Taewa It seems you might be missing the install step to get the driver you need. I recommend creating a custom config file and then running the install and start CLI commands. You'll need to update selenium-standalone to version 6.17.0 to use the `ignoreExtraDrivers` flag.

**selenium-custom-config.js**
```js
module.exports = {
  ignoreExtraDrivers: true,
  drivers: {
    chrome: {
      version: '77.0.3865.90',
      arch: process.arch,
      baseURL: 'https://chromedriver.storage.googleapis.com'
    }
  }
};
```

Execute the install and start commands.
```
selenium-standalone install --config=/path/to/selenium-custom-config.js
selenium-standalone start --config=/path/to/selenium-custom-config.js
```

**Comment by nsklyarov** [comment]
after resolve this issue - https://github.com/vvo/selenium-standalone/issues/468
specifying the exact version of chrome is not required?

**Comment by frathe** [comment]
Finding the correct way to configure the chrome version in the codeceptjs config was painful, since there is no documentation of this.
I just leave this here should anybody else fall into this pit:
```
exports.config = {
    helpers: {
        WebDriver: {
            seleniumArgs: {
                drivers: {
                    chrome: {
                        version: '85.0.4183.83',
                        arch: process.arch,
                        baseURL: 'https://chromedriver.storage.googleapis.com'
                    },
                }
            }
        },
    }
};
```

**Comment by andreyagra** [comment]
@frathe I' facing the same problem... but how could I use this configuration to update my environment? I didn't find an answer anywhere.

**Comment by mgrybyk** [comment]
Thanks for posting the answer!
