### ISSUE TITLE
Custom path to hub to support selenium v4

### ISSUE THREAD

**Issue by mgrybyk** [vvo/selenium-standalone#449]
## Expected Behavior
I'd like to be able to change hardcoded path from `/wd/hub` to `/` to make selenium standalone work with selenium v4

## Current Behavior
- have to pass `seleniumArgs: 'standalone',`
- have to wait for one minute for [checkStarted](https://github.com/vvo/selenium-standalone/blob/master/lib/check-started.js#L6) to complete because the status path is hardcoded and set to `/wd/hub` https://github.com/vvo/selenium-standalone/blob/49afd90a65398586494115f280fb91a698343bde/lib/get-selenium-status-url.js#L74

## Steps to Reproduce

1.  download latest [selenium v4](https://selenium-release.storage.googleapis.com/4.0-alpha/selenium-server-4.0.0-alpha-3.jar) to `.selenium/selenium-server/4.0.0-alpha-3-server.jar`. (selenium-standalone [can't download](https://github.com/vvo/selenium-standalone/issues/445) selenium v4)
2.  specify selenium version `version: '4.0.0-alpha-3',`
3.  specify selenium args `seleniumArgs: 'standalone',` (otherwise selenium v4 can't be started!)
4.  run

## Your Environment
* Version of `selenium-standalone` that you are using: 6.15.1
* Other details that might be important: using selenium v4 alpha

**Comment by mgrybyk** [comment]
Changed locally `/wd/hub/status` to `/status` and it works like a charm.

**Comment by jonesh66** [comment]
I would like to take this up @mgrybyk

**Comment by mgrybyk** [comment]
Assigned to you, thanks a lot @jonesh66

**Comment by mgrybyk** [comment]
@jonesh66 do you still able to tackle this one?

**Comment by jonesh66** [comment]
@mgrybyk yes I can. What I was thinking is to check if the version contains '4', and if it does, I modify `const nodeStatusAPIPath = '/wd/hub/status'` to   `const nodeStatusAPIPath = '/status';`
Additionally, I want to append `seleniumArgs: ['standalone']` to the options object if the selenium version is 4. Does that sound right?

**Comment by jonesh66** [comment]
However, I was unable to see the 60 second wait as described in the bug because an error is returned if the number of attempts is less than 0. This takes about five seconds.
