### ISSUE TITLE
npm package "request" has been deprecated.

### ISSUE THREAD

**Issue by wolfoo2931** [vvo/selenium-standalone#457]
Since february the request package is deprecated and when someone installs selenium-standalon he sees a warning. 

Is a pull request welcome?

Best Regards,
Oliver

**Comment by vvo** [comment]
@wolfoo2931 Yes, PR welcome to fix that, mention me when it's ready!

**Comment by thomasschuiki** [comment]
Hi,

is this still "available"? I would like to give it a try.

@vvo Any preference which library should be used to replace _request_?
The request repo lists a few alternatives https://github.com/request/request/issues/3143. 

For example there is [bent](https://github.com/mikeal/bent) by the creator of request.

Best regards,
Thomas

**Comment by mgrybyk** [comment]
@thomasschuiki please use got https://www.npmjs.com/package/got

**Comment by mgrybyk** [comment]
If you believe bent should work better, feel free to use it.
It would be great if you can build a simple abstraction over the library to make it easier replacing them in the future

**Comment by thomasschuiki** [comment]
> If you believe bent should work better, feel free to use it.
I have no preference myself. I will try got first and if I run into issues give bent a try. 
> It would be great if you can build a simple abstraction over the library to make it easier replacing them in the future
Good idea. I will see what I can do :)

**Comment by thomasschuiki** [comment]
I created a pull request #487 to replace request with got. 

I will look into an abstraction once this is reviewed and create a new PR for that.

**Comment by mgrybyk** [comment]
Can you please do it within single PR?

Let's proceed convo in the PR
