### ISSUE TITLE
selenium-standalone does not download or start specified version of Edgedriver for Chrome-based Edge; always downloads 17134-MicrosoftEdgeDriver.exe

### ISSUE THREAD

**Issue by osmolyar** [vvo/selenium-standalone#458]
## Expected Behavior
selenium-standalone should download version of edgedriver as specified in wdio.browser.setup.config when the --config is passed as an argument to selenium-standalone install.

## Current Behavior
With the browser.config setup below, or any other variation attempting to specify the latest version of edgedriver, selenium-standalone always ignores the specified version and always installs the obsolete 17134-MicrosoftEdgeDriver.exe version of the driver, which only works with the old IE-based version of Edge.

Furthermore it ignores any javaArgs specifying a path to a manually-downloaded binary of edgedriver and always starts up the 17134-MicrosoftEdgeDriver.exe version.

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.
1.  Set up browser.config file 
`module.exports= {
    baseURL: 'https://selenium-release.storage.googleapis.com',
    version: '3.141.5',
    ignoreExtraDrivers: true,
    drivers: {
        edge: {
            version: '81.0.4044.69',
             arch: process.arch,
            // - Recent versions of the driver: https://sites.google.com/a/chromium.org/chromedriver/
           // baseURL: 'https://chromedriver.storage.googleapis.com'
        },
chrome: {
            version: '81.0.4044.69',
            // arch: process.arch,
            // - Recent versions of the driver: https://sites.google.com/a/chromium.org/chromedriver/
            baseURL: 'https://chromedriver.storage.googleapis.com'
        },
    // For running with some other manually downloaded drivers (??)
    javaArgs:[
        "-Dwebdriver.edge.driver=C:\drivers\msedgedriver.exe",
    ]
};`
2. Run selenium-standalone install --config=browser.config
3. Other browsers are installed as specified, Edge is not
4. Manually download latest edgedriver binary
4. Try specifying a javaArgs -Dwebdriver.edge.driver=<path to edgedriver> on command line with selenium-standalone start (works), or in javaArgs in browser.config (doesn't work)

## Your Environment
* Version of `selenium-standalone` that you are using: 6.17.0
* Is there another tool calling `selenium-standalone` on your behalf: No, but same result is seen if called by @wdio/selenium-standalone-service
* System/platform: Windows 10
* Other details that might be important:

**Comment by theVernon124** [comment]
Hoping for a resolution for this as well. Seems like the download urls for edge are hard-coded in `./lib/microsoft-edge-releases.js`, and judging from the `getEdgeDriverUrl()` function in `./lib/compute-download-urls.js`, the `drivers.edge.url` value doesn't get used.

**Comment by snehalkulkarni20** [comment]
Can this issue be addressed ? I am using WDIO6 and Chromium Edge version 83. However, the driver thats getting installed by default is always the legacy one 17134-MicrosoftEdgeDriver.exe
Because of this unable to execute my automation scripts on Edge. Can the compatible edge driver version 83 not be installed at runtime to solve this issue ?

**Comment by sanjeethgwd** [comment]
+1

Chromium Edge drivers fail to download, even when they are configured with another endpoint url for downloads, it defaults to baseURL(_see logs below_) from selenium-standalone 

```.js
// Options for standalone installs
const opts = {
  basePath: selenumDriverPath,
  version: '3.13.0',
  baseURL: 'https://selenium-release.storage.googleapis.com',
  drivers: {
    chrome: {
      version: '83.0.4103.39',
      arch: process.arch,
      baseURL: 'https://chromedriver.storage.googleapis.com'
    },
    edge: {
      version: '83.0.478.56',
      arch: process.arch,
      baseURL: 'https://msedgewebdriverstorage.z22.web.core.windows.net' // **ISSUE**: doesn't override default url in 
         // selenium-standalone [**DOWNLOADS LEAGACY EDGE DRIVER 17134 ONLY**]
    }
  },
```

**Error Logs**:

> selenium-standalone installation starting
> 
> (node:26192) UnhandledPromiseRejectionWarning: Error: Invalid Microsoft Edge Web Driver version see https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

**Comment by vvo** [comment]
Hey there, while I can release selenium-standalone, I cannot fix this at the moment because I have no idea anymore how to do it AND I am not even using the library I created. So you can have a look at the code and give it a try!

I am welcoming maintainers too, I have done it over the years and it went well. Thanks!

**Comment by trinhpham** [comment]
It's sad to know that. I have just reached and seen that you did an excellent library.
Just made a feature request 😢 
I am not confident enough to apply for this repository maintainer position. Let me give it a try.

> Hey there, while I can release selenium-standalone, I cannot fix this at the moment because I have no idea anymore how to do it AND I am not even using the library I created. So you can have a look at the code and give it a try!
> 
> I am welcoming maintainers too, I have done it over the years and it went well. Thanks!

**Comment by VicGrygorchyk** [comment]
Based from my experience I believe it's not an issues with this lib itself, but more about Selenium Java server, which version 3.14 doesn't support new Edge-Chromium. You can run Edge browser against Selenium server 4, but it's in alpha stage right now,

**Comment by osmolyar** [comment]
@VicGrygorchyk you can run Edge browser driver fine with Java Server if you use the Chrome-based Edge driver, using the below workaround:

-Install latest chrome-based Edge:
https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium
-Install latest edgedriver:
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/;
-Set capability { browserName: 'MicrosoftEdge'}
-Run selenium either as
a. selenium-standalone start --javaArgs="-Dwebdriver.edge.driver=<path to driver>" or
b. java -Dwebdriver.edge.driver=“<path to driver>" -jar selenium-server-standalone-3.141.59.jar

**Comment by VicGrygorchyk** [comment]
@osmolyar I didn't get the trick. Shall `-Dwebdriver.edge.driver=""` be empty string? I mean, is it expected `=""`, or should I pass a path to my `webdriver.edge.driver` ?

**Comment by osmolyar** [comment]
@VicGrygorchyk corrected formatting above; it should be the path to the driver.  (The point being that is should be possible to fix selenium-standalone)

**Comment by sanyee04** [comment]
hi @vvo, can you please add me as contributor? I created a branch to fix this issue and I'd like to create a PR, we also need it for our project.

**Comment by trinhpham** [comment]
@sanyee04 make your PR then @vvo (and others) would try to review.
If I was Vincent, I would have to trust your code first before I could give you the role.

**Comment by sanyee04** [comment]
@trinhpham I get a 403 when I try to create a branch on this repo. Without that I'm not sure how to create a PR.
![403](https://user-images.githubusercontent.com/7722563/92683812-90bb4200-f33c-11ea-95cb-e7acabc5bf63.PNG)
@vvo can you please give me enough rights to just create a branch and a PR? Otherwise I can't submit my proposed fix.
In that case I'll just create a fork and use it that way, but I'd rather share the solution with everyone as I see it's needed by some people.

**Comment by sanjeethgwd** [comment]
@trinhpham fork pull-request to upstream repo would work here..

**Comment by sanyee04** [comment]
thanks @sanjeethgwd that's correct. forked the repo and created the PR: https://github.com/vvo/selenium-standalone/pull/474

**Comment by vvo** [comment]
> hi @vvo, can you please add me as contributor?

I see you started your first PR, let's go with that!
