### ISSUE TITLE
Selenium-Standalone does not fetch the latest Edge version 83 driver

### ISSUE THREAD

**Issue by snehalkulkarni20** [vvo/selenium-standalone#459]
## Behavior
 I am using WDIO6 and Chromium Edge version 83. However, the driver that is getting installed by default is always the legacy one 17134-MicrosoftEdgeDriver.exe
Because of this unable to execute my automation scripts on Edge. Can the compatible edge driver version 83 not be installed at runtime to solve this issue ?

## Steps to Reproduce
When i use Edge in the capabilities, and execute the scripts the browser instance gets launched but no actions happen after that. And the application url is not opened.
I am using WDIO6 and Chromium Edge 83
I execute the npm script "npm run test"

Error seen on console as below:
`[0-3] 2020-06-22T04:08:39.164Z WARN webdriver: Request failed with status 500 due to Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: Retrying 3/3
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'MicrosoftEdge', 'cjson:metadata': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MicrosoftEdge',
    'cjson:metadata': { device: 'Windows Desktop', platform: [Object] }
  }
}
[0-3] 2020-06-22T04:08:40.752Z ERROR webdriver: Request failed with status 500 due to unknown error: Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:40.752Z ERROR webdriver: unknown error: Unable to parse remote response: Unknown error
    at getErrorFromResponseBody (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:121:10)
    at WebDriverRequest._request (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\request.js:148:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\index.js:44:23)
    at async remote (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriverio\build\index.js:66:20)
    at async Runner._startSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:206:50)
    at async Runner._initSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:175:21)
    at async Runner.run (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:93:15)
[0-3] 2020-06-22T04:08:40.753Z ERROR @wdio/runner: Error: Failed to create session.
Unable to parse remote response: Unknown error
    at startWebDriverSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-3]  Error:  Failed to create session.
Unable to parse remote response: Unknown error`

## Logs
`[0-12] {
  value: {
    stacktrace: 'org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)\r\n' +
      '\tat org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.Collections$2.tryAdvance(Collections.java:4717)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)\r\n' +
      '\tat java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)\r\n' +
      '\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)\r\n' +
      '\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\r\n' +
      '\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n' +
      '\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n' +
      '\tat java.lang.Thread.run(Thread.java:748)\r\n' +
      'Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: U. Last 1 characters read: U\n' +
      "Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\n" +
      "System info: host: 'D1ML31429', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'\n" +
      'Driver info: driver.version: unknown\r\n' +
      '\tat org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)\r\n' +
      '\tat org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)\r\n' +
      '\tat org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:69)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:55)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:50)\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:109)\r\n' +
      '\t... 52 more\r\n',
    stackTrace: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object]
    ],
    message: 'Unable to parse remote response: Unknown error',
    error: 'unknown error'
  },
  status: 13
}
`

## Your Environment
**WebdriverIO version: 6
**Mode: selenium-standalone
If WDIO Testrunner, running sync/async: sync
Node.js version: v12.16.2
NPM version: 6.14.4]
Browser name and version: Chromium Edge 83
Platform name and version: Windows 10
Additional wdio packages used (if applicable):@wdio/selenium-standalone service

**Comment by pjcalvo** [comment]
duplicated of https://github.com/vvo/selenium-standalone/issues/458 ?

**Comment by mgrybyk** [comment]
Should be resolved now, feel free to reopen if it's not!
