### ISSUE TITLE
Switch from install time installation to runtime

### ISSUE THREAD

**Issue by daleharvey** [vvo/selenium-standalone#46]
Currently this will pull down the required selenium and drivers at install time, this is less flexible as it means an npm install every time you want to switch versions or a double install if you want to use the programatic api to configure your version.

I think we should take out the install script from package.json, and wrap the programatic api + cli with the install process, so something similiar to:

```
var selenium = require('selenium-standalone');

var opts = { 
  seleniumVersion: '2.42.0', 
  stdio: 'pipe' 
};

// options to pass to `java -jar selenium-server-standalone-X.XX.X.jar`
var seleniumArgs = [
  '-debug'
];

selenium(opts, seleniumArgs, function(server) { 
  // or, var server = selenium();
  // returns ChildProcess instance
  // http://nodejs.org/api/child_process.html#child_process_class_childprocess

  // spawnOptions defaults to `{ stdio: 'inherit' }`
  // seleniumArgs defaults to `[]`

  server.stdout.on('data', function(output) {
    console.log(output);
  });
});
```

**Comment by daleharvey** [comment]
Not sure about how to best represent the options, but that was the basic idea

**Comment by daleharvey** [comment]
This would also fix the issue that the env flags may not be the same when installing as running, so if you configure iedriver_arch / selenium_version at install time then run again later without env flags its broken (I didnt think of that in the previous patch, apologies)

**Comment by vvo** [comment]
I do not like the "download and install selenium" step to be done at launch time. Some drawbacks:
- race conditions (multiple scripts starting, downloading, the same version)
- start selenium server means start selenium server, not download it etc.

Another approach is to have a more advanced command line AND underlying programmatic API:

```shell
selenium-standalone install (reads ENV variables)
selenium-standalone start -- [selenium Args] (reads ENV variables)
```

```js
selenium.install({
  versions: {
    chromeDriver: '2.13'
    selenium: '2.44.0',
    ieDriver: {
      version: '2.44.0'
      arch: process.arch
    }
  }
});

var server = selenium.start({
  spawnOptions,
  seleniumArgs,
  versions: {
    chromeDriver: '2.13'
    selenium: '2.44.0',
    ieDriver: {
      version: '2.44.0'
      arch: process.arch
    }
  }
});
// returns child process
```

What do you think?

**Comment by daleharvey** [comment]
Hrm, well the race conditions would be introduced by taking the install step out of `npm install` either way, but good point they will need to be fixed, I do think maintaining seperate install + start functions would be useful, how about `install` | `start` | `run` where run is sugar for install + start

```
selenium.run({
  versions: {selenium: '2.42.0'}
}, function(err, server) {
  .... yay 
});
```
is mostly how I would like to consume the api

Happy to take your suggestions on how best to present args vs flags

**Comment by vvo** [comment]
@daleharvey While I do understand you need "run", it's only install + start done in series and not a lot of people seems to need this feature. It would confuse the API consumers from my point of view.

As for ENV/Flags, if you do implement it, use https://github.com/dominictarr/rc and document that selenium standalone uses this library.

But in examples, just use flags which are prettier.

What do you think?

**Comment by daleharvey** [comment]
So I am thinking in terms of API cleanliness / ease of use, right now we have 

```
$ npm install selenium-standalone -g 
$ start-selenium
```
or 
```
$ npm install selenium-standalone -g 
// In a script
var selenium = require('selenium-standalone');
selenium();
```

This is nice and simple 2 step process, however its main problems are:

```
$ SELENIUM_VERSION=2.42.0 npm install selenium-standalone
// In a script without SELENIUM_VERSION defined
var selenium = require('selenium-standalone');
selenium();
```
This will fail (similiarly with the cli), also if you get a corrupt download (or `rm -rf .selenium`) then `npm install` will do nothing and your install is broken until you `rm -rf node_modules/selenium-standalone`

I would like to maintain the simplicity of the current setup, but improve its ease of use when switching versions and improve its robustness when downloading fails. 

Moving to a runtime install means we can switch between versions with no `npm install` if we do it via `selenium()` or `selenium.run()` then it means we can maintain the 2 step api process but improve robustness and simplicity

**Comment by vvo** [comment]
> $ SELENIUM_VERSION=2.42.0 npm install selenium-standalone
> // In a script without SELENIUM_VERSION defined
> var selenium = require('selenium-standalone');
> selenium();
> This will fail (similiarly with the cli)

Yes, selenium() should be able to choose the selenium version if we wanted to.

> I would like to maintain the simplicity of the current setup, but improve its ease of use when switching versions and improve its robustness when downloading fails.
> 
> Moving to a runtime install means we can switch between versions with no npm install if we do it via selenium() or selenium.run() then it means we can maintain the 2 step api process but improve robustness and simplicity

I will not make selenium() both download AND run selenium. I do prefer your proposed .run().

If we refactor the project I would like to do as I stated in my comment https://github.com/vvo/selenium-standalone/issues/46#issuecomment-68518462.

When we are done refactoring in two steps (install, start) I will accept your proposition about the "run()" function because yes in some situations, it might be easier.

So with install, start, run (can we find a better explicit name?) both as cli and programmatic APIS, we will cover a lot of cases.

And if we want to keep it backward compatible we could make npm install run npm run-script run (but maybe not a good idea).

What do you think?

> also if you get a corrupt download (or rm -rf .selenium) then npm install will do nothing and your install is broken until you rm -rf node_modules/selenium-standalone

About failing downloads that's another issue we will need to cover in any case.

**Comment by vvo** [comment]
@daleharvey ping

**Comment by daleharvey** [comment]
Done in v3 :)
