### ISSUE TITLE
Webdrivers not found on path in TypeScript project

### ISSUE THREAD

**Issue by Zw3rv3r** [vvo/selenium-standalone#473]
We're using selenium-standalone in out NPM project to test Cucumber scenario's with selenium-webdriver.

In our JavaScript projects the webdrivers are automatically found.
In our TypeScript project the webdrivers are not found (Error: The ChromeDriver could not be found on the current PATH.)

It can be solved with just adding the paths to PATH (a bit ugly) but I want to know what makes the difference. There is probably a very simple solution for this but after a four hours of search I'm starting to feel a bit desperate.

Does anyone know what I do wrong?

**Comment by mgrybyk** [comment]
Please provide a reproducible example.

Closing for now but feel free to re-open.

Cheers!
