### ISSUE TITLE
Make arch and baseURL optional in tpyes

### ISSUE THREAD

**Issue by mgrybyk** [vvo/selenium-standalone#480]
## Expected Behavior

`arch` and `baseURL` should be optional in types according to [default-config](https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js) and [install](https://github.com/vvo/selenium-standalone/blob/3f9f977c8a4047b7ab73a4ac2f85c22a747b754a/lib/install.js#L36)

**Comment by mgrybyk** [comment]
Please approve https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47761

**Comment by mgrybyk** [comment]
Types were updated

**Comment by vvo** [comment]
👍
