### ISSUE TITLE
Installing more recent ChromiumEdge driver versions fails

### ISSUE THREAD

**Issue by ablok** [vvo/selenium-standalone#488]
## Expected Behavior
Running `npx selenium-standalone install --drivers.chromiumedge.version=86.0.622.69` should finish without any errors.

## Current Behavior
Installation does not complete and throws the following error: `Callback was already called.`
However, older versions, for instance 86.0.622.0 do seem to work without any issue. I looked at the zip files (https://msedgewebdriverstorage.z22.web.core.windows.net/). And it seems that the storage structure changed somewhere between these versions. So instead of having a single binary, more recent edgedriver zip files now contain multiple files and folders.

## Steps to Reproduce
`npx selenium-standalone install --drivers.chromiumedge.version=86.0.622.69` 

## Logs
Error output:
```
▶ npx selenium-standalone install --drivers.chromiumedge.version=86.0.622.69
npx: installed 80 in 6.859s
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
to: /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_mac64.zip
to: /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/.selenium/chromedriver/85.0.4183.87-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-macos.tar.gz
to: /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/.selenium/geckodriver/0.26.0-x64-geckodriver
---
chromiumedge install:
from: https://msedgedriver.azureedge.net/86.0.622.69/edgedriver_mac64.zip
to: /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/.selenium/chromiumedgedriver/86.0.622.69-x64-msedgedriver


selenium-standalone installation [==============      ] 71% 0.7s

-----
selenium-standalone installation finished
-----
/Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/node_modules/async/dist/async.js:318
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/node_modules/async/dist/async.js:318:36
    at /Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/node_modules/async/dist/async.js:2953:17
    at WriteStream.onExtracted (/Users/arjan.blok/.npm/_npx/2743/lib/node_modules/selenium-standalone/lib/install.js:483:15)
    at Object.onceWrapper (events.js:421:28)
    at WriteStream.emit (events.js:327:22)
    at finish (_stream_writable.js:657:10)
    at finishMaybe (_stream_writable.js:644:9)
    at _stream_writable.js:617:7
    at WriteStream._final (internal/fs/streams.js:355:3)
    at callFinal (_stream_writable.js:610:10)
```

## Environment
I am running on a Mac.

**Comment by mgrybyk** [comment]
one word here is - god damn edge. 🥇 

> The latest edge available for macos is 87, the latest edge driver is 89.

starting somewhere in the middle of v86 edge requires `libc++.dylib`.
If you have edge 86 it would work, but not for version 87.

Edge driver version 87 still requires `libc++.dylib` (or something) but edge is not shipped with it.

I haven't found any solution on how to run edge driver 87 on MacOS (it's not related to selenium standalone anyhow).

Conclusion: either stay on v86 or upgrade to v88.
v87 just doesn't work, the latest tested version is `87.0.669.0`
