### ISSUE TITLE
Latest selenium-standalone uses old chrome driver

### ISSUE THREAD

**Issue by Gennadiii** [vvo/selenium-standalone#490]
## Expected Behavior
I expect chrome driver v87 to be started

## Current Behavior
chrome driver v85 is started

## Steps to Reproduce
1.  Just follow installation instructions from readme
npm install selenium-standalone@latest -g
selenium-standalone install && selenium-standalone start

## Logs
λ selenium-standalone start
14:54:40.037 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be
7d358
14:54:40.094 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium
Server on port 4444
2020-11-24 14:54:40.128:INFO::main: Logging initialized @238ms to org.seleniumhq.jetty9.util.
log.StdErrLog
14:54:40.284 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
14:54:40.685 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
Selenium started
14:54:54.972 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:54:54.974 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 12089
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:54:56.604 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:54:56.604 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 9367
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:54:57.674 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:54:57.674 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 35393
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:54:58.793 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:54:58.793 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 1269
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:56:36.070 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:56:36.070 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 5584
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:56:37.137 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:56:37.137 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 36504
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:56:38.219 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:56:38.220 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 5010
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.
14:56:39.258 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
14:56:39.259 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.seleniu
m.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDri
verService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-head
s/4183@{#1689}) on port 4117
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepi
ng ChromeDriver safe.
ChromeDriver was started successfully.

## Your Environment
* Version of `selenium-standalone` that you are using: 6.20.1
* Is there another tool calling `selenium-standalone` on your behalf: I use @wdio/selenium-standalone but for the sake of this experiment I used it directly
* System/platform: Win 10

**Comment by HananArgov** [comment]
we can see the reason here:
https://github.com/vvo/selenium-standalone/commit/a08d7f4d13872e5024126cb44231b278345a84c2

**Comment by mgrybyk** [comment]
Please set browser version explicitly

**Comment by Gennadiii** [comment]
@mgrybyk Done. But any 87.x won't work with driver 85.x

**Comment by mgrybyk** [comment]
Of course, that's why I said to set browser driver version explicitly

**Comment by Gennadiii** [comment]
It's in logs. But anyways don't see how it matters.

**Comment by mgrybyk** [comment]
The chrome browser driver major version should match the major version of your chrome browser. Chrome driver 85 usually works properly with chrome 85

**Comment by Gennadiii** [comment]
Yeah I know that. That's why I indicated only major versions. I tried wdio docs but still got driver v85.x.

**Comment by Gennadiii** [comment]
BTW isn't the reason of this package is for me to not worry about selenium server and browsers drivers?

**Comment by mgrybyk** [comment]
If you use the package properly and have browser installed that matcher browser driver versions you specified than yes
