### ISSUE TITLE
Drop NodeJS below 12

### ISSUE THREAD

**Issue by mgrybyk** [vvo/selenium-standalone#503]
minimum supported NodeJS version should be 12

- remove all the references in the code, docs, scripts, etc with the usage of NodeJS below 12
- set NodeJS version in package.json file

**Comment by Thermofish** [comment]
6.21.0 appears to have broken execution against NodeJS 8 due to the change from `request` to `got`.  These kind of breaking changes need to increase the major version to prevent downstream builds from failing.
