### ISSUE TITLE
Selenium standalone intermittently fails

### ISSUE THREAD

**Issue by daleharvey** [vvo/selenium-standalone#51]
Since merging into pouchdb the selenium tests are failing a lot more commonly than they used to be, I havent figured out why yet

**Comment by vvo** [comment]
It may be the selenium version along with your selenium client. What were you using before as a selenium server?

You mean the install fails or the server fails

**Comment by daleharvey** [comment]
The install seems to complete successfully, however connecting to it just hangs

Ill do a run using the version we were previously using to see if theres any version issues, but its intermittent so doesnt seem like there should be

**Comment by vvo** [comment]
It may be that you try connecting BEFORE it's fully loaded. I have seen selenium server taking ages to start. And it could take a more time since new versions or since you switched to selenium-standalone bc it has chromedriver? ..

**Comment by vvo** [comment]
But there's the GET request being done so that's strange, maybe log how many tries you do

**Comment by daleharvey** [comment]
Heh so I copied the "wait for startup" code we used on pouch, but I used the wrong values https://github.com/vvo/selenium-standalone/blob/master/index.js#L75 will give it 12 seconds to startup, our implementation gave it a minute https://github.com/pouchdb/pouchdb/commit/bbf577d369763608f42d6eb8a7e67f2c79e0eb04#diff-dafec2f5308cb1c6f0e56e5c381f698fL127

fairly certainly the problem, I remember having to bump it from 30 seconds to a minute because of slow selenium startups, probably switch to 90 seconds to be safe

**Comment by daleharvey** [comment]
@vvo any chance of a quick patch release before v3? this is hitting everyone who makes a PR against pouchdb and I wont be able to update to v3 for a few days?

Either way closing as its merged, thanks

**Comment by daleharvey** [comment]
Forgot to mention, fixed by https://github.com/vvo/selenium-standalone/commit/602972939ff239cded70a5e3ecdf13c66ac383c8

**Comment by vvo** [comment]
yup, made it to one minute but 200ms check, https://github.com/vvo/selenium-standalone/blob/master/lib/check-started.js#L10

So our fast computers stay fast :)
