### ISSUE TITLE
Edgedriver URL returns 400

### ISSUE THREAD

**Issue by krulletc** [vvo/selenium-standalone#528]
## Expected Behavior
Edgedriver should install from the url after running `selenium-standalone install` 

## Current Behavior
on running `selenium-standalone install` I received a 404 error for the edgedriver.
```
See more details below:
404 https://msedgedriver.azureedge.net/87.0.664.60/edgedriver_mac64.zip
Response code 404 (Not Found)
```

## Steps to Reproduce
This was run on a Mac with node v15.4.0

1.  run `selenium-standalone install`

## Logs
```
[======              ] 28%      https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_mac64.zipError in "getDownloadStream". Could not download https://msedgewebdriverstorage.blob.core.windows.net/87.0.664.60/edgedriver_mac64.zip
See more details below:
400 https://msedgewebdriverstorage.blob.core.windows.net/87.0.664.60/edgedriver_mac64.zip
Response code 400 (One of the request inputs is out of range.)
```

## Your Environment
* Version of `selenium-standalone` that you are using: 6.23.0 
* Is there another tool calling `selenium-standalone` on your behalf: no
* System/platform: Mac OS 10.15.7
* Other details that might be important:  I have the fix.  will open the PR shortly

**Comment by krulletc** [comment]
It appears that Microsoft has updated the base URL for their Edge Chromedriver. I fixed this in my branch by updating the default-config.js.  I can open a PR, but believe I need access to do so. Github gave me an unauthorized error when I attempted to push a branch to this repo.

**Comment by mgrybyk** [comment]
You don't need any access to the repp. Fork it first, then create branch in your fork, then raise PR. Look for how to raise PRs in github

**Comment by jmalczak** [comment]
I believe this is not permanently fixed:

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/1000144/104031622-3be5e600-51cd-11eb-8fc6-e97c5d1fae67.png">
