### ISSUE TITLE
Error on getDownloadStream

### ISSUE THREAD

**Issue by JuniorCtba** [vvo/selenium-standalone#534]
Version 6.23.0 
Just run
selenium-standalone install && selenium-standalone start 
![image](https://user-images.githubusercontent.com/13451867/102916229-f81b7e80-4461-11eb-9132-0ac1802720e4.png)
 
I guess that is a proxy issue, which proxy environment i should use? because i can download by the link.

**Comment by mgrybyk** [comment]
Looks like proxy issue, closing then.

What kind of proxy do you use?

**Comment by JuniorCtba** [comment]
@mgrybyk which proxy the selenium-standalone use? i have http_proxy https_proxy e no_proxy and they are working for the other package manager

**Comment by mgrybyk** [comment]
@JuniorCtba got package is used for downloading, see https://www.npmjs.com/package/got#proxies

**Comment by mgrybyk** [comment]
Are you using corporate proxy? https://github.com/vvo/selenium-standalone/issues/515#issuecomment-738250844

**Comment by JuniorCtba** [comment]
@mgrybyk yes it is a corporate.

I just want to know which proxy env the selenium is using when i am running 
selenium-standalone install && selenium-standalone start

**Comment by mgrybyk** [comment]
Not sure to be honest, I can't test it, don't have any corporate proxies I can use :(

**Comment by JuniorCtba** [comment]
@mgrybyk the is a away to set a proxy like that
selenium-standalone install --https-proxy http://localhost:8888 --http-proxy http://localhost:8888

**Comment by mgrybyk** [comment]
Does it work for you?

**Comment by JuniorCtba** [comment]
@mgrybyk sorry this was a question. :0
But will be good have the proxy setting in the cmd available

.

**Comment by mgrybyk** [comment]
What OS do you have?

**Comment by JuniorCtba** [comment]
@mgrybyk sorry for the delay, but it is windows server

**Comment by bailedk2** [comment]
@mgrybyk I have been researching this as well. I do not believe the proxy is being set correctly based on the documentation from got. Could you show an example of how you expect it to be used?
