### ISSUE TITLE
UnhandledPromiseRejection warning while starting selenium standalone server in NodeJS

### ISSUE THREAD

**Issue by MonishaGitHub** [vvo/selenium-standalone#540]
## Expected Behavior
Selenium standalone server should start in NodeJS but getting UnhandledPromiseRejectionWarning and server is not starting.

## Current Behavior

Seeing following message when starting selenium standalone server in NodeJS: npm selenium-standalone start

\AppData\Roaming\npm-cache\_npx\18720\node_modules\selenium-standalone\.selenium\chromedriver\latest-x64-chromedriver
    at AppData\Roaming\npm-cache\_npx\18720\node_modules\selenium-standalone\lib\check-paths-existence.js:16:29
    at suppressedCallback (fs.js:227:5)
    at FSReqCallback.oncomplete (fs.js:171:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce
npx selenium-standalone start in NodeJS prompt

Any suggestions how to fix this issue
Installed chrome version 87.

**Comment by mgrybyk** [comment]
Can you please provide with steps to reproduce and your system info? Can you try on another system?

**Comment by MonishaGitHub** [comment]
This is on windows 10 using CodeceptJS.
Have downloaded Selenium standalone server and using command : npx selenium-standalone start but getting the error mentioned above.

Steps performed:
mkdir qa_automation
npm init -y

npm install codeceptjs webdriverio selenium-standalone --save-dev

npm install 
npx codeceptjs init
npx selenium-standalone install
npm install chromedriver --save-dev
npx selenium-standalone start

**Comment by mgrybyk** [comment]
No need to install chromedriver if you have selenium standalone

**Comment by mgrybyk** [comment]
Then, you should run install before running start.
