### ISSUE TITLE
Chrome diver not working - it pops up and closes immediately 

### ISSUE THREAD

**Issue by amiya-pattnaik** [vvo/selenium-standalone#55]
Hi I am using the selenium-standalone alone with the webdriverIO for automation. with the latest version if I run my automation script on chrome browser, the chrome pops up and closes immediately hence test cases are failed. this issue is not appearing if I use older version of selenium-standalone which has the chrome version of 2.9. Please suggest me.

**Comment by vvo** [comment]
@amiya-pattnaik If you need a particular selenium-standalone chrome driver version, you just need to:

```shell
npm install -g selenium-standalone@latest
selenium-standalone install --drivers.chrome.version=2.9
selenium-standalone start --drivers.chrome.version=2.9
```

Let me know

**Comment by amiya-pattnaik** [comment]
Hi VVO,
thanks a lot. just want to know is it a issue with chrome driver or something else. the latest version of selenium-standale which I downloaded on Friday works fine with Safari and Firefox. only it does not work for Chrome. Could you please look into this issue? and please advise me accordingly. I appreciate your help

**Comment by vvo** [comment]
@amiya-pattnaik I have too litle information to help you I know project working fine with latest selenium-standalone, you better have a look yourself if you want to debug.
