### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by hanifahatiyabudianto** [vvo/selenium-standalone#550]
npm WARN pfm-estore@1.0.0 No description      
npm WARN pfm-estore@1.0.0 No repository field.

+ selenium-webdriver@4.0.0-beta.3
added 10 packages from 19 contributors and audited 635 packages in 6.514s

49 packages are looking for funding
  run `npm fund` for details       

found 5 vulnerabilities (3 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by mgrybyk** [comment]
Please add logs and provide with steps to reproduce

**Comment by mgrybyk** [comment]
Closed due to inactivity
