### ISSUE TITLE
Ability to launch particular version of chrome

### ISSUE THREAD

**Issue by salomegeo** [vvo/selenium-standalone#63]
Is there a way to pass down chrome version as a parameter?

**Comment by vvo** [comment]
The chrome loaded version is the one installed on the system, so you just need
to install different versions of chrome. Selenium does not installs or controls the chrome version of the system, it uses what's available.

I thik you are also free to specify another chrome browser location using this: https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location
