### ISSUE TITLE
Closing browsers

### ISSUE THREAD

**Issue by ericelliott** [vvo/selenium-standalone#67]
Everything seems to be working smoothly, except that my Firefox browser instance is left open after running all the tests. Is there a way to tell Selenium to close all the browser instances?

**Comment by vvo** [comment]
It all depends on the selenium API you are using:
- https://github.com/admc/wd#api
- http://webdriver.io/api/window/close.html

In the end, all selenium API wrappers are using https://code.google.com/p/selenium/wiki/JsonWireProtocol#DELETE_/session/:sessionId/window in the background.

So closing the window and then stopping selenium should close everything, if not, that's a selenium issue (and sadly there are lot of selenium issues you will encounter!)

**Comment by ericelliott** [comment]
I'll take a look at this again tomorrow. Thanks for the response! =)
