### ISSUE TITLE
Run headlessly through selenium.start()

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#70]
Yes, in the readme it's mentioned how to run it headlessly with

```
xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start
```

But how can I configure this when using `selenium.start()`?

Looking at the code, you spawn it with Java
https://github.com/vvo/selenium-standalone/blob/master/lib/start.js#L61

Any chance this can be tweaked to `xvfb-run` with a new option?

**Comment by vvo** [comment]
No there's no feature to do so. Doing it in the programmatic API would be a problem since xvfb-run is only available to some platforms.

If you have any idea how to implement it in a clean way, open a PR.

**Comment by binarykitchen** [comment]
Good point. Let's leave this ticket open until someone does. At the moment I cannot do a PR ...

But I can imagine this solution:
* Add a new option
* Run `which xvfb-run`, if it returns zero, throw an error, otherwise
* Replace the Java command with xvfb-run.

**Comment by vvo** [comment]
@binarykitchen if you run the program that's using selenium.start() using xvfb it should work, otherwise reopen

**Comment by binarykitchen** [comment]
how? i am starting this from gulp, so no idea how to run gulp with xvfb?

**Comment by vvo** [comment]
nope sorry

**Comment by rfranca86** [comment]
Hi ! 
I used xvfb + python + selenium + behave like this:

environment.py:
```
import os
from selenium import webdriver
from pyvirtualdisplay import Display
from selenium.webdriver.common.desired_capabilities import DesiredCapabilitie

display = Display(visible=0, size=(1280, 1024))


def before_feature(context, feature):
    display.start()
    #chromedriver = "/usr/bin/chromedriver"
    # os.environ["webdriver.chrome.driver"] = chromedriver
    context.driver = webdriver.Chrome('/usr/bin/chromedriver')
    context.driver.implicitly_wait(30)
    context.driver.maximize_window()


def after_feature(context, feature):
    display.stop()
    context.driver.quit()
```
Pyvirtualdisplay uses xvfb to start a display visible=0 (headless) then when I executed my tests with behave calling my features that executed headless with the browser I started in my environment in this case is Chrome. I was having a lot of troubles with phantomjs :)

Any doubts just say it !

**Comment by binarykitchen** [comment]
cool @rfranca86 ... but how would you combine this with a gulp task and solve this python dependency the elegant way? So that all can be just installed with `npm install`
