### ISSUE TITLE
IE does not match with current platform: LINUX

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#71]
When running `selenium-standalone start` I spotted this obscure line

```
14:58:00.273 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX`
```

Should I be worried about this? Can't IE be run headlessly on Linux?

**Comment by vvo** [comment]
IE cannot run on Linux, headlessly or not. This is only an INFO log, no worries.

**Comment by binarykitchen** [comment]
Right, stupid question of mine :)

**Comment by GrayedFox** [comment]
Anyway to silence this output then? I.E a conditional somewhere that finds Linux and then silences that output? (I'm OCD)

**Comment by vvo** [comment]
This should already be the case: https://github.com/vvo/selenium-standalone/blob/15c8761115f79871a49decbf046f43b5dfefd843/lib/start.js#L54

Otherwise that's a selenium bug

**Comment by GrayedFox** [comment]
I could be making an erroneous assumption here, as I can't quite tell from just a glance at that single file... but t is checking for 32 bit operating systems only?

**Comment by vvo** [comment]
Hi @GrayedFox so 'win32' in this case means windows, 32 or 64 bits it seems from the nodejs documentation: https://nodejs.org/api/process.html#process_process_platform

**Comment by vvo** [comment]
I think that the IE driver is a default one in selenium so that he tries to load it on every system, this is really no big deal. Is it a problem for you?

**Comment by GrayedFox** [comment]
On second thought, not so much :smile: thanks for the info and speedy response. Keep up the good work!
