### ISSUE TITLE
Gulp plugin

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#76]
Would be good to have one which is also able to kill the process upon completion.

**Comment by binarykitchen** [comment]
And make it possible to pipe jasmine tests afterwards!

**Comment by vvo** [comment]
You can build whatever awesome plugin you want with the programmatic API, but as for this repo, this is out of scope! Good luck, let me know

**Comment by binarykitchen** [comment]
Yeah, I understand. Maybe, but not now. I am too busy with work and wrote a hack to make it work with gulp for now.
