### ISSUE TITLE
Do not want to see errors when killing

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#77]
Every time I kill the selenium process I see this error:

```
     Callstack:
     -> session("delete")
     -> end()
]
  message: 'RuntimeError\n     (ECONNREFUSED:-1) Couldn\'t connect to selenium server\n     Problem: Couldn\'t connect to selenium server\u001b[1;30m\n\n     Callstack:\n     -> session("delete")\n     -> end()\n',
  name: 'RuntimeError',
  hasCallStack: true }
```

in the `process.uncaughtException` handler.

Honestly, when it is getting killed, it should not throw an ECONNREFUSED error

**Comment by vvo** [comment]
I think that's not a selenium standalone error, more a your selenium-webdriver error. Try to listen for delete and end before killing the server

**Comment by binarykitchen** [comment]
thanks but how @vvo if I have no access to the client from a gulp task running the jasmine tests and killing the process? are there any examples for that out there?

**Comment by binarykitchen** [comment]
And why aren't you mentioning this in the readme and recommend a direct `.kill()` there?

**Comment by vvo** [comment]
Sorry I misunderstood something. I do not understand the problem you are facing, maybe show me a failing git project

**Comment by binarykitchen** [comment]
forget it, all is good now. i solved this all by myself by rearranging and writing better gulp tasks, keeping all references in local scope.

**Comment by vvo** [comment]
:+1:
