### ISSUE TITLE
Firefox 36 needs Selenium 2.45

### ISSUE THREAD

**Issue by zdfs** [vvo/selenium-standalone#81]
Firefox 36 doesn't seem to work with Selenium 2.44. Can we get an update?

**Comment by vvo** [comment]
Hi,
you can select your own selenium version to install run: https://github.com/vvo/selenium-standalone#command-line-api

```shell
selenium-standalone install --version=2.45.0
selenium-standalon start --version=2.45.0
```
But the latest version of selenium-standalone already installs 2.45: https://github.com/vvo/selenium-standalone/commit/3a532e2b54e1b262c2ed202707134811b8e5d6b2

Reopen the issue if you still have problems.
