### ISSUE TITLE
How to detect if it's already running?

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#82]
Such a function call could be very useful ...

**Comment by vvo** [comment]
Sorry can you be more specific, maybe a code example?

**Comment by binarykitchen** [comment]
something like this

```coffee
gulp.task('selenium:start', (cb) ->

  if (selenium.alreadyRunning())
    cb()
  else
    selenium.start((err, seleniumProcess) ->
      if err
        cb(err)
      else
        gutil.log('Selenium instance spawned.')

        ...

        cb()
    )
)
```

**Comment by vvo** [comment]
I think that if you started selenium you should already be able to know if it's running, with a simple flag?

**Comment by binarykitchen** [comment]
no, not when i am running the same gulp task in another terminal instance

**Comment by vvo** [comment]
So if you are doing this (but that's a bad idea I think), you can check that the url `http://localhost:4444/wd/hub/status` sends a 200, then it means you have a selenium server started on your machine.

But that's really weird, you better have a single gulp task starting the selenium and then other tasks using it if you plan to start many in many terminals.

**Comment by binarykitchen** [comment]
i know, it's weird. we have a heavy backend startup sequence here and run that in a separate gulp task terminal to shorten development time. the same goes for selenium. just an exotic case here.

do you think you could wrap your idea to ping `http://localhost:4444/wd/hub/status` in a new function? i do not care if it's bad as long as it works and it's reliable enough.

**Comment by vvo** [comment]
I think it's better if you do it on your side because we do not have the requirement in the module.
