### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by grofit** [vvo/selenium-standalone#87]
I have just setup a simple test with this and webdriver io, however I noticed that in firefox I am getting CORS errors. I am not entirely sure if I need to set some args when starting up selenium-standalone to allow CORS or if I need to set it in the dependencies for webdriver io, but I thought I would ask the question incase anyone else has had/solve an issue with making CORS requests.

Just to be clear it works fine if I was just browsing and using the site in firefox normally, as the xhr and server all support CORS based requests, it just seems to be while running via selenium it doesnt, but cannot find much information on the subject.

**Comment by grofit** [comment]
The question was answered here:
http://stackoverflow.com/questions/29457206/selenium-standalone-with-cors

**Comment by vvo** [comment]
great answer for future reference

**Comment by zcmgyu** [comment]
I've created PR for --allow-cors in selenium 4

https://github.com/SeleniumHQ/selenium/pull/7540
https://github.com/SeleniumHQ/selenium/pull/7634
