### ISSUE TITLE
Using on a Linux Server

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#88]
Is there a way to get this to run in the background on a linux ubuntu server? Thanks!

**Comment by Aidanie** [comment]
Run headlessly with xvfb `xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start`

See: https://www.npmjs.com/package/selenium-standalone (near end of page)

**Comment by sean-hill** [comment]
I honestly found that right after I created this issue, sorry!

**Comment by sean-hill** [comment]
After installing `xvfb` and `selenium-standalone` and run the command above, I get this error:

	$ xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start
	execvp(): No such file or directory

	events.js:72
	        throw er; // Unhandled 'error' event
	              ^
	Error: spawn ENOENT
	    at errnoException (child_process.js:980:11)
	    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by sean-hill** [comment]
Correct, when I run `selenium-standalone start` on my ubuntu server I get this:

	$ selenium-standalone start
	execvp(): No such file or directory

	events.js:72
	        throw er; // Unhandled 'error' event
	              ^
	Error: spawn ENOENT
	    at errnoException (child_process.js:980:11)
	    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by sean-hill** [comment]
SOLVED. Had to install Java.

    $ sudo apt-get install default-jre

**Comment by vvo** [comment]
good, strangely you should get a better error message stating you need java. hmr
