### ISSUE TITLE
version backwards compatibility

### ISSUE THREAD

**Issue by benjamine** [vvo/selenium-standalone#90]
I have:
```
"selenium-standalone": "^4.2.0",
```
in my package.json, but I noticed that in last version `4.2.2`, `require('selenium-standalone')` is not a function anymore (you have to call `.install`), that's a breaking change.
I just wanted to kindly remind that you should increase the minor version when doing that (eg to `4.3.0`), that's the [semantical way](http://semver.org/) to inform that a version introduces breaking changes.
That's what NPM uses to decide what version to install, ie. when package.json says `"^4.2.0"` (which is the default syntax) it means, install the last version >= 4.2.0 and < 4.3

**Comment by vvo** [comment]
Are you sure this is the case? 4.2.0 tree [already had this change](https://github.com/vvo/selenium-standalone/blob/3a532e2b54e1b262c2ed202707134811b8e5d6b2/index.js).

I bumped 4.0.0 [when I made the change](https://github.com/vvo/selenium-standalone/blob/v4.0.0/index.js) on the programmatic API.

Let me know.

**Comment by vvo** [comment]
In fact I am a true semver believer and try to follow it.

**Comment by benjamine** [comment]
you're right (I'm not sure but maybe I had an older version on my `/node_modules` and didn't run `npm i` for a while, weird), an embarrasing case of:
![](http://www.troll.me/images/y-u-no-guy/it-doesnt-work-on-my-machine-thumb.jpg)
closing :)
