### ISSUE TITLE
Programmatic .start() does not resolve

### ISSUE THREAD

**Issue by gghez** [vvo/selenium-standalone#91]
I get an issue when calling this code:
```js
var selenium = require('selenium-standalone');
selenium.start({spawnOptions: {stdio: 'inherit'}}, function(err, child) {
     // code section never called...
});
```
Callback never called... I'm currently forced to use `selenium-standalone start` command which works fine (but I then need to encapsulate in a `spawn` call :()

I try this code after either calling `.install()` or executing `selenium-standalone install`.

**Comment by vvo** [comment]
Cannot reproduce,

what's your OS/Java version/flavor?

Node version?

**Comment by gghez** [comment]
Windows 7
![image](https://cloud.githubusercontent.com/assets/6266247/7256634/8e888256-e850-11e4-81a0-2d48372caa9a.png)


`java -version`
output:
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

`node --version`
output:
`v0.10.33`

**Comment by gghez** [comment]
My full grunt task:

```js
module.exports = function (grunt) {
	'use strict';
	var spawn = require('child_process').spawn;
	var q = require('q');

	function installSelenium(done) {
		var selenium = require('selenium-standalone');

		selenium.install({
			version: '2.45.0',
			baseURL: 'http://selenium-release.storage.googleapis.com',
			drivers: {
				chrome: {
					version: '2.14',
					arch: process.arch,
					baseURL: 'http://chromedriver.storage.googleapis.com'
				},
				ie: {
					version: '2.45.0',
					arch: process.arch,
					baseURL: 'http://selenium-release.storage.googleapis.com'
				}
				// firefox built-in with selenium
			},
			logger: function (message) {
				grunt.log.writeln(message);
			},
			progressCb: function (totalLength, progressLength, chunkLength) {
				grunt.log.writeln('Installation:', progressLength, '/', totalLength);
			}
		}, done);
	}

	function setupAndRun(containerType, done) {

		// START SELENIUM SERVICE
		var selenium = spawn(
			'node',
			['./node_modules/selenium-standalone/bin/selenium-standalone', 'start'], {
				stdio: 'inherit'
			}
		);

		// RUN TESTS
		setTimeout(function () {
			var env = process.env;
			env.CONTAINER_TYPE = containerType;

			var cucumber = spawn(
				'node',
				['./node_modules/cucumber/bin/cucumber.js', './tests/e2e/features/sample.feature'], {
					stdio: 'inherit',
					env: env
				});

			cucumber.on('close', function (code) {
				selenium.kill();
				done(code == 0);
			});
		}, 2000);
	}

	grunt.registerTask('e2e', function () {
		var done = this.async();

		if (grunt.option('install')) {
			installSelenium(done);
		} else {
			var containerType = grunt.option('container');
			setupAndRun(containerType, done);
		}
	});

};
```

**Comment by vvo** [comment]
@gghez Can you create a github repo where I could easily reproduce the behavior? Thanks

**Comment by gghez** [comment]
As soon as I get time to envolve myself, unfortunately not for the moment.

**Comment by jeremyr8r** [comment]
I haven't been able to access the child process either. I see in the documentation that we can just do the following:

var selenium = require('selenium-standalone');
selenium.start(function(err, child) {
  child.stderr.on('data', function(data){
    console.log(data.toString());
  });
});

However, I don't get anything back. I am able to access this process by passing in the spawnCb into opts like so:

var opts = {
    version: '2.46.0',
    drivers : {
        chrome: {
            version: '2.15',
            arch: process.arch,
            baseURL: 'http://chromedriver.storage.googleapis.com'
        },
        ie: {
            version: '2.46.0',
            arch: process.arch,
            baseURL: 'http://selenium-release.storage.googleapis.com'
        }
    },
    spawnCb : function(selenium){
        selenium.stderr.on('data', function(data) {
            console.log(data.toString());
        });
    },
};

In lib/start.js...is there a reason the buffers need to be flushed?

// Add empty handler to stdout and stderr so the buffers can be flushed
    if (selenium.stdout && selenium.stderr) {
      selenium.stdout.on('data', noop);
      selenium.stderr.on('data', noop);
    }

**Comment by vvo** [comment]
Both can you setup runable example or add a failing test so that we can iterate on this. thanks

**Comment by vvo** [comment]
> In lib/start.js...is there a reason the buffers need to be flushed?
> 
> // Add empty handler to stdout and stderr so the buffers can be flushed
>     if (selenium.stdout && selenium.stderr) {
>       selenium.stdout.on('data', noop);
>       selenium.stderr.on('data', noop);
>     }

Does that triggers a bad thing for you?

**Comment by jeremyrader** [comment]
I've setup an example repo with a failing tests at `https://github.com/jeremyrader/selenium-standalone-programmatic`. It appears that the data event is never being fired when I try to use the following chunk of code:
````  
selenium.start(function(err, child) {
   child.stderr.on('data', function(data){
      console.log(data.toString());
   });
});
````

I was curious as to why the buffers need to be flushed because if I remove this chunk of code the test I have setup passes : 
````
// Add empty handler to stdout and stderr so the buffers can be flushed
if (selenium.stdout && selenium.stderr) {
   selenium.stdout.on('data', noop);
   selenium.stderr.on('data', noop);
}
````

**Comment by vvo** [comment]
Maybe try to launch selenium standalone with different spawn options: https://github.com/vvo/selenium-standalone#seleniumstartopts-cb, and https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by jeremyrader** [comment]
I've added the following to my failing test : 
````
    var opts = {
        spawnOptions : {
            stdio : ['pipe', 'pipe', 'pipe'],
        }
    };
````

I have also tried with stdio : 'inherit'  and I'm still not seeing the data event fire

**Comment by vvo** [comment]
Maybe we could not flush the stdin and out, i will try to find why i did it
