### ISSUE TITLE
Managing default version upgrades via the API

### ISSUE THREAD

**Issue by nevir** [vvo/selenium-standalone#92]
Currently `wct-local` calls `install()` as a [postinstall step](https://github.com/Polymer/wct-local/blob/master/scripts/postinstall.js), which works great most of the time. But if there's an update to `selenium-standalone` that bumps selenium and/or chromedriver versions (and no corresponding update to wct-local), any call to `start()` will end up blowing up on the user.

I'd like to be able to know when the selenium or chromedriver copies are missing for the latest version, and install when possible. Right now, the only signal I have is a [`Missing ...`](https://github.com/vvo/selenium-standalone/blob/master/lib/check-paths-existence.js#L15) error message.

Unsure what the right approach is; I see a couple options:

a. Make `install()` idempotent.
b. `seleniumStandalone.start({installAsNeeded: true, ...})`
c. `seleniumStandalone.isInstalled({chrome: {...}, ...})`

**Comment by vvo** [comment]
You mean in wct-local you want to always be up-to-date with chrome/selenium versions without having to specify the versions you want?

Your best option would be to specify the version and bump wct-local when an update is released.

> a. Make install() idempotent.

It is idempotent right now I think, you always end up with the latest version installed or the specified version.

You could also call .install() (there's no redownload) before starting, it should work.

Let me know

**Comment by silvenon** [comment]
It seems I managed to get this to work, but why is the `logger` option required? It doesn't complain when I pass it an empty function.

**Comment by silvenon** [comment]
Here's how I did it, if anyone is interested:

```js
  before(function (done) {
    selenium.install({
      logger: function (message) { console.log(message); }
    }, function () {
      selenium.start(function (err, child) {
        if (err) { throw (err); }
        selenium.child = child;
        client = webdriverio.remote(clientOptions)
          .init()
          .url('http://localhost:9000', done);
      });
    });
  });
```

(This is Mocha + WebdriverIO + selenium-standalone.)

**Comment by vvo** [comment]
> It seems I managed to get this to work, but why is the logger option required on .install()? It doesn't complain when I pass it an empty function.

It should not complain about it since by default we pass a `noop` if no logger given: https://github.com/vvo/selenium-standalone/blob/96cfd5a6143ab992e4f1f890c015032d0fcc9747/lib/install.js#L27

Happy to fix it if that's really an issue.

@nevir can we close this? Do you still need some work to be done?

**Comment by nevir** [comment]
Sorry, yeah, looks like I misunderstood iy

**Comment by silvenon** [comment]
> It should not complain about it since by default we pass a noop if no logger given

It's complaining if no argument is passed, but passes if I pass it an empty object.

```js
require('selenium-standalone').install({});
```

**Comment by vvo** [comment]
You need to pass at least a function: https://github.com/vvo/selenium-standalone#seleniuminstallopts-cb
