### ISSUE TITLE
Programmatically and Headlessly

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#94]
Hey there,

    xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start

Works fantastic on my linux server. However, I'd like to now use the programattic API on my linux server, is there a way to do that?

I currently have 

	selenium.install({
		logger: function (message) {
			console.log('LOG:', message);
		}
	}, function (err) {
		selenium.start(function (err, child) {
			selenium.child = child;
		});
	});

But I know I probably need to use `xvfb-run` somehow, I'm just not sure how. Any ideas?

**Comment by sean-hill** [comment]
Hey I've tried this:

	// Selenium Standalone with Xvfb

	var selenium = require('selenium-standalone');
	var xvfb = require('headless');
	var async = require('async');

	exports.go = function() {

		async.series([

			// Xvfb
			function (done) {
				xvfb({
					display: {width: 1366, height: 768, depth: 32}
				}, function(err, child) {

					if (err) {
						return done(err);
					}

					xvfb.child = child;

					return done();

				});
			},

			// Selenium install
			function (done) {
				selenium.install({
					logger: function (message) {
						console.log('Selenium install:', message);
					}
				}, done);
			},

			// Selenium start
			function (done) {
				selenium.start(function (err, child) {

					if (err) {
						return done(err);
					}

					selenium.child = child;

					return done();

				});
			}

		], function(err) {

			if (err) {
				console.log('Selenium startup error:', err);
			}
			else {
				console.log('Selenium listening!');
			}

		});

	};

And everything properly ran with no errors, but on my server, it looks like chrome wasn't happy: 

	(UnknownError:13) An unknown server-side error occurred while processing the command.
	     Problem: unknown error: Chrome failed to start: exited abnormally
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 60.64 seconds
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	     Callstack:
	     -> init()

**Comment by sean-hill** [comment]
Figured it out! I used this library instead:

    var Xvfb = require('xvfb');
    var xvfb = new Xvfb();

Then replaced the `xvfb` section above with this:

	function (done) {
		xvfb.start(done);
	},

I also have this events listening on the process to kill the child processes created:

	function end() {

		if (selenium && selenium.child) {
			console.log('Killing selenium with PID:', selenium.child.pid);
			selenium.child.kill();
		}

		if (xvfb) {
			console.log('Killing xvfb');
			xvfb.stopSync();
		}

		process.exit(1);

	};

	process.on('SIGINT', end);
	process.on('SIGTERM', end);

Hope this helps someone!

**Comment by EvtK** [comment]
@sean-hill just checking in to let know that your solution definitely helped me out, killing selenium in a neat way.

Thanks a big bunch!
