### ISSUE TITLE
Use a proxy please! :)

### ISSUE THREAD

**Issue by sean-hill** [vvo/selenium-standalone#95]
I've tried a thousand ways to get my server's IP masked while using selenium, anyone out there have some suggestions of how to do this?

With `selenium-standalone` I've tried:

	selenium.start({
		seleniumArgs: ['-Dhttp.proxyHost=host.com', '-Dhttp.proxyPort=1234', '-Dhttp.proxyUser=username', '-Dhttp.proxyPassword=password']
	})

With 'webdriverio` I've tried:

    var options = {
        desiredCapabilities: { 
            browserName: 'chrome'
            , proxy: {
                proxyType: 'MANUAL'
                , httpProxy: 'http://username:password@host.com:port'
                , sslProxy: 'http://username:password@host.com:port'
            }
        } 
    };

I've also tried setting the `http_proxy` and `https_proxy` environment variables, but have had no luck. When my linux server requests a page using selenium and webdriverio, my server's IP is passed along in the request instead of my proxied one. 

Any help would be GREATLY appreciated :smile:.

**Comment by vvo** [comment]
Using a proxy will not always mean that your IP will be hidden. Most proxies will tell your ip to the receiving end.

What you want is an "anonymous proxy" where nobody can see your real IP. I guess it's not a selenium or selenium-standalone issue I am sorry.
