### ISSUE TITLE
Using `whereis` to locate java binary is wrong

### ISSUE THREAD

**Issue by techtonik** [vvo/selenium-standalone#96]
While debugging https://github.com/gratipay/gratipay.com/issues/3000 I found that there was an error in locating Java in 2.43.1-5 version of selenium-standalone.
```
$ whereis java
java: /usr/share/java
$ whereis -b java
java: /usr/share/java
$ ls -ls /usr/share/java
total 4
4 -rw-r--r-- 1 root root 2615 Apr 28  2014 libintl.jar
```
```
$ which java
$
```

**Comment by plessbd** [comment]
On mac one should use
/usr/libexec/java_home

see: https://developer.apple.com/library/mac/qa/qa1170/_index.html#//apple_ref/doc/uid/DTS10001702-CH1-SECTION1

**Comment by vvo** [comment]
I am happy to take any suggestion in the vvo/whereis package, maybe using https://github.com/isaacs/node-which would be better, I really dunno, let me know @techtonik @plessbd

**Comment by techtonik** [comment]
@vvo I'd go with which, it is less mystic / more straightforward.

**Comment by vvo** [comment]
@techtonik fixed, `npm install selenium-standalone@4.4.1`, try it and let me know mate

**Comment by vvo** [comment]
try 4.4.2

**Comment by techtonik** [comment]
Thanks. I wish I knew how. I don't see it as any direct dependency in https://github.com/gratipay/gratipay.com/blob/master/package.json but I am sure it is used by some of those packages.

**Comment by vvo** [comment]
Yes its grunt-webdriver

**Comment by techtonik** [comment]
Seems like this will have to wait until PR approved and new version is released.
