### ISSUE TITLE
Downloads `2.14-x64-chromedriver.zip` when version is 2.15

### ISSUE THREAD

**Issue by nickdunn** [vvo/selenium-standalone#99]
I'm using webdriverio and selenium-standalone. When I `npm install selenium-standalone --save-dev` I get `4.4.0`. When I fire up selenium I get an error:

    [Error: Missing /Users/nick.dunn/src/nuff-templates/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver]

When I check the path, I have `2.14-x64-chromedriver`. The version in default-config.js is definitely `2.15` so I'm confused as to why I'm getting the older version. Might another dependency be setting an option that is overriding this?

**Comment by nickdunn** [comment]
From my app's package.json

    "selenium-server": "^2.45.0",
    "selenium-standalone": "^4.4.0",
    "webdriverio": "^2.4.5",

**Comment by nickdunn** [comment]
In fact, running this globally also installs 2.14.

    npm install selenium-standalone -g

I was expecting 2.15.

**Comment by vvo** [comment]
try:

```sh
selenium-standalone install
```

otherwise you get any pre-installed global version
